### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by Flood** [contentful/contentful.js#100]
Hi! I've installed the latest contentful version but when starting the page I'll receive an error complaining about babel-register. I tried install babel-register but then the error is:

Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/contentful/lib/contentful.js

I don't even have a lib folder. Do you know what the error could be?

Node version: 6.3.1
Npm version: 3.10.3

I have also tried with an older version of contentful(3.6.4) but receives the same error.

I have pointed out that SystemJS should use "node_modules/contentful/index" path. If I point directly to contentful.min.js the error disappears, but "contentful" variable is missing all the methods.

This is how I use it:
```
const contentful = require('contentful');

this.client = contentful.createClient({
			space: 'xxxxxxx',
			accessToken: 'xxxxxxxxxxxxxxxxxxxx'
		})
```

Thanks

**Comment by Khaledgarbaya** [comment]
Hi @Flood ,
Looks like you are using contentful.js in an Angular 2 project.

try to point contentful package to take point the browser-dist min file
```
      contentful:{
        defaultExtension: 'js',
        main:'./browser-dist/contentful.min.js'
      },

```

**Comment by Flood** [comment]
Thank you, that did the trick!

**Comment by Khaledgarbaya** [comment]
Awesome, glad that worked, [here](https://github.com/contentful/contentful.js/blob/master/SETUP.md) is why you had the problem if you are interested.
That's why using System.import you should include the already built package
