### ISSUE TITLE
getEntries behaves unpredictably based on request options

### ISSUE THREAD

**Issue by grantglidewell** [contentful/contentful.js#1000]
## Expected Behavior

If `getEntries` returns a `page` when requesting all pages in a locale, then `getEntries` should return the same `page` if I request the `slug` that is returned from the initial request.

## Actual Behavior

`getEntries` will return nothing if the field I use to filter the requests (slug in this case) is using a fallback value
```
  ).getEntries<IPageFields>({
    content_type: 'page',
    'fields.slug[in]': slug,
    locale,
    limit: 1,
    include: 10,
  });
```

## Possible Solution

I believe this exposes the document database that contentful uses, since it isn't actually a relational database this is going to be very difficult to fix. Perhaps making the fallback more apparent instead of a late-in-the-process type shim would help the issue but not entirely resolve it.

## Steps to Reproduce

Create page (compose) content with more than one locale. set the fallback. request all page types, see the page with the fallback slug, then use that same slug to request the page specifically. 

## Context

our `slug` field is required and unique. This likely plays a role in the issue.

**Comment by gibex** [comment]
I opened a ticket with a similar issue.

**Comment by grantglidewell** [comment]
Ive recently run into a similar symptom of what I believe is the root cause of this. In some scenarios fallback values in field level localization enabled spaces do not populate. This can be replicated if you create a space with field level localization, create a content type with a field that is not localizable, create content, change the field in the content type to enable localization, observe fallbacks do not work. There is another interesting twist: if you recreate the same piece of content with the same "Entry Title" field and observe the same behavior. Create another piece of content which does not match the "Entry Title" and observe the fallback behavior is as expected now.

Again, this is a document database with pseudo relationships and when updates are made to content types or validations the existing content is not updated effectively. There are likely far-reaching ramifications of this problem and more bugs that I have not yet identified.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
