### ISSUE TITLE
Only return specific fields for linked items of a given type

### ISSUE THREAD

**Issue by penx** [contentful/contentful.js#1005]
Is it possible to specify a select operator (or similar) for linked items?

Say I have a structure:

```
NavItem.childNavItems: (NavItem | Page)[]
```

i.e. navigation can be nested, or link to pages.

I want to get a certain NavItem, and all it's child NavItems and their child NavItems, but when a Page is linked I don't want to retrieve the entire contents of Page (and the Page's linked items), just the Page.slug.

Or would I have to use the graphql api for this?

**Comment by adelindanaila** [comment]
Use `select` parameter.
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator/query-entries/console/js

**Comment by marcolink** [comment]
Hi @penx 👋 

As @adelindanaila already mentioned, `select` is your friend :)

**Comment by penx** [comment]
Hi @marcolink, please could you reopen this?

I'm aware of the select operator, that's why I referenced it in the question "specify a select operator".

I would like to be able to use the use it for linked items, as described above.

> I want to get a certain NavItem, and all it's child NavItems and their child NavItems, but when a Page is linked I don't want to retrieve the entire contents of Page (and the Page's linked items), just the Page.slug.

**Comment by marcolink** [comment]
Ok, I think I now understand what you're trying to achieve. One limitation of the rest API is, that you can only select specific fields, if you provide a single content type. What you describe is a response with mixed content types `NavItem` and `Page`. 

I recommend looking into the GraphQL API (as you already mentioned). You might also want to post your requirements in the [community slack](contentful-community.slack.com
) for visibility 😎
