### ISSUE TITLE
get item by the label of a linked entry

### ISSUE THREAD

**Issue by stickyhands** [contentful/contentful.js#102]
I figured out how it is possible to get entries by a linked entry (lets say a one-to-many Category) and thats great.

```
        let options = {
          'content_type': 'study',
          'limit': params[0],
          'skip': params[1],
          'order': params[2],
          'fields.category.sys.id': params[3],
          'fields.author.sys.id': params[4]
        };
```

but is it possible to use, lets say `fields.category.fields.label` or even better `fields.category.fields.slug`, instead of its id (here: `fields.category.sys.id`) ?

**Comment by Khaledgarbaya** [comment]
@stickyhands Unfortunately, it is not possible for now. But we are planing on improving that soon

**Comment by stickyhands** [comment]
thats a good news, is it on the roadmap yet ? Do you have a roughly ETA ?

**Comment by Khaledgarbaya** [comment]
@stickyhands Unfortunatly I can't give you and ETA for now

**Comment by groundc** [comment]
Any update on this?

**Comment by Khaledgarbaya** [comment]
@groundc @stickyhands this is not possible ,
Here is an example code to do that. Please note that you need to specify the contentType of the reference field that you will querying.
which is what am doing in `fields.bestFriend.sys.contentType.sys.id`.

```js
var contentful = require("contentful")

var client = contentful.createClient({space:"cfexampleapi", accessToken:"b4c0n73n7fu1"})

var entries = await client.getEntries({content_type: "cat", "fields.bestFriend.fields.color": "gray", "fields.bestFriend.sys.contentType.sys.id":"cat"})
```

**Comment by groundc** [comment]
Thanks a lot for your reply! Works great.

**Comment by schaparrodiaz** [comment]
@Khaledgarbaya Is there a way to do this with something other than id, so an actual field inside that nested component?

**Comment by marcolink** [comment]
@schaparrodiaz check out the last comment from @Khaledgarbaya. 
defining the content type of the nested entry is a hard requirement though!
