### ISSUE TITLE
Query Assets not returning assets with / in title

### ISSUE THREAD

**Issue by dmorrow** [contentful/contentful.js#103]
* **Node Version**: v4.4.5
* **Npm Version**: 3.9.2
* **Platform**: OSX 
* **Package Version**:contentful@1.2.1

When querying assets using contentful-management@1.2.1 (which I assume uses contentful@1.2.1) I do not receive Assets that have a / character in their name.
`space.getAssets({ 'query':'-preview', 'limit': 1000 })`

I am able to verify that Assets that do not have a / character in their title appear.  If I remove the query param from the request, I am able to receive the assets with the / in the title.

Strangely, the array of Asset objects that I receive matches the count of Assets I can see in the web interface.  I currently have 300+ assets that match '-preview', so I have not been able to confirm how this is possible.  I have de-duped the returned array, and there doesn't seem to be duplicates either.

**Comment by Khaledgarbaya** [comment]
Hi @dmorrow ,
If you haven't notice Contentful.js is at version **3.7.1** now, I recommend you update to the latest version.
For getting the asset in contentful@3.7.1 you need to do the following.
```js
var contentful = require('contentful')
var client = contentful.createClient({
  // This is the space ID. A space is like a project folder in Contentful terms
  space: 'SPACE_ID',
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: 'DELIVERY_ACCESS_TOKEN'
})
// This API call will request an entry with the specified ID from the space defined at the top, using a space-specific access token.
var asset = await contentful.getAssets({limit:1000})
```

**Comment by dmorrow** [comment]
Perhaps this issue should be moved to the **contentful-management** repo.  I had assumed that the read functionality of the management sdk was linked to this repo.
