### ISSUE TITLE
Can't install package via NPM

### ISSUE THREAD

**Issue by micellius** [contentful/contentful.js#105]
* **Node Version**: v6.9.1
* **Npm Version**: 3.10.8
* **Platform**: macOS Sierra (10.12.2) 
* **Package Version**:  latest

Can't install NPM package using `npm install contentful`. NPM returns 404 with empty JSON.

> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/contenful
> npm ERR! 404 
> npm ERR! 404  'contenful' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Here is my NPM configuration:

```
$ npm config list
; cli configs
user-agent = "npm/3.10.8 node/v6.9.1 darwin x64"

; userconfig /Users/user/.npmrc
strict-ssl = false

; node bin location = /usr/local/bin/node
; cwd = /Users/user/WebStorm Projects/Contentful/webapp
; HOME = /Users/user
; "npm config ls -l" to show all defaults.
```

Trying to access `https://registry.npmjs.org/contenful` directly (via browser address bar) has the same effect. Other NPM modules are loaded fine. So, I assume the problem is not with my environment.

**Comment by BernsteinA** [comment]
Try `contentful` instead of `contenful`

**Comment by micellius** [comment]
Oh, my bad. You are totally right. Thanks for figuring this out!
