### ISSUE TITLE
JS docs for sync have 'stringifySafe' and 'toPlainObject' swapped.

### ISSUE THREAD

**Issue by steve-a-jones** [contentful/contentful.js#106]
* **Node Version**: v4.3.2
* **Npm Version**: 2.14.12
* **Platform**: Darwin 15.6.0 Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64
* **Package Version**: contentful@3.8.0

From the docs at : https://www.contentful.com/developers/docs/javascript/tutorials/using-the-sync-api-with-js/

"If you'd like to store the retrieved content, you can use the convenient toPlainObject method or stringifySafe to prevent issues with circular links:"

I believe 'stringifySafe' and 'toPlainObject need to swapped here.

```
console.log(typeof contentfulResponse); // object
console.log(typeof contentfulResponse.stringifySafe()); // string
console.log(typeof contentfulResponse.toPlainObject()); // object
```

The code example also shows..

```
client.sync({initial: true})
.then((response) => {
  const stringifiedResponse = response.stringifySafe()
  window.localStorage.setItem('contentfulEntries', stringifiedResponse.entries)
})
```

Since `stringifiedResponse` above is a string, accessing the `entries` prop is not possible. To get the entries as a JSON string I believe one would need to do something like..

```
    const responseObj = response.toPlainObject(); // To handle circular references
    const entries = responseObj.entries; // Shouldn't contain circular refs here.. so safe to stringify
    window.localStorage.setItem('contentfulEntries', JSON.stringify(entries))  
```

EDIT: Looks like I still received a circular reference error with my code example above. I had to resort to:

```
    const responseObj = JSON.parse(response.stringifySafe()); 
    const entries = responseObj.entries;
    window.localStorage.setItem('contentfulEntries', JSON.stringify(entries))  
```

Hope this helps!

**Comment by Khaledgarbaya** [comment]
Hi @steve-a-jones ,
Thanks for the explanation I will definitely look into this asap, the reason of using the toPlainObject is to strip away all functions added to the response entries like delete, update and so on. This way you won't end up  storing them along with the object.

**Comment by Khaledgarbaya** [comment]
@steve-a-jones I submitted a [PR](https://github.com/contentful/slash-developers/pull/421) to fix the tutorial. Sorry about that

**Comment by steve-a-jones** [comment]
Thanks @Khaledgarbaya!
