### ISSUE TITLE
Cleanup webpack configuration and drop node v 0.10 support. 

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful.js#107]
contentful.js does not play nicely with nodejs+webpack stack. we should figure out a way to remove the two distributions folder and have only ony one compatible with both.

**Comment by Camzilla** [comment]
@kevinbarnett If you still wanna go about using webpack, how do you set it up? Any relation to this closed issue? https://github.com/contentful/contentful.js/issues/59 it seems to be fixed.

**Comment by Khaledgarbaya** [comment]
hi @Camzilla,
Yes the issue is fixed in this branch https://github.com/contentful/contentful.js/pull/108 which should be merged soon.
