### ISSUE TITLE
Accessing versions of an entity

### ISSUE THREAD

**Issue by felixjung** [contentful/contentful.js#109]
@Khaledgarbaya as you wish (https://twitter.com/khaled_garbaya/status/820995880207745024)

So, I had the following idea: Contentful does versioning of content. In the editor you can compare versions of an entry and I assume move between them. Say you put your blogs content on Contentful. Wouldn't it be cool if in your blog frontend could also access multiple versions of your blog posts?

Your blog's permalinks to posts could have a format like `domain.com/my-cool-slug/{version}`, where the `{version}` route parameter is the version of the entry on Contentful. If someone has a permalink to an outdated version, this would allow you to put a notification at the top of the post pointing to the latest version.

This of course would require the CDA SDK to expose the versions somehow. How hard would this be to do? Is it possible at all?

Thanks!

**Comment by Khaledgarbaya** [comment]
@felixjung, I think you are talking about [this](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/snapshots) :) the endpoint is there but it is not implemented yet in the sdk.

**Comment by felixjung** [comment]
Ah right! Saw this but didn't make the right connection. Also, management API so not the best choice for serving a blog, unless you add your own cache layer for fast access, right?

**Comment by Khaledgarbaya** [comment]
You maybe consider using the sync api also and compare the changes between changes

**Comment by cschagen** [comment]
It is a terrible idea from a SEO point of view ot have a domain.com/folder/versioning/ structure. Cause imagine you get 1000 awesome links, and then somebody updates that URL and the links now point to no mans land.

**Comment by felixjung** [comment]
Well the idea was to keep all versions in tact (i.e. `domain.com/folder/versioning/` would always work).

Say I have a blog post `foo` which is at version `v1`. The permalink to that version would be `domain.com/posts/foo/v1`. This post gets really hot on hackernews and I update the post to `v2`. `domain.com/posts/foo/v1` would still work, but the page would show a notification at the top with a link to `domain.com/posts/foo/v2`. So instead of having one page with a bunch of *Update MM/DD/YYYY* headlines in between, you get something that's more like a history of your blog post. You can time travel through the states of the post.

Of course you could also have `domain.com/posts/foo` always point to the most recent version and provide links to the outdated versions. Using some text diffing library you could highlight the changes, much like diffs on Github.

I don't know much about SEO, and maybe the above scenario would dilute the value of each version of the post. I just thought the idea was interesting from a technical or UX experience.
