### ISSUE TITLE
ContentType name not in sync response

### ISSUE THREAD

**Issue by fkamras** [contentful/contentful.js#113]
Is it possible to get the name of the contentType with the Sync API? I only see an id in the response.

**Comment by Khaledgarbaya** [comment]
Hi @fkamras,

Can you provide more details about your use case?

Best,
Khaled

**Comment by fkamras** [comment]
Hi Khaled,
I would like to save each entry in a seperate file and save them in directories that are named by the content type.

**Comment by Khaledgarbaya** [comment]
Hi @fkamras ,
Does this [snippet](https://runkit.com/5874e177391f8300131bee42/589855628dc09b0014911b7a) help ?

**Comment by fkamras** [comment]
Yes. I was working with the autogenerated data and this gave me these weird ids. 
Thanks!
