### ISSUE TITLE
Possibly incorrect documentation for createClient

### ISSUE THREAD

**Issue by sgronblo** [contentful/contentful.js#114]
* **Node Version**:
* **Npm Version**:
* **Platform**:
* **Package Version**:

The docs for contentful 3.8.0 on https://contentful.github.io/contentful.js/contentful/3.8.0/contentful.html mention that the param to control the number of concurrent requests is called `concurrency`. However the function here https://github.com/contentful/contentful.js/blob/v3.8.0/lib/contentful.js#L41 passes `params.rateLimit` not `params.concurrency` to `wrapHttpClient` as `concurrency`. Params is also given to `httpCreateClient`, and I didn't dig all the way into contentful-sdk-core to check if those params are expected to contain `concurrency` instead of `rateLimit` in some other place.

**Comment by Khaledgarbaya** [comment]
@sdepold Thanks for the report, I will take care of that asap, also PRs are welcome :)

**Comment by xtianjohns** [comment]
I've opened a PR, @Khaledgarbaya, would like your feedback.

**Comment by Khaledgarbaya** [comment]
@xtianjohns, LGTM. 👏

**Comment by Khaledgarbaya** [comment]
I fixed the naming in the docs, sorry for the long delay https://contentful.github.io/contentful.js/contentful/3.8.1/contentful.html
