### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by seriousManual** [contentful/contentful.js#116]
Currently the contenful SDK does not provide the possibility to be used with a proxy, is this a planned feature for the future?

**Comment by zcei** [comment]
Hej Manuel,

if I understand https://github.com/contentful/contentful.js/issues/16#issuecomment-169688343 correctly, this is already possible using a different module called [`https-proxy-agent`](https://www.npmjs.com/package/https-proxy-agent).
Afterwards you pass it as the `agent` property and `axios` will use it.

Though I think that can be solved better, if we would pass through a `proxy` property to `axios` as well. This should be rather easy, but [in a different place](https://github.com/contentful/contentful-sdk-core/blob/c79dc19d14a5c84e1b42704c4a553d4b8361a451/lib/create-http-client.js#L19). Of course we'd be happy to review a PR 🙂

**Comment by seriousManual** [comment]
hi,
thank you for your answer, I'm not perfectly clear where I should assign that https-proxy-agent, should this be a parameter for the createClient method?

````javascript
let client = contentful.createClient({
        host: configuration.host,
        space: configuration.spaceId,
        accessToken: configuration.accessToken
    })
````

**Comment by zcei** [comment]
Yes, that *should* be working, haven't tried for myself, though.

From what I see the `params` are passed through from [here](https://github.com/contentful/contentful.js/blob/master/index.js#L17-L18) to [here](https://github.com/contentful/contentful.js/blob/master/lib/contentful.js#L67) to eventually end up in [`contentful/contentful-sdk-core`](https://github.com/contentful/contentful-sdk-core/blob/master/lib/create-http-client.js#L19) where the `agent` property is extracted and [passed to `axios`](https://github.com/contentful/contentful-sdk-core/blob/master/lib/create-http-client.js#L39-L45).

**Comment by Khaledgarbaya** [comment]
@seriousManual , I think using proxies is possible since the SDK is using axios,
so if you pass in the proxy params in the params it should work 

```js
let client = contentful.createClient({
        host: configuration.host,
        space: configuration.spaceId,
        accessToken: configuration.accessToken,
        proxy: {
           host: '127.0.0.1',
          port: 9000,
         auth: : {
          username: 'mikeymike',
          password: 'rapunz3l'
       }
})
```
but still not 100% sure I need to dig deeper in the code

**Comment by Khaledgarbaya** [comment]
@seriousManual, do you still need help with this ?

**Comment by seriousManual** [comment]
hi, sorry i did not saw your reply on this, thank you!
will check this out and close this if it worked out as expected!

**Comment by seriousManual** [comment]
hi, its actually not possible to do it the way you described it (via the proxy config parameter), it is necessary to pass a `agent` configuration key which holds an https proxy agent which in turn will be used by axios to connect to the proxy.

**Comment by Khaledgarbaya** [comment]
@seriousManual ,
I will add this to my list but unfortunately, I can't give an ETA on this
