### ISSUE TITLE
 [ERROR] Status: 404 - Not Found - Message: The resource could not be found. - Request ID

### ISSUE THREAD

**Issue by EliseiNicolae** [contentful/contentful.js#1165]
## Expected Behavior
No error 😄 

## Actual Behavior
I got this error when I was trying to setup the cms-contentful vercel example:
` [ERROR] Status: 404 - Not Found - Message: The resource could not be found. - Request ID`

Github repo: https://github.com/vercel/next.js/tree/canary/examples/cms-contentful
Tutorial: https://www.youtube.com/watch?v=S-NsDgoaCTo&t=395s

## Steps to Reproduce
Run follow command: `npx cross-env CONTENTFUL_SPACE_ID=X CONTENTFUL_MANAGEMENT_TOKEN=Y npm run setup`
where `X = contentful space id` ( https://app.contentful.com/spaces/yinr6xmquurm/api/keys/52HPXp9WVbgfulpeNJhfHw)
`Y = CONTENTFUL management token` (https://app.contentful.com/spaces/yinr6xmquurm/api/cma_tokens)

![image](https://user-images.githubusercontent.com/43387542/158560079-ee2833fe-f87d-455f-8c21-9664a3ee9101.png)

## Environment

-   **Language Version**: v16.14.0
-   **Package Manager Version**: 
-   **Browser Version**: git bash
-   **Operating System**: Windows
-   **Package Version**: 
-   **Which API are you using?**:

**Comment by dotnetcraig** [comment]
Same error for me. Even followed the official demo to the letter; https://www.contentful.com/nextjs-starter-guide/ 

Very frustrating. Tried removing the node_modules and package-lock.json with fresh npm install, as suggested in an older issue log but still no joy. Then tried creating a new space with fresh access keys. Still same error.

**Comment by andreascful** [comment]
Hello,
I tried to reproduce the error while following the tutorial but it did not occure. The only time the error occured was when the space ID was not correct. Please make sure that the space ID is correct (e.g. you are not accidentially using the environment ID) and also that the env variable is set correctly in case you are using one to pass it to the command.
