### ISSUE TITLE
Ordering based on reference/linked fields

### ISSUE THREAD

**Issue by Techn1x** [contentful/contentful.js#1170]
I've skipped the standard bug/issue template because this is more of a question rather than a bug and the fields didn't seem relevant. Please let me know if I should fill it out.

---

We have a content model `lessonPreview` that links to a single `lessonData` entry. That entry contains various fields about a lesson, including an `activityNumber` field and `precinct` field.

We would like to shape a request that pulls down `lessonPreview` entries, ordered by `lessonData.activityNumber`.

We can _filter_ on linked fields, like so, and it works great
```js
this.client.getEntries({
  content_type: 'lessonPreview',
  'fields.lessonData.sys.contentType.sys.id': 'lessonData',
  'fields.lessonData.fields.precinct[in]': 'some-precinct',
})
```

Ideally, we could do this to also apply ordering;
```js
this.client.getEntries({
  content_type: 'lessonPreview',
  'fields.lessonData.sys.contentType.sys.id': 'lessonData',
  'fields.lessonData.fields.precinct[in]': 'some-precinct',
  order: 'fields.lessonData.fields.activityNumber',
})
```

But that doesn't seem to work (`400` error, "The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field."). Is there a way to achieve this? Otherwise, is this functionality on the roadmap?

In simple cases it's "workaroundable" by ordering client-side, but when it comes to pagination, that gets a lot trickier and we really need to be able to order via the request.

Thanks!

**Comment by gibex** [comment]
Not possible. 

`Collection Order
The GraphQL Content API allows users to specify the fields and direction to sort on root collection queries.`

**Comment by Techn1x** [comment]
Would you mind linking me to where that sentence comes from? thanks. I'm not using graphql but I assume the same applies.

Feels like this would be a very useful feature of the API

**Comment by gibex** [comment]
Sure, I hit on same issue when using rest API and trying to sort by compose pages

https://www.contentful.com/developers/docs/references/graphql/#/reference/collection-order

**Comment by Techn1x** [comment]
closing - issue has run its course. thanks for the info
