### ISSUE TITLE
How do I get the tag ID and tag name of the Tags set on the content?

### ISSUE THREAD

**Issue by Gullinkambi-Whip** [contentful/contentful.js#1179]
I would like to get the ID and name of the Tag set in the Tags tab of Content on the article page.  

I am using Next.js and I am getting the article data in ```getStaticProps``` as follows.
```TypeScript
const slug = context.params?.articles;
const articleData = await client.getEntries({
  content_type: "articles",
  "fields.slug": slug,
  limit: 1,
});

return { props: { articleData } }
```

I was able to get the list of tags set in the article from this ```articleData```, as well as the id, but it did not include the tag name.

![meta](https://user-images.githubusercontent.com/78286433/159197671-6e7fe997-b53a-46ed-b516-0b5c02a854f2.JPG)

I would like to display the tag name on the screen as follows.

```html
<a href={`/tags/${tag.id}`}>{tag.name}</a>
```

---

The following solutions are currently possible.

1. Loop through the tags array that can be retrieved with the current code and pass the tag ID to [getTag](https://contentful.github.io/contentful.js/contentful/latest/ContentfulClientAPI.html#.getTag) to get the tag name.
2. Pass the appropriate query to [getTags](https://contentful.github.io/contentful.js/contentful/latest/ContentfulClientAPI.html#.getTags) to obtain the tag name.

With the method 1. you can also get the tag name, but I think you are doing something redundant.  
I did not know what query to pass for method 2.  
If I run ```getTags``` without passing a query, I get both tag ID and tag name, but I get all tags, not just the tags set in the article.

If you have a simple and easy solution, I would like to know.  
Thank you.

**Comment by marcolink** [comment]
Hi @Gullinkambi-Whip 👋 

Both scenarios you described are working for such cases. There is currently no way to filter tags on the tags collection endpoint.  For now, the most straightforward solution is to fetch all tags once and filter with your tag ids. 

Best 
Marco
