### ISSUE TITLE
Missing Snapshots API

### ISSUE THREAD

**Issue by notbear** [contentful/contentful.js#1190]
Getting error while trying to fetch snapshots or single snapshot/revision from existing content entry.

## Expected Behavior

According to [documentation](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/snapshots/entry-snapshots-collection/get-all-snapshots-of-an-entry/console/js) the SDK should return a list of items reflecting the previously published versions of the entry

## Actual Behavior

The getSnapshots() method of Entry seems to be missing 
(moreover the example provided in documentation mentions a getEnvironment method of space which seems to be missing as well)

## Steps to Reproduce

1. getSnapshots 
1.1 Run the JS code as below
```
client = createClient({space, token, host})
const entry = await client.getEntry('some-entry-id',{content_type: 'article', select: 'fields.slug,sys.revision'} )
const snapshot = await entry.getSnapshots()
```
1.2 Getting error: `entry.getSnapshots is not a function`

## Context

I need to compare some field (eg slug) of currently published content with historical versions. 

## Environment
```
-   **Language Version**: 16.13.0
-   **Package Manager Version**: 8.1.0
-   **Operating System**: Linux hhh 5.4.0-104-generic #118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-   **Package Version**: 9.1.18
-   **Which API are you using?**: Content Management
```

**Comment by marcolink** [comment]
Hey @notbear 👋 

Snapshots only exist on the content management API. 

We have a separate client for it: 
https://github.com/contentful/contentful-management.js

cheers
Marco
