### ISSUE TITLE
Publish latest versions to NPM

### ISSUE THREAD

**Issue by xtianjohns** [contentful/contentful.js#121]
* **Node Version**: `v6.9.2`
* **Npm Version**: `3.10.9`
* **Platform**: `macOS`
* **Package Version**: `*`

Hey team, would it be possible to get a version bump on NPM (through `4.0.2`)? My team would prefer to install from the registry rather than Github, and we're interested in getting some updates since `3.8.1` (such as TypeScript declarations).

Thanks for all of your hard work!

EDIT: It appears that consumers cannot install this package directly from Github because the package's `package.json` file is missing a specified version. If this is intentional, then I suppose that's fine. But if it isn't something the Contentful team has a problem with, I think it would be great to include the version number so that we could install directly and avoid the registry if needed. Please advise.

**Comment by Khaledgarbaya** [comment]
@xtianjohns the new version version is already in npm under the `@beta` tag so if you do `npm i contentful@beta` you should get `v4.0.2`, it should be fairly stable but we want to give it some time until we are sure that everything is fine

**Comment by Khaledgarbaya** [comment]
I added a not in the release not, sorry about the confusion

**Comment by xtianjohns** [comment]
Fantastic, `@beta` works. Thank you for the updated release notes, much appreciated.

**Comment by Khaledgarbaya** [comment]
@xtianjohns I would love to hear your feedback on the new beta, you may noticed already that the bundle size has decreased a lot
