### ISSUE TITLE
Enhancement: getEntries and getEntry query suggestions based on well known search parameters

### ISSUE THREAD

**Issue by lancegliser** [contentful/contentful.js#1222]
The current client provides this interface:
```ts
export interface ContentfulClientApi {
    getEntries<T>(query?: any): Promise<EntryCollection<T>>;
    getEntry<T>(id: string, query?: any): Promise<Entry<T>>;
}
```

The documentation for [search parameters](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters) provides some well known values, such as `limit` and `skip`.

Even a minimal redefinition by developers wrapping that can provide users with helpful defaults while maintaining flexability:

```ts
type QueryFields<T> = {
  [P in keyof T & string as `fields.${P}`]?: T[P];
};

type GetEntries<T> = (
  query?: Record<string, any> & {
    limit?: number;
    skip?: number;
  } & QueryFields<T>
) => Promise<EntryCollection<T>>;
```

## Expected Behavior

What could be discovered or is well known is provided well typed to speed user discovery and deprecation handling.

## Actual Behavior

No suggestions are provided.

## Possible Solution

The well known, simple types such as `limit`, `skip`, `order`, etc are all stubbed allow you to add anything else you like similar to the pattern above. In addition we use the existing generic to pull the fields as suggestions for the user.

## Steps to Reproduce

Start a query like the below:
```ts
export interface TypeCareerPostingFields {
    title: Contentful.EntryFields.Symbol;
    slug: Contentful.EntryFields.Symbol;
    publishDate: Contentful.EntryFields.Date;
    tags: Contentful.EntryFields.Symbol[];
    url?: Contentful.EntryFields.Symbol;
    active: Contentful.EntryFields.Boolean;
    location: Contentful.EntryFields.Symbol;
    remote: Contentful.EntryFields.Boolean;
    division: Contentful.EntryFields.Boolean;
    jobDescription: Contentful.EntryFields.Text;
}

 client.getEntries<TypeCareerPostingFields>({
    content_type: ContentModels.CareerPosting,
  });
```

Start typing to add `limit` or `slug` and note it's not a suggested parameter.

## Context

Learning the API, mostly through usage as I inherit a project. Found the client, and tried to view the available parameters.
Currently trying to install `@contentful/rich-text-react-renderer` as well which I'm plugging `*Fields` generated types into the generic.

## Environment

-   **Package Manager Version**:  8.6.0
-   **Browser Version**: Chrome (but not relevent)
-   **Operating System**: Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
-   **Package Version**: contentful: 9.1.12
-   **Which API are you using?**: Delivery

**Comment by marcolink** [comment]
Hey @lancegliser,
To address all these enhancements, we have completely rewritten the client in Typescript. 

You can check it out on [npm](https://www.npmjs.com/package/contentful) under the beta-v10 tag (go to the "Versions" tab to find it). The [migration guide](https://github.com/contentful/contentful.js/blob/beta-v10/MIGRATION.md#migration-to-contentfuljs-10x) and updated v10 [README](https://github.com/contentful/contentful.js/blob/beta-v10/README.md) and can be found on the [beta-v10 branch](https://github.com/contentful/contentful.js/tree/beta-v10). All details on the new Typescript features can be found [here](https://github.com/contentful/contentful.js/blob/beta-v10/TYPESCRIPT.md).

I'd be curious to hear if this is what you need?

**Comment by lancegliser** [comment]
I am giddy with anticipation. It's so pretty! 🤩
