### ISSUE TITLE
[beta-v10] The type for `metadata.tags` doesn't match data returned by the `getEntry` method

### ISSUE THREAD

**Issue by NWRichmond** [contentful/contentful.js#1237]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `contentful@10.0.0-beta-v10.5` for the project I'm working on.

The [`Metadata`](https://github.com/contentful/contentful.js/blob/beta-v10/lib/types/metadata.ts) type's `tags` property appears to be missing a `sys` property that's in the client response.

The type indicates that the `tags` data should be an array of:
```ts
{ type: 'Link', linkType: 'Tag', id: string }
````

But when we compare this to the response from `contentfulClient.withoutUnresolvableLinks.getEntry`:
```js
{
  "metadata": {
    "tags": [
      {
        "sys": {
          "type": "Link",
          "linkType": "Tag",
          "id": "someTagId"
        }
      }
    ]
  },
  // ...`fields` and `sys`
}
```

, it seems that the `Link<'Tag'>`s should be contained in a `sys` property.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/contentful/dist/types/types/metadata.d.ts b/node_modules/contentful/dist/types/types/metadata.d.ts
index ca2d09a..0c0a348 100644
--- a/node_modules/contentful/dist/types/types/metadata.d.ts
+++ b/node_modules/contentful/dist/types/types/metadata.d.ts
@@ -1,4 +1,4 @@
 import { TagLink } from './link';
 export declare type Metadata = {
-    tags: TagLink[];
+    tags: Array<{ sys: TagLink }>;
 };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by marcolink** [comment]
Hi @NWRichmond 👋 

thanks for reporting this 🎉 
Would [this PR](https://github.com/contentful/contentful.js/pull/1240) solve the issue from your perspective?

**Comment by marcolink** [comment]
A fix has been released: https://github.com/contentful/contentful.js/releases/tag/v10.0.0-beta-v10.6

**Comment by NWRichmond** [comment]
Excellent, thanks so much!
