### ISSUE TITLE
Documentation redirects confusing. Lead to incomplete pre-release docs.

### ISSUE THREAD

**Issue by signal-intrusion** [contentful/contentful.js#124]
I had trouble finding documentation that had previously existed at https://contentful.github.io/contentful.js . Anyone downloading the package who is looking for the documentation will be directed to the 4.0.2 docs which are quite incomplete: https://contentful.github.io/contentful.js/contentful/4.0.2/ . This is really off-putting to new and old users alike.

Should the documentation links should point to **latest release**, not latest **pre-release**?
Why not redirect to https://contentful.github.io/contentful.js/contentful/3.8.1/ ?
How about a select menu for switching in between versions like the ember docs: https://guides.emberjs.com/v2.11.0/ ?

**Comment by Khaledgarbaya** [comment]
@signal-intrusion Sorry for that I'll fix it asap

**Comment by Khaledgarbaya** [comment]
This is now fixed
