### ISSUE TITLE
Link resolution is completely absent from documentation

### ISSUE THREAD

**Issue by qbunt** [contentful/contentful.js#125]
* **Node Version**: 6.9.1
* **Npm Version**: 3.10.8
* **Platform**: Mac OS
* **Package Version**: 3.8.1

Documentation on link resolution parameters in this library are simply not documented in the repo or in the documentation site. This was discovered when attempting to resolve deeply nested content. Naturally, I did what's mentioned in the Readme, which in turn pointed me to the [JS SDK site](https://contentful.github.io/contentful.js/contentful/3.8.1/ContentfulClientAPI.html#.getEntries). This also had nothing on link resolution for deeply nested content.

After a lot of hunting around on what the object structure **could** be, I found [this site](https://www.contentful.com/developers/docs/javascript/tutorials/using-js-cda-sdk/#retrieving-linked-entries), which included the `include` parameter for the query object.

      client.getEntries({content_type: 'model', include:5} ).then(entries =>{

My point is, instead of collecting the actual object structure into cohesive docs, I had to go hunting for the correct object structure to use to get what I needed. 

This optional flag could have been mentioned in a Github wiki, in the linked docs, or anywhere closer to the repo, and it would have saved me time and hassle. I understand the need to have automatically generated docs, but the SDK site I linked to above needs **a lot** of work to actually document the options and features available. Putting a parameter of an `<optional>` object does nobody any favors, especially when the object has no documented structure.

I would offer to issue a PR, but it's so difficult to determine what the actual parameters (especially with things split between contentful.js and contentful-sdk-core, I'm not sure which module is responsible.

**Comment by Khaledgarbaya** [comment]
Hi @qbunt,
I completly get your point 😞  we are working on improving that, which should be soon availeable.
