### ISSUE TITLE
Issue with include parameter.

### ISSUE THREAD

**Issue by mrsteele** [contentful/contentful.js#126]
* **Node Version**: `v6.10.0`
* **Npm Version**: `4.4.1`
* **Platform**: `Windows 10 Home 64-bit`
* **Package Version**: `v3.8.1`

We are having very inconsistent issues with the `include` parameter on the `client.getEntries` request.

Sometimes the linked entries are properly mapped to the included entries from the request, sometimes they are not.

This is our test code:

```javascript
client.getEntries({
  include: 10,
  'fields.url': 'url-slug-here',
  'content_type': 'category' 
}).then(function (entries) {
  console.log(entries.items[0].fields.featured)
  // sometimes outputs [ { sys: { type: 'Link', linkType: 'Entry', id: 'REMOVED' } } ]
  // other times outputs { sys: { ... }, fields: { ... } }
})
```

In our local tests, we can get it working again by pinning our version to `v3.7.0`. I'm not sure about the consistency after that.

**Comment by mrsteele** [comment]
scratch that, `v3.7.0` returned a Link, testing 3.3.6 as that was our original version.

**Comment by Khaledgarbaya** [comment]
Hi @mrsteele is this happening when using the preview api ?

**Comment by mrsteele** [comment]
no, but we are positive that the content is published and that doesn't explain why intermittently it shows up accurately and sometimes not.

**Comment by Khaledgarbaya** [comment]
Hi @mrsteele
It appears to be a backend issue, I transferred the ticket to our backend engineers to check what happen they should come back to you with an answer in the support channel.
Best,
Khaled
