### ISSUE TITLE
Typing issues creating utility functions around `getEntries`

### ISSUE THREAD

**Issue by lancegliser** [contentful/contentful.js#1266]
## Context

Follow on to my previous ticket where I established utility functions prior to the Typescript rewrite #1222.

Trying to create a type that includes the generics for writing utility functions seems to have issues. I want to make something like this:

```ts
export const getCareerPostingsEntries = async (query = {}) =>
  client.withoutUnresolvableLinks.getEntries<TypeCareerPostingFields>({
    ...query,
    content_type: ContentModels.CareerPosting,
  });
```

But, with strong typings. I can use `query: EntriesQueries<TypeCareerPostingFields>`, but getting the return type is an issue.

## Expected Behavior

I can access interfaces without typescript errors to enable strong typings on utility functions.

## Actual Behavior

Preface problem:
Some guide as to which `ClientWithLinkResolutionAndWithoutUnresolvableLinks` import should be used would help. I've got two options as it's not in just `contentful`:

```ts
import { ClientWithLinkResolutionAndWithoutUnresolvableLinks } from "contentful/lib/create-contentful-api";
import { ClientWithLinkResolutionAndWithoutUnresolvableLinks } from "contentful/dist/types/create-contentful-api";
```
Command clicking through `getEntries` leads me to: `node_modules/contentful/lib/create-contentful-api.ts`

If I access the exported interface, it's missing the `getEntries` and `getEntry` method:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/12085479/168086606-d9c4dd57-3c56-426c-8829-c74a9c92dc23.png">

I can find it using bracket dynamic notation:

```ts
type T2 = ClientWithLinkResolutionAndWithoutUnresolvableLinks["getEntries"]<TypeCareerPostingFields>;
```

But that has its own issues. Generics inserted into the dynamic notation give me `Expecting newline or semicolon`

Trying to create a simple generic at the bracket, and trying to use its type to provide brackets also fails:

```ts
type T3 = ClientWithLinkResolutionAndWithoutUnresolvableLinks["getEntries"];
type T4 = T3<TypeCareerPostingFields>;
```

Gives me: "TS2315: Type 'T3' is not generic."

I tried using `EntryCollectionWithLinkResolutionAndWithoutUnresolvableLinks<TypeNewsFields>` but the function now says there's a return type conflict:

```ts
export const getCareerPostingsEntries: EntryCollectionWithLinkResolutionAndWithoutUnresolvableLinks<
  TypeNewsFields
> = async (query: EntriesQueries<TypeCareerPostingFields>) =>
  client.withoutUnresolvableLinks.getEntries<TypeCareerPostingFields>({
    ...query,
    content_type: ContentModels.CareerPosting,
  });
```

```
TS2739: Type '(query: EntriesQueries ) => Promise  >' is missing the following properties from type 'AbstractEntryCollection  >': total, skip, limit, items
```

Except that's not true, because:

```ts
export type EntryCollectionWithLinkResolutionAndWithoutUnresolvableLinks<Fields> =
  AbstractEntryCollection<EntryWithLinkResolutionAndWithoutUnresolvableLinks<Fields>>

export interface AbstractEntryCollection<TEntry> extends ContentfulCollection<TEntry> {
  errors?: Array<any>
  includes?: {
    Entry?: any[]
    Asset?: any[]
  }
}

export interface ContentfulCollection<T> {
  total: number
  skip: number
  limit: number
  items: Array<T>
}
```

## Environment

-   **Language Version**: v16.13.1
-   **Package Manager Version**: 8.6.0
-   **Operating System**: Darwin Torchs-MBP-2 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
-   **Package Version**: 10.0.0-beta-v10.6
-   **Which API are you using?**: Delivery

**Comment by marcolink** [comment]
Hi @lancegliser - thanks for playing with the new beta version 🙇 

If I understand you correctly, you would like to have the response type for your `getEntries` method with a specific content type set?

In that case, this example might help:


```typescript
import {
    createClient,
    EntryFields,
    EntryCollectionWithLinkResolutionAndWithoutUnresolvableLinks,
    EntriesQueries
} from "contentful";

const client = createClient({
    space: '***',
    accessToken: '***'
})

// type for fields of content type "myContentType"
type MyFields = {
    first: EntryFields.Boolean,
    second: EntryFields.Text
    third: EntryFields.Array<EntryFields.Integer>
}

// type for querying entries of a specific content type with known fields
type MyQueryType = EntriesQueries<MyFields>

// response type for myContentType collection queries
type MyEntriesResponseType = EntryCollectionWithLinkResolutionAndWithoutUnresolvableLinks<MyFields>

export const getMyEntries = async (query: MyQueryType = {}): Promise<MyEntriesResponseType> =>
    client.withoutUnresolvableLinks.getEntries<MyFields>({
        ...query,
        content_type: 'myContentType',
    });

```

This gives you full type support on the query object for `getMyEntries` as well as a fully typed response object.

**Comment by lancegliser** [comment]
Trying that out, I have:

```ts
import {
  createClient,
  EntryCollectionWithLinkResolutionAndWithoutUnresolvableLinks,
  EntriesQueries,
} from "contentful";
import { TypeCareerPostingFields } from "../generated/contentful";

// Trying very hard not to expose the raw client to get good utility functions.
const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_KEY,
});

enum ContentModels {
  CareerPosting = "careerPosting",
}

type GetEntries<Fields> = (
  query: EntriesQueries<Fields>
) => Promise<
  EntryCollectionWithLinkResolutionAndWithoutUnresolvableLinks<Fields>
>;

export const getCareerPostingsEntries: GetEntries<
  TypeCareerPostingFields
> = async (query) =>
  client.withoutUnresolvableLinks.getEntries<TypeCareerPostingFields>({
    ...query,
    content_type: ContentModels.CareerPosting,
  });

```

Not sure what I'd done wrong, but this works. Thanks for helping sort me out!
