### ISSUE TITLE
XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by maximus8891** [contentful/contentful.js#131]
* **Node Version**: v7.5.0
* **Npm Version**: 4.1.2
* **Platform**: MacOS
* **Package Version**: contentful v4.1.1

Running the code below in the node environment:
```javascript
const contentfulClient = contentful.createClient({
    space, 
    accessToken: key
});

contentfulClient.getEntries({
    content_type: 'article',
    select: 'fields',
})
.catch(e => console.error(e))
.then(entries => {
    console.log(entries.items);
})
```

triggers the error:
```javascript
ReferenceError: XMLHttpRequest is not defined
    at dispatchXhrRequest (/node_modules/contentful/dist/contentful.js:1671:23)
```

There are no other dependencies or transpilers. Just one file with the above-mentioned code.

**Comment by Khaledgarbaya** [comment]
Hi @maximus8891 ,
is this a react native project ?

**Comment by Khaledgarbaya** [comment]
Oh wow, for some reason axios thinks it is running in the browser, I will try to fix this asap. Sorry about that

**Comment by Khaledgarbaya** [comment]
Thank a lot for the report @maximus8891 this is now fixed in https://github.com/contentful/contentful.js/pull/132 a new patch version will be out in few minutes

**Comment by maximus8891** [comment]
@Khaledgarbaya Thanks for the prompt resolution!

**Comment by bsansone** [comment]
Hi, I am experiencing this problem as well. Here is my environment:

- **Node Version:** 8.6.0
- **Npm Version:** 5.3.0
- **Platform:** MacOS
- **Package Version(s):**
    - **contentful:** 7.0.0
    - **axios:** 0.17.1
    - **webpack:** 3.8.1
    - **webpack-dev-server:** 2.11.1
    - **react:** 16.4.2
    - **react-native:** 0.54.4

My scenario may be a little different. I have a _shared_ contentful file in my project that is used across a SSR react web-app and a react-native app.

I had initially gotten everything working on the web-app, by importing contentful like this `import { createClient } from 'contentful';` but when starting to implement my work in the react-native app I was experiencing the `Unable to resolve module http` error and followed your suggested solution by importing it like this:
`const { createClient } = require('contentful/dist/contentful.browser.min.js');`
which resolved the issue in the react-native app, however when I went back to the web app to work I started to receive the error from this issue when SSR a page. I've also attempted to conditionally import based on the platform but react-native doesnt like that.
