### ISSUE TITLE
Assert could not be found within the project or in these directories:   node_modules   ../../../node_modules

### ISSUE THREAD

**Issue by mustafa-pxs** [contentful/contentful.js#1326]
## Expected Behavior

Should work with any version of node.

## Actual Behavior

Throwing Error in react-native env
node_modules/contentful/dist/contentful.node.js: assert could not be found within the project or in these directories:
  node_modules
  ../../../node_modules

## Steps to Reproduce

1. Install contentful
2. createClient as pass the params.

## Environment

-   **Language Version**: v12.18.3
-   **Package Manager Version**: v6.14.6
-   **Browser Version**: Simulator
-   **Operating System**: Mac OS
-   **Package Version**: 9.1.32
-   **Which API are you using?**: Delivery

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
