### ISSUE TITLE
Support http request cancellation (abortController signal)

### ISSUE THREAD

**Issue by jakke-korpelainen** [contentful/contentful.js#1327]
The Axios library used for http requests supports [cancellation](https://axios-http.com/docs/cancellation) via AbortController signal. However it is not possible to utilize it using the sdk.

e.g. adding cancel support for getEntries
https://github.com/contentful/contentful.js/blob/298999da245a6e8401f061254cd774ebfcad3353/lib/create-contentful-api.js#L226

could be as simple as introducing an additional `abortController` parameter to the `getEntries` function and then passing it to the http.get() axios options.

`http.get('entries', createRequestConfig({ query: query, signal: abortController.signal }))`

which of course would require a change for [createRequestConfig](https://github.com/contentful/contentful-sdk-core/blob/5006c0de3d2bde9e194e8eda245408f9354dc231/src/create-request-config.ts#L15) in **contentful-sdk-core** since `{...createRequestConfig({ query: query }), signal: abortController.signal}` or a similar approach is not that ideal.

--

Would make a PR but I guess you guys might want to figure this out as a larger adaption to all requests.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.

**Comment by ethan-ozelius-contentful** [comment]
For posterity, see this post for more info: https://github.com/contentful/contentful.js/issues/2562
