### ISSUE TITLE
TypeError: Cannot read property 'createClient' of undefined

### ISSUE THREAD

**Issue by khrome83** [contentful/contentful.js#133]
* **Node Version**: v6.9.1
* **Npm Version**: v4.1.2
* **Platform**: OSX
* **Package Version**: 4.1.2

Ever since upgrading from `3.8.1` to `4.1.2` i get this error. `TypeError: Cannot read property 'createClient' of undefined`. I am using ES6 imports and importing in `contentful`.  The exact same code works with 3.8.1, and fails with 4.1.2.

Did the interface change without updating the documentation? The version bump to 4 shows breaking changes, but the only thing I can find in the release list is the lack of support for Node v4.x.x. 

Thanks!

**Comment by ohmyguigs** [comment]
+ 1

**Comment by Khaledgarbaya** [comment]
Hi @khrome83 @ohmyguigs,
To use es6 imports with the SDK, you can do the following. 
```js
import {createClient} from 'contentful'
// OR
import * as contentful from 'contentful'
```
The Example in the README still uses require. I will add an import example also.

**Comment by Khaledgarbaya** [comment]
I added a section in the README explaining that [here](https://github.com/contentful/contentful.js#using-es6-import)

**Comment by gunturaf** [comment]
@Khaledgarbaya I cant seem to find the ES6 import documentation on the README today so I search for this problem in issues and stumble upon this one, does that documentation moved somewhere else?
