### ISSUE TITLE
Support "baggage" header in CORs 'Access-Control-Allow-Headers'

### ISSUE THREAD

**Issue by wadehammes** [contentful/contentful.js#1381]
## Expected Behavior
Sentry `baggage` header should be allowed. https://www.w3.org/TR/baggage/

## Actual Behavior

I have a json file from Contentful that won't load due to Sentry adding the new `baggage` header to the CORs request.

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/222170/181402697-9d01107a-45dd-4d89-9682-a329151f9435.png">

## Possible Solution

Add `baggage` to 'Access-Control-Allow-Headers'

**Comment by marcolink** [comment]
Hey @wadehammes 
Did you try to update to the latest version of sentry? There has been a bug reported [here](https://github.com/getsentry/sentry-javascript/issues/6077)

**Comment by Archi4400** [comment]
Hi I am using the latest versions but it doesn't work for me
`sentry/tracing": "^7.19.0"
sentry/vue": "^7.19.0"`
![Снимок экрана 2022-11-16 в 13 11 58](https://user-images.githubusercontent.com/36852464/202165655-69613966-9227-4519-bb15-8bd1c5eefbf3.png)
![Снимок экрана 2022-11-16 в 13 12 48](https://user-images.githubusercontent.com/36852464/202165766-3ed4fb2c-88c6-45c2-a289-d3bf10c34d4f.png)`

CURL
`curl 'https://salesiq.zoho.eu/visitor/v2/channels/website?widgetcode=myID****&internal_channel_req=true&browser_language=en&current_domain=http%3A%2F%2Flocalhost&pagetitle=Demo%20Lesson%20-%20Brighterly%20Main%20App&include_fields=avuid' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'Referer: http://localhost:8080/' \
  -H 'baggage: sentry-environment=local,sentry-public_key=d707d73dfaac4abb8e97d83185d0f317,sentry-trace_id=e68d49f9f3d44bf8962bf708ffdaef34,sentry-sample_rate=1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'sentry-trace: e68d49f9f3d44bf8962bf708ffdaef34-bdc14889a552823c-1' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed`
