### ISSUE TITLE
How to use entries() with linked entry IDs?

### ISSUE THREAD

**Issue by raucao** [contentful/contentful.js#14]
How can I use `client.entries()` with linked entry fields?

See https://support.contentful.com/hc/en-us/articles/200513278-How-do-I-add-categories-to-my-content-?page=1#comment_202252446 for use case.

**Comment by asross** [comment]
@ehd do you know if that's changed yet? I'd like to be able to query by associated category name without doing the intermediate request for the categories.

**Comment by ehd** [comment]
Someone please correct me if I'm wrong (cc @sdepold).

@asross It works the same as far as I know. What I do is keep a map from category names to IDs in a config file in my code so I can query by name. If your list isn't static, I would fetch the list at start up time, cache it and use that. I hope you find this helpful.

**Comment by sdepold** [comment]
cc @trodrigues :D

**Comment by ehd** [comment]
Whoops. Thanks :smile:
