### ISSUE TITLE
Create tests for typescript type definition

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful.js#143]
It would be nice to have some tests for typescript type definition file to make sure it is always in sync

**Comment by stefanjudis** [comment]
I'm playing around with typescript right. Do you have a clue already how you would do this? :)

**Comment by axe312ger** [comment]
@stefanjudis Khaled is in holidays and I used TS a few times but never created my own typings. So, nope.

Maybe @googol can assist here?

**Comment by mgeorgehansen** [comment]
I just submitted a PR (#258) with a potential testing solution using [ts-runtime](https://github.com/fabiandev/ts-runtime). If there's interest in developing this into a production-ready state please let me know and I'd be happy to collaborate on it!

**Comment by marcolink** [comment]
Related PR has been closed. will close this issue as well.
