### ISSUE TITLE
How to set rate limit using contentful creat client API

### ISSUE THREAD

**Issue by manirohit1002** [contentful/contentful.js#147]
I am looking for the rate limit to be imposed while hitting the delivery API through Contentful client created using this package.

**Comment by axe312ger** [comment]
The rate limits are imposed by the server, there is no option to set it from the client. As soon the rate limit is reached, the client waits the given time and retries the API call.

Does this answer your question? :)

**Comment by AshishJain05** [comment]
@axe312ger So on the client side how we can ensure that we are not overreaching the rate limit defined for my organization while hitting the Contentful using Delivery API. Any thoughts here will be appreciated.

**Comment by axe312ger** [comment]
Hey @AshishJain05,

`contentful.js` is automatically taking care of your hourly and other rate limits, as it waits till the given time from the `x-contentful-ratelimit-reset` header is over. 

All requests will be done, nothing will be dropped. That way we ensure compliance to the rate-limits every Organization may have individually.

Does this answer your question?  :)

Benedikt

**Comment by AshishJain05** [comment]
@axe312ger 
I am getting below error while making calls to get the entries through the client created using contentful.createClient()

I am pushing multiple calls to get the entries in promise array, so that I can take my application specific action on the resolve of all of these calls.

Any thought here?

{"sys":{"type":"Error","id":"RateLimitExceeded"},"message":"You have exceeded the rate limit of the Organization this Space belongs to by making too many API requests within a short timespan. Please wait a moment before trying the request again.","requestId":"b13c2aeeb03c1f4a49a996e3d39cf960"}

**Comment by axe312ger** [comment]
@AshishJain05 Which version of `contentful.js` and `contentful-sdk-core` are you using? I have the indention that your version is not handling rate-limits since it might be to old.

**Comment by AshishJain05** [comment]
@axe312ger 
I am using below versions-
contentful.js  - 3.8.0
contentful-sdk-core - 2.5.0

I believe contentful-sdk-core got installed as the dependency of contentful.js, as I have not installed this package separately. Please see if this information is of any help to you?

**Comment by axe312ger** [comment]
Here we go, rate-limit handling was introduced in v4.0.0 of `contentful.js` and v3.8.1 of `contentful-sdk-core`

The only breaking change was that we stopped supporting very old node versions (v0.10 and v0.12).

If you are using node v4.7 or newer, feel free to upgrade `contentful.js` to the newest version, this should fix all your rate limit problems. Also, you shouldn't have to change any line of your code, the API did not change :)

**Comment by AshishJain05** [comment]
@axe312ger Thanks for the quick responses.

I have updated the version of contentful and contetful-sdk-core to 4.3.0 and 3.9.0 respectively and it worked for me like a boon :). Now everything is fine on the hosted servers.

But my development environment is behind the proxy and it seems now after updating the versions contentful client is not accepting the proxy.

I am creating the client and passing the proxy details to it as below-

const cfClient = contentful.createClient({		
		space: CONTENTFUL_SPACE_ID,
		accessToken: CONTENTFUL_ACCESS_TOKEN,
		agent: createProxyAgent(),
		host: CONTENTFUL_HOST_NAME,
	}); 

function createProxyAgent() {
       const HttpsProxyAgent = require('https-proxy-agent');
       const httpProxy = PROXY;
	return proxyAgent = new HttpsProxyAgent(httpProxy);	
};

Is any thing has changed in the API to pass the proxy details. Any help here would be highly appreciated. Thanks.

**Comment by AshishJain05** [comment]
@axe312ger 
We are getting below error in our development environment, if this helps you to identify the issue-

{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address"
:"IP_ADDRESS_HERE","port":443,"config":{"transformRequest":{},"transformResponse":{
},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","max
ContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Conte
nt-Type":"application/vnd.contentful.delivery.v1+json","X-Contentful-User-Agent"
:"contentful.js/4.3.0","Authorization":"Bearer _TOKEN _HERE ","user-agent":"node.js/v6.10.3","Accept-Encoding
":"gzip"},"baseURL":"https://preview.contentful.com:443/spaces/SPACE_ID_HERE/","m
ethod":"get","params":{"locale":"sv-SE","content_type":"hcpEducationResourcesDig
italToolsContentPage","limit":1000},"url":"https://preview.contentful.com:443/sp
aces/SPACE_ID_HERE/entries"},"response":{"status":500}}

**Comment by axe312ger** [comment]
Hey @AshishJain05,

I am sorry, but https://github.com/TooTallNate/node-https-proxy-agent is pretty old and has some really nasty hacks for old node versions.

We introduced a dedicated proxy option a few versions ago, it is configured exactly as an Axios proxy (as it is an Axios proxy actually) --> https://github.com/mzabriskie/axios
```
proxy: {
  host: '127.0.0.1',
  port: 9000,
  auth: {
    username: 'mikeymike',
    password: 'rapunz3l'
  }
}
```

This worked for other customers, maybe this is also working fine for u?

Benedikt

**Comment by axe312ger** [comment]
https://github.com/contentful/contentful.js/releases/tag/v4.5.0 was released to address this. Closing for now. Let me know if the issue still exists.
