### ISSUE TITLE
error when performing npm install

### ISSUE THREAD

**Issue by YasBenAll** [contentful/contentful.js#1481]
I'm trying to install the packages but I'm receiving the following error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-standard@16.0.3
npm ERR! Found: eslint-plugin-promise@6.0.1
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   dev eslint-plugin-promise@"^6.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-promise@"^4.2.1 || ^5.0.0" from eslint-config-standard@16.0.3
npm ERR! node_modules/eslint-config-standard
npm ERR!   dev eslint-config-standard@"^16.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint-plugin-promise@5.2.0
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   peer eslint-plugin-promise@"^4.2.1 || ^5.0.0" from eslint-config-standard@16.0.3
npm ERR!   node_modules/eslint-config-standard
npm ERR!     dev eslint-config-standard@"^16.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

What should I do?

Node version: v16.17.0
npm version: 8.19.2

**Comment by marcolink** [comment]
Hi @YasBenAll 👋 
is this still happening with the latest version of this package?

**Comment by marcolink** [comment]
closing this for now due to inactivity - please feel free to re-open it again with additional information
