### ISSUE TITLE
Limit Parameter not Working in Contentful Sync API

### ISSUE THREAD

**Issue by sagargandhi5** [contentful/contentful.js#1489]
## Expected Behavior
client
  .sync({
    initial: true,
    limit: 10,
  })
  .then((response) => {
    console.log(response.entries);
    console.log(response.assets);
  });

This is supposed to send just 10 Records whereas I am getting a full flush of ~900 records

## Actual Behavior
client
  .sync({
    initial: true,
    limit: 10,
  })
  .then((response) => {
    console.log(response.entries);
    console.log(response.assets);
  });

Getting total records ~900 instead of 10

## Possible Solution
Need to revisit the Sync API and test the limit parameter

Possibly limit parameter is not being passed somewhere in the Sync API
## Steps to Reproduce

1.Sorry, not able to do that any developer with access to contentful should be able to test it with the sample code from the website itself
2.https://www.contentful.com/developers/docs/javascript/tutorials/using-the-sync-api-with-js/
3.
4.

## Context

I am trying to implement the delta api for changes to update frequently but not being able to as not sure if the bug will be fixed and cause a production issue on our side
## Environment

-   **Language Version**: 
-   **Package Manager Version**: 
-   **Browser Version**: 
-   **Operating System**: 
-   **Package Version**: 7.14.3 contentful version
-   **Which API are you using?**: Sync

**Comment by marcolink** [comment]
Hi @sagargandhi5,

Have you tried updating to the latest version? We're currently on **9.x**

**Comment by marcolink** [comment]
Ok, I had another look, the `limit`  parameter defines the page size for every loaded page. 
You would still get the full data set after the promise is settled, just with more requests executed. 
More on pagination on syncs can be found [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/synchronization/pagination-and-subsequent-syncs).

**Comment by marcolink** [comment]
Closing this for now
