### ISSUE TITLE
Get content related to an individual entry

### ISSUE THREAD

**Issue by paigecwilley** [contentful/contentful.js#150]
* **Node Version**: 6.9.4
* **Npm Version**: 4.2.0
* **Platform**: Darwin Kernel Version 16.3.0
* **Package Version**: contentful@4.3.0

I'm using the following to get the content for an individual entry: 
```const data = ({ id }) => client.getEntry(id);```

This entry content model has a field with a limited number of value options. I want to be able to get all the entries that have the same value in that field and display them on the same page as the entry--for example, if a blog post has a  'category' field with a value of 'press release', on an individual entry with category 'press release', I want to be able to show all the other entries that also have that 'press release' as their category in a sidebar. 

Similarly, I have individual entries with related/linked items, and I want to be able to show some of the content of the linked items--like titles--on the same page, but am only able to grab the corresponding ids, and not the corresponding content.

I have used 'include' before when getting entries by content-type, which worked. However, when getting individual entries by sys.id, rather than by content-type, it produces a circular JSON object.

**Comment by Khaledgarbaya** [comment]
Hi @paigecwilley ,

> This entry content model has a field with a limited number of value options. I want to be able to get all the entries that have the same value in that field and display them on the same page as the entry--for example, if a blog post has a 'category' field with a value of 'press release', on an individual entry with category 'press release', I want to be able to show all the other entries that also have that 'press release' as their category in a sidebar.

You may want to check the search parameters section in the API [docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters). all the  params can be passed in the query object like so 

```js
client.getEntries({content_type: 'post', 'fields.category': 'press release'})
  .then(response => {
    console.log(response.items)
  })
```

> Similarly, I have individual entries with related/linked items, and I want to be able to show some of the content of the linked items--like titles--on the same page, but am only able to grab the corresponding ids, and not the corresponding content.

Link resolution in the SDK is only done when you request your data through the collection endpoint.
`client.getEntries()`.

> have used 'include' before when getting entries by content-type, which worked. However, when getting individual entries by sys.id, rather than by content-type, it produces a circular JSON object.

Content types is so flexible and it is totally normal to get a content type that references itself. If you want to save you can use something like [`json-stringify-safe](https://www.npmjs.com/package/json-stringify-safe)` npm package.

I hope that answers all your questions, if you have more questions don't hesitate to ask.

all the best,
Khaled
