### ISSUE TITLE
How to get URL of image with Node.js library

### ISSUE THREAD

**Issue by LAMike310** [contentful/contentful.js#151]
I'm using the Node.js library to grab content data, and I'm having trouble trying to get the full image path from the response. The image object in the response looks like this:

`image: { sys: { type: 'Link', linkType: 'Asset', id: '6mSiWbl1NCAO8MqkskMWUy' } },`

If I'm trying to display an image on the frontend, how can I use this image object to make a valid URL? Do I combine the `image.id` value with another value in the response object? Any help would be appreciated!

Also, the Ruby/Rails API returns a full URL when an image is requested, is there a reason this doesn't happen for this library?

Thanks,
Mike

**Comment by axe312ger** [comment]
Hey @LAMike310,

our JS SDK does link resolution for you. Check out this: https://www.contentful.com/developers/docs/concepts/links/

That means you will have an `includes` on your request response, containing these linked entities. You can filter that `includes` array for the asset with the id of the image. The asset you just filtered out is your image, which contains the url :)

Does this help?

Benedikt

**Comment by LAMike310** [comment]
Thanks for the link, I got the assets to show by calling the 'entries' endpoint:

client.getEntries({'sys.id': ID_OF_ENTRY})
			.then(function(entry) {
				if(entry.includes) {
					let assets = entry.includes.Asset
					assets.map(a => console.log(a.fields.file.url))
				}
			})
			.catch(function (error) {
				console.log(error)
			})
