### ISSUE TITLE
Breaking change from default import to named imports

### ISSUE THREAD

**Issue by aray12** [contentful/contentful.js#154]
![image](https://cloud.githubusercontent.com/assets/8671174/26713283/b311a93c-4720-11e7-99d5-6918a4de0794.png)

The only breaking change mentioned in Releases is that you are no longer supporting less than nodev4.x. But the move from

```
import contentful from 'contentful';
```

to 

```
import * as contentful from 'contentful';
```

is also a breaking change worth mentioning. I think a lot of people look at release notes for breaking changes when they do upgrades. Hope this helps someone

Love the work btw

**Comment by axe312ger** [comment]
Thank you @aray12 :)

I added a note to the release: https://github.com/contentful/contentful.js/releases/tag/4.0.0 :)

**Comment by aray12** [comment]
@axe312ger thank!!
