### ISSUE TITLE
The standalone version can not be used without module system

### ISSUE THREAD

**Issue by stefanjudis** [contentful/contentful.js#155]
* **Platform**: MacOS
* **Package Version**: 4.4.0

I just wanted to use the standalone version (`https://unpkg.com/contentful@latest/dist/contentful.min.js`, `https://unpkg.com/contentful@4.4.0/dist/contentful.min.js`) of the project but unfortunately, it's throwing an exception. 

It starts with `module.exports=...` which doesn't work for environments without having a module loader in place.

You can find an example here 👉  https://codepen.io/stefanjudis/pen/weaKgj

It worked fine for version `4.3.0`.

**Comment by drajvver** [comment]
Simply use `https://npmcdn.com/contentful` instead, then it should be working. I don't know why would someone do that, but I've come here to write the same post as you did ;)

**Comment by Khaledgarbaya** [comment]
fixed in https://github.com/contentful/contentful.js/pull/159
