### ISSUE TITLE
v4.4.0 does not work with latest react-native

### ISSUE THREAD

**Issue by leoschweizer** [contentful/contentful.js#156]
* **Node Version**: v.7.8.0
* **Npm Version**: 4.2.0
* **Platform**: react-native 0.44.3 on iOS 10.3
* **Package Version**: contentful@4.4.0

I'm using the contentful JS-SDK in a react-native project. After upgrading from 4.3.0 to 4.4.0, the app no longer works due to contentful throwing an error on import:
```
Cannot read property '0' of null
```
in `contentful.js:11297` which is the last line of this block:
```
        else if (
          typeof context.process == 'object' && !context.process.browser &&
          (data = context.process)
        ) {
          name = 'Node.js';
          arch = data.arch;
          os = data.platform;
          version = /[\d.]+/.exec(data.version)[0];
        }
```

I've downgraded to `4.3.0` and everything works as expected again.

**Comment by Khaledgarbaya** [comment]
hi @leoschweizer,
Thanks for reporting I will check this asap.
Best,
Khaled

**Comment by leoschweizer** [comment]
@Khaledgarbaya btw, the `data` object looks like this:
```
{
    "env": {
        "NODE_ENV": "development"
    }
}
````
so `arch`, `platform` and `version` are all missing.

**Comment by Khaledgarbaya** [comment]
Hey @leoschweizer looks like it's a problem with platform.js

**Comment by Khaledgarbaya** [comment]
let's hope this PR gets fixed https://github.com/bestiejs/platform.js/pull/130
if not in the next 2 days I will maybe fork the repo and apply the patch

**Comment by Khaledgarbaya** [comment]
Hi @leoschweizer can you get this [branch](https://github.com/contentful/contentful-sdk-core/pull/26) of SDK-core and `npm link` it and test if it solves the issue for you?

**Comment by leoschweizer** [comment]
@Khaledgarbaya I can't get this to work but I'm not sure if I'm doing this correctly.

Here's what I did:

- In my app project, put contentful 4.4.0 as dependency
- Cloned the sdk-core repository in a separate directory and checked out the `fix/platform` branch
- Ran `sudo npm link` in the sdk-core directory
- Ran `npm link contentful-sdk-core` in the app directory

But the error remains the same. Since I'm not seeing the code changes either I guess I'm missing something?

**Comment by Khaledgarbaya** [comment]
hi @leoschweizer hmm can you clone `contentful.js` also and run `npm build` after step 4 and link `contentful.js` to your project ?

**Comment by leoschweizer** [comment]
@Khaledgarbaya I did, but now I ran into this: https://github.com/facebook/react-native/issues/637
- so `npm link` is not going to work with React Native for the time being.

**Comment by Khaledgarbaya** [comment]
@leoschweizer 😭  ok I will try to do some tests on other platforms and release a patch version by tomorrow. Sorry about the ping pong

**Comment by axe312ger** [comment]
Looks like we are still blocked here since https://github.com/bestiejs/platform.js/pull/130 is merged but not released yet :(

**Comment by axe312ger** [comment]
@leoschweizer I released https://github.com/contentful/contentful-sdk-core/releases/tag/v3.14.2 which should now work in react-native. Can you upgrade all your contentful.js (plus check that you got the latest contentful-sdk-core) and confirm if this is now working for you in react native? A small test on my local machine was promising :)

**Comment by leoschweizer** [comment]
@axe312ger I can confirm that it is working for me now 👍

**Comment by axe312ger** [comment]
Awesome! :)
