### ISSUE TITLE
Webp image example

### ISSUE THREAD

**Issue by SKempin** [contentful/contentful.js#1576]
How is it possible to set the image format (I require webp) using the `getEntries` params? I cannot find any examples in the documentation.

`  const entries = await client.getEntries({ 'reviews', 'fields.name' });
`

Thanks

**Comment by marcolink** [comment]
Hi @SKempin,
the Content Delivery API will return you a media object which can be used to display images in all formats. 
[Here](https://www.contentful.com/blog/always-look-your-best-webp-source-sets-and-the-contentful-images-api/) is an example of how to use WebP with contentful!

**Comment by SKempin** [comment]
@marcolink Thanks but I can't see how I can utilise that with `client.getEntries`, can you provide an example snippet?

**Comment by ITSjwags** [comment]
> @marcolink Thanks but I can't see how I can utilise that with `client.getEntries`, can you provide an example snippet? The examples in those docs are about directly referencing an image URL.
> 
> For clarity I am using https://www.npmjs.com/package/contentful with NextJS

I'm also trying to figure this out one. Has anyone come to a solution yet that isn't requiring the use of the Images API as an extra step?

**Comment by marcolink** [comment]
I made a little sandbox to showcase how to display an image asset as webp image linked from an entry:|
https://codesandbox.io/s/contentful-cda-image-ym868b?file=/src/App.tsx


The used content type as a field called `image` which is of type `Asset`. If loaded with link resolution (default behaviour). the response payload will contain the full asset data. We can change the image using different get parameters (see docs) 


I hope that helps.

Here are the docs for retrieving and manipulating images with contentful
- https://www.contentful.com/developers/docs/concepts/images/
- https://www.contentful.com/developers/docs/references/images-api/#/reference/resizing-&-cropping/change-the-resizing-behavior
