### ISSUE TITLE
Cannot find ./dist/es6-modules/contentful.js

### ISSUE THREAD

**Issue by hans-lizihan** [contentful/contentful.js#158]
* **Node Version**: 8.0.0
* **Npm Version**: 5.0.0
* **Platform**: MacOS Sierra
* **Package Version**: 4.4.0

in the dist directory

```
contentful.js
contentful.js.map
contentful.min.js
contentful.node.js
```
there are no `es6-modules` directly while in package.json

```
  "jsnext:main": "./dist/es6-modules/contentful.js",
  "license": "MIT",
  "main": "./dist/contentful.node.js",
```

jsnext:main points to `./dist/es6-modules/contentfuljs`

this breaks eslint rules: `import/no-unresolve` which will overwrite the `jsnext:main` as `main`.

[https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/node/index.js#L43](https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/node/index.js#L43)

**Comment by Khaledgarbaya** [comment]
this will be fixed in https://github.com/contentful/contentful.js/pull/159
