### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by jsebfranck** [contentful/contentful.js#16]
It is impossible to use the Javascript API with a proxy (host, port, username, password). Please not that it has been done partially with the Ruby API.

**Comment by jsebfranck** [comment]
It seems that the problem is related to questor. To reproduce the problem :

1. Install a proxy on your computer. On mac os, I tried SquidMan.
2. Launch it on localhost and a specific port, for example 3128.
3. Configure your terminal to use this proxy : export http_proxy=http://127.0.0.1:3128

Then with the following code, you can see in Squidman access logs that the request uses the proxy :

var request = require('request');
request(contentfulUrl, function(error, response, body) {
  console.log(error, response, body);
});

But with questor, the request don't use the proxy :

var questor = require('questor');
questor(contentfulUrl).then(function(body) {
  console.log(body);
});

**Comment by sdepold** [comment]
Hi @jsebfranck,

questor is using the shipped http/https modules of node. From what I read [here](http://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client) we would need to modify the http(s) module call when a proxy property is passed to questor, right?

@ehd Any chance to add support for something like that any time soon?

**Comment by jsebfranck** [comment]
@sdepold : yes I also read that. But I have another question : why did you implement your own module of http request instead of using classic request module ?

**Comment by ehd** [comment]
@sdepold Depends, I'm definitely open for pull requests, but this looks like it's a bit more work than just passing a few arguments through?

@jsebfranck `request` doesn't work in browsers.

**Comment by ehd** [comment]
Mhm, this is looking reasonable:

- https://github.com/bitinn/node-fetch
- https://github.com/github/fetch

Anyone got experience with the fetch spec? Is it worth following? It's returning promises and looks pretty close to what questor is doing. Haven't checked proxy support though.

**Comment by jsebfranck** [comment]
I did a pull request in questor module in order to support http proxies with basic auth : https://github.com/ehd/questor/pull/5. 

As soon as it will be accepted, I will do another PR in contentful.js.

**Comment by walpolea** [comment]
Is there any movement/updates on proxy support? Currently stuck trying to use the contentful-management library behind a proxy. This is the only contentful + proxy related thread I could find.

**Comment by jsebfranck** [comment]
We are currently using this fork (https://github.com/jsebfranck/contentful.js/commits/master) which uses questor fork (https://github.com/jsebfranck/questor/commits/master). I didn't take the time to update it with @ehd needs but it is working in production.

**Comment by walpolea** [comment]
Any clue if there is a fork for contentful-management.js with the same fix?

**Comment by jsebfranck** [comment]
I don't think so. You can still create your own fork and have a look at what I changed in my contentful.js fork : https://github.com/jsebfranck/contentful.js/commits/master

**Comment by walpolea** [comment]
Thanks! Done!

**Comment by trodrigues** [comment]
This is now possible on 2.1.0 with https://www.npmjs.com/package/https-proxy-agent
