### ISSUE TITLE
Does Contenful support custom UI like mdxjs

### ISSUE THREAD

**Issue by tienlx97** [contentful/contentful.js#1607]
Does Contenful support custom UI like mdxjs? 

Example: when I add a paragraph:

`<CustomComponent>Lorem Ipsum</CustomComponent>` is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 

In UI when  **Lorem Ipsum** text covered by `<CustomComponent/>`, it will bigger and flickering at UI. Does contenful support this.  I mean the json response ?

**Comment by marcolink** [comment]
Hi @tienlx97,
is this about RichText content? I'm not sure I fully understand the question, maybe you can provide an example?

**Comment by marcolink** [comment]
Closing this for now due to inactivity
