### ISSUE TITLE
GUI for creating Queries against my own Content Space and data

### ISSUE THREAD

**Issue by githubjosh** [contentful/contentful.js#161]
* **Node Version**:
* **Npm Version**:
* **Platform**:
* **Package Version**:

Would be nice if in my Contenful Space I could query my own data and see the code that was generated to run it. Then I could copy-and-paste it into my own app. Have a heck of a time Resoling some links and this would make it easy

**Comment by Khaledgarbaya** [comment]
Hi @githubjosh,

I will transfer your feedback to our product owners, meanwhile I invite you to check the snippets we have in our documentation https://www.contentful.com/developers/docs/references/content-management-api/#/reference/search-parameters
on the sidebar, you can find snippets for all our SDK

Best,
Khaled
