### ISSUE TITLE
Update to include new ResourceLink FieldType and allowedResources Field

### ISSUE THREAD

**Issue by nihalna** [contentful/contentful.js#1622]
Contentful has recently released a new FieldType called "ResourceLink" and its related Field properties in their latest release. However, these new elements are currently not supported in the contentful js library.

To support these new elements, the Field interface should be updated to include the "allowedResources" property and the FieldType should be updated to include the "ResourceLink" type.

**Comment by alicandko** [comment]
Hi @nihalna, I think you want to resolve the data the `ResourceLink` refers to. This feature is currently under development. We will announce it on our [changelog](https://www.contentful.com/developers/changelog/) when the feature is ready.
