### ISSUE TITLE
v4.4.3 not working with HttpProxyAgent. 

### ISSUE THREAD

**Issue by NickLiffen** [contentful/contentful.js#163]
* **Node Version: v7.4.0**:
* **Npm Version: v4.0.5**:
* **Platform: Darwin LillyMac-NickLiffen 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64**:
* **Package Version: v4.4.3**:

When using the latest version of the Contentful npm module (v4.4.3) our proxy settings have stopped working. We are still having to use v3.8.0 which is the last version that we have got working with our proxy. 

These are the settings we have configured to work with our proxy: 

```
// Connection to Contentful 
const configs = {
	space: process.env.CONTENTFUL_SPACE,
	accessToken: process.env.CONTENTFUL_KEY,
	host: 'cdn.contentful.com',
};
```

```
// Proxy configuration (Contentful)
if (process.env.HTTP_PROXY) {
  configs.agent = new HttpProxyAgent(process.env.HTTP_PROXY);
}

```

This code snippet was working fine but when upgrading to the latest version of this npm module we can't seem to connect to Contentful when behind our proxy. Has anything changed recently with proxy support? 👍 Have you got any other support for proxies?

**Comment by Khaledgarbaya** [comment]
Hi @NickLiffen,
That was changed instead of `agent` you need to pass `httpAgent` or `httpsAgent` based on your setup for more info check the reference [docs](https://contentful.github.io/contentful.js/contentful/4.4.3/contentful.html#.createClient)

Hope that helps
Best,
Khaled

**Comment by NickLiffen** [comment]
@Khaledgarbaya thanks for your quick reply 👍 didn't see the documentation update 😢 all working fine!
