### ISSUE TITLE
Beta-v10: syntax error in fast-copy when compiled via Angular 15

### ISSUE THREAD

**Issue by matmar10** [contentful/contentful.js#1659]
## Expected Behavior

Typescript built by Angular when compiled without errors should run in browser without syntax error.

## Actual Behavior

![Screen Shot 2023-01-31 at 1 41 42 AM](https://user-images.githubusercontent.com/19975/215566409-685595cf-0272-4da3-8915-082be6b163b9.png)

```
VM270:354 Uncaught SyntaxError: Unexpected token ':'
    at ../node_modules/fast-copy/dist/fast-copy.js (contentful.browser.js:400:1)
    at __nested_webpack_require_265610__ (contentful.browser.js:903:42)
    at eval (index.es-modules.js:11:67)
    at ../node_modules/contentful-sdk-core/dist/index.es-modules.js (contentful.browser.js:390:1)
    at __nested_webpack_require_265610__ (contentful.browser.js:903:42)
    at eval (contentful.ts:7:77)
    at ./contentful.ts (contentful.browser.js:594:1)
    at __nested_webpack_require_265610__ (contentful.browser.js:903:42)
    at eval (index.ts:5:69)
    at ./index.ts (contentful.browser.js:627:1)
```

## Possible Solution

Possible upstream issue with module `fast-copy`

../node_modules/fast-copy/dist/fast-copy.js 

## Steps to Reproduce

1. Initialize a new project with `ng new`
2.Install Contentful.js Beta-v10 via `npm install --save contentful@beta-v10`
3. Import contentful in a component via `import * as Contentful from 'contentful';`
4. Serve the project `ng serve`
5. Open browser
6. Observe console error

## Context

This is blocking  a new project started in Angular using generated types. 

## Environment

-   **Language Version**:  v16.16.0
-   **Package Manager Version**: 18.13.2
-   **Browser Version**: N/A (all)
-   **Operating System**: macOS 12.4
-   **Package Version**: 10.0.0-beta-v10.10
-   **Which API are you using?**: Delivery

**Comment by Vinz93** [comment]
Hey @matmar10 👋
Thank you for reporting this issue.

I just created a PR that fixes the broken fast-copy version

Cheers

**Comment by matmar10** [comment]
Awesome, thanks for the (blazingly fast) fix, @Vinz93 !

**Comment by matmar10** [comment]
@Vinz93  I've tried using the version that includes your PR (both `10.0.0-beta-v10.12` and also `10.0.0-beta-v10.12`) but unfortunately the issue persists. Bumping fast-copy does not seem to have made any change. Was the source for contentful.browser.js re-compiled as part of the release process?

I've created a bare bones angular app to demonstrate that even with v10.11 & v10.12 this still does not work and it cannot be included into a browser-based project:

https://github.com/matmar10/angular-contentful-beta-10

**Comment by Vinz93** [comment]
Hey @matmar10 I am sorry that this is still occurring, I am taking a look into it, thanks for sharing a repo to reproduce the error

**Comment by alcaponepl** [comment]
Any idea how to solve it?

**Comment by EdSouthgate** [comment]
I'm also facing the same issue, any progress?

**Comment by Tommysyllow** [comment]
Please solve this issue. Any video or blog introducing contentful in angular projects leads to this issue..

**Comment by eaglestorm** [comment]
This issue occurs with angular 14 as well.  I needed to downgrade to contentful version 9.3.5 to get it to work.  I'm assuming all the 10.x versions are broken in Angular.

**Comment by EdSouthgate** [comment]
> This issue occurs with angular 14 as well. I needed to downgrade to contentful version 9.3.5 to get it to work. I'm assuming all the 10.x versions are broken in Angular.

Can confirm that downgrading the package works. Thanks...would be good to be able to use the TS version though.

**Comment by veu** [comment]
Hi, can anyone test if this issue persists with the latest contentful.js version (10.1.4)?

**Comment by EdSouthgate** [comment]
> 

Awesome seems to be working with the latest release!
