### ISSUE TITLE
Does cdn.contentful.com return a 500 error when down?

### ISSUE THREAD

**Issue by githubjosh** [contentful/contentful.js#170]
cdn.contentful.com was just down temporarily but no error was returned. 

Do you have server response errors turned off in this event? 

My app is set to handle exceptions, but no response code was return from cdn.contentful.com

**Comment by axe312ger** [comment]
Sorry for the trouble, we went back online after 7 minutes. Details here: https://www.contentfulstatus.com/

It may have happened that the whole system was down, so it was a connection timeout instead of a 500.

I'll investigate what we can do here on SDK level

**Comment by andrewkumar** [comment]
@githubjosh what can be done on the application side to handle a connection timeout?

**Comment by axe312ger** [comment]
Look here: https://github.com/contentful/contentful-sdk-core/blob/master/test/unit/rate-limit-test.js#L60-L72

**Comment by axe312ger** [comment]
The test/the code is actually broken, just tested it with the newly released axios-mock-adapter today. I'll have a closer look tomorrow, the SDK should throw a connection timeout error or sth so you can handle it properly in your application.

**Comment by axe312ger** [comment]
I wrote a bugfix at https://github.com/contentful/contentful-sdk-core/commit/3f7270f0c9b8ceccb80b886d067a1e75f00f9092 to address this. After some more tests we will release a new `contentful.js` version including this bug fix :)
