### ISSUE TITLE
Issue when fetching specific linked resources

### ISSUE THREAD

**Issue by aperkaz** [contentful/contentful.js#176]
* **Node Version**: 6.11.1
* **Npm Version**: 3.10.10
* **Platform**:   Linux 2bdff240d6b3 4.4.0-81-generic Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* **Package Version**: 4.5.0

I have followed the guide explosed in the [Content Delivery API](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/links-to-a-specific-item), but when constructing the request with the js library:
```
client.getEntries({
  content_type: '<content_type_id>',
  linking_field: 'fields.<field_name>.sys.id',
  target_entry_id: '<target_entry_id>'
})
.then((response) => console.log(response.items))
.catch(console.error)
```
The request outputs the following message:
```
message: 'The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.'
```
However, when constructing the request with the bare HTML, it works propertly:
```
https://cdn.contentful.com/spaces/{space_id}/entries?access_token={access_token}&include={value}&content_type={content_type}&fields.{linking_field}.sys.id={target_entry_id}
```

I may be missing something basic here, but i have been playing for some time with the parameter and so, but i dont get to make it work.
<br/>
Thanks for your time.

**Comment by axe312ger** [comment]
Imagine the `getEntries()` options object as a map of query parameters. There is no big magic involved :)

So everything before the `=` becomes a property name, everything after it the value of that property.

So this should work:
```
client.getEntries({
  content_type: '<content_type_id>',
  'fields.linking_field.sys.id': '<target_entry_id>'
})
.then((response) => console.log(response.items))
.catch(console.error)
```

Click `Query entries` button and select Javascript examples in the upper right corner. These will give you some examples how to use it properly :)

--> https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/equality-operator

Let me know if that worked,
Benedikt

**Comment by aperkaz** [comment]
Is working now, thanks 🙂
