### ISSUE TITLE
IE 11 Unable to load site when using package

### ISSUE THREAD

**Issue by hessnd** [contentful/contentful.js#181]
* **Node Version**: 8.1.2
* **Npm Version**: 5.3.0
* **Platform**: Darwin Nick-Hess 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_6
* **Package Version**: 4.6.0

When using the Contentful package with my VueJS app I encounter an error on versions of the package newer than v3.5.0 with IE 11:

`Object doesn't support property or method 'assign'`

On v3.5.0 I do not encounter this error but on newer versions it occurs and none of my content on Contentful is loaded or displayed on the site.

**Comment by axe312ger** [comment]
Hey hessnd:

It may be the case we forgot the Object.assign polyfill for IE. A quick fix for you would be applying the poly/ponyfill on your own (https://github.com/sindresorhus/object-assign) so it should work straight. (Assign it as polyfill via  `Object.assign = require('object-assign')`)

But in case that's true, I wonder how our tests can complete. Additionally, I can tell you, that the soon published v5 of the SDK will support IE11 for sure again :)

I keep u posted.

Benedikt

**Comment by hessnd** [comment]
@axe312ger Awesome, thank you!
