### ISSUE TITLE
Typescript issue with embedded-entry-block and EntryFields.RichText

### ISSUE THREAD

**Issue by tsmithRo** [contentful/contentful.js#1820]
## Expected Behavior

I have some data that is a mock for a component thats using rich text. The mock has a shape like (I took this almost directly from an api response so the shape is correct to what the api is returning):

```ts
import type { Entry, EntryFields } from "contentful";

const mockItem: Entry<{
  someRichTextField: EntryFields.RichText;
}> = {
  fields: {
    someRichTextField: {
      nodeType: "document",
      data: {},
      content: [
        {
          nodeType: "embedded-entry-block",
          data: {
            target: {
              metadata: { tags: [] },
              sys: {
                space: {
                  // redacted
                },
                type: "Entry", // ERROR HERE
                id: "3qBNt0ibTGZXjTkXBLMEeE",
                contentType: {
                  sys: {
                    type: "Link",
                    linkType: "ContentType",
                    id: "button",
                  },
                },
                revision: 1,
                createdAt: "2022-12-22T09:26:32.531Z",
                updatedAt: "2023-03-20T21:56:27.991Z",
                environment: {
                  sys: {
                    id: "tsmith-local",
                    type: "Link",
                    linkType: "Environment",
                  },
                },
                locale: "en-US",
              },
              fields: {
                internalName: "Example",
                text: "Example",
                link: "https://ro.co",
                size: "large",
                variant: "primary",
              },
            },
          },
          content: [],
        },
      ],
    },
  },
};
```

This should not error.

## Actual Behavior

Theres an error that:

> Type '"Entry"' is not assignable to type '"Link"'.ts(2322)
> index.d.ts(273, 9): The expected type comes from property 'type' which is declared here on type '{ id: string; type: "Link"; linkType: "Entry" | "Asset"; }'

Looks like it comes from the EntryFields.RichText type for embedded-entry-block types of content.

## Steps to Reproduce

See above data, just copying the above into a npm package with typescript and contentful 9.3.5 should repro

## Context

For now we're just ignoring it but I think theres just an issue with this type.

## Environment

contentful 9.3.5 js package
preview api for the data
typescript ^4.9.5

**Comment by marcolink** [comment]
Hi @tsmithRo 👋 
We expected this to be solved with the latest [major](https://github.com/contentful/contentful.js/compare/v9.3.5...v10.0.0)  release (which was a complete re-write).
Please feel free to re-open again if the error still occurs.
