### ISSUE TITLE
Search queries based on links

### ISSUE THREAD

**Issue by jdwillemse** [contentful/contentful.js#183]
I have 3 types of entries _user_, _place_, and _review_. Users can link to one another (many to many). Reviews are linked to a user and a place. A review can be linked to only one place. Places can be linked to many reviews

I need to create a list of places that were reviewed by users I'm linked to. How can I do this efficiently?

**Comment by axe312ger** [comment]
Hey JD,

since this is not related to the SDK itself, can you please file a support ticket at https://www.contentful.com/support/? Our support team will help you out :)

Thanks,
Benedikt

**Comment by jdwillemse** [comment]
I am using the SDK for this, but ok. I sent a support question. Thanks

**Comment by Khaledgarbaya** [comment]
Hi @jdwillemse,
you can get all entries with a `fields.user.sys.id=myUserID`
here is a snippet to do so 
```js
client.getEntries({content_type:'Review', 'fields.user.sys.id': MyUserId})
  .then(response => {
    console.log(response.items)
})
```
I hope this is what you wanted to achieve, otherwise feel free to ask further question.
Sorry for the confusion.

Best,
Khaled

**Comment by jdwillemse** [comment]
This might be bitchy, but @Khaledgarbaya your answers have yet to useful.

With support I figured out this solution that involves 3 different calls:

```
client.getEntries({
  content_type: 'person',
  // get users who have me in their followers list
  'fields.followers.sys.id': userId,
  // only return users that have made suggestions
  'fields.reviews[exists]': true,
});

client.getEntries({
  content_type: 'review',
  // get all reviews that have links to persons found above
  'fields.person.sys.id[in]': stringifyIds(followedPersons),
  // they have to be created after this date
  'sys.createdAt[gt]': isoFormat,
});

client.getEntries({
  content_type: 'place',
  // get all places linked to reviews above
  'fields.reviews.sys.id[in]': stringifyIds(reviews),
});
```

**Comment by Khaledgarbaya** [comment]
I'm glad you found a useful answer for your question :).
I will close the issue since you problem is solved and feel free to open another one if you have other question.

Best,
Khaled
