### ISSUE TITLE
nuxt.js [warning] Connection error occured. Waiting for 1986 ms before retrying...

### ISSUE THREAD

**Issue by milescui** [contentful/contentful.js#184]
* **Node Version**: 8.4.0
* **Npm Version**: 5.3.0
* **Platform**: Darwin MacBook-Pro-3.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
* **Package Version**: contentful@4.6.1

Hello,

I use nuxt.js and contentful. If invoke contentful client in asyncData function, I get the following error：

[warning] Connection error occured. Waiting for 1986 ms before retrying...
[warning] Connection error occured. Waiting for 2685 ms before retrying...
[warning] Connection error occured. Waiting for 3450 ms before retrying...
[warning] Connection error occured. Waiting for 4576 ms before retrying...

If invoke  contentful client in mounted function, It's work.

I tried on the terminal using curl call contentful RESTful api. It's work.

**Comment by Khaledgarbaya** [comment]
Hi @milescui,
Can you provide a minimal code snippet that showcases the issue?
Also, Did you make sure that the client is initialized before making the call?

**Comment by milescui** [comment]
Hi @Khaledgarbaya 

`
import {createClient} from 'contentful'
const client = createClient({
   space: 'nk5aak8gy6yn',
   accessToken: '5721dfe1f3b445295405d3a992f5a8b58bb9c4b50e8eb5e638471d6bd64fd9b8'
})


async asyncData({params}) {
            console.log(client)
            const a = await client.getEntries()
            console.log(a)
        },
`


I make sure the client is initialized.

**Comment by Khaledgarbaya** [comment]
Hi @milescui, this is really weird can you try to pull content from another space using a fresh access token?

**Comment by Khaledgarbaya** [comment]
one more thing, can you capture the request in the Dev tool and see what do you receive there

**Comment by milescui** [comment]
Hi @Khaledgarbaya 

In the browser I can access restful api success. 

https://cdn.contentful.com/spaces/nk5aak8gy6yn/entries?access_token=<my_token>

I use the vuejs + nuxt.js.

`
// The function to run on nuxt.js nodejs server. It's failed
async asyncData({params}) {
            console.log(client)
            const a = await client.getEntries()
            console.log(a)
        },

// The function to run on browser. It's successed
async mounted() {
            console.log(client)
            const a = await client.getEntries()
            console.log(a)
        },
`

**Comment by milescui** [comment]
Hi @Khaledgarbaya 

I created a test file run on nodejs.
`
const contentful = require('contentful')

const client = contentful.createClient({
    space: 'nk5aak8gy6yn',
    accessToken: '<my_token>'
})

async function run() {
    console.log(client)
    const a = await client.getEntries()
    console.log(a)
}

run()
`

$ node 1.js

Result:

{ getSpace: [Function: getSpace],
  getContentType: [Function: getContentType],
  getContentTypes: [Function: getContentTypes],
  getEntry: [Function: getEntry],
  getEntries: [Function: getEntries],
  getAsset: [Function: getAsset],
  getAssets: [Function: getAssets],
  parseEntries: [Function: parseEntries],
  sync: [Function: sync] }
[warning] Connection error occured. Waiting for 1981 ms before retrying...
[warning] Connection error occured. Waiting for 2640 ms before retrying...
[warning] Connection error occured. Waiting for 3342 ms before retrying...
[warning] Connection error occured. Waiting for 4655 ms before retrying...

**Comment by Khaledgarbaya** [comment]
Hi @milescui do you connect through a proxy or a normal network?

**Comment by milescui** [comment]
Hi @Khaledgarbaya 

Yes. I connect vpn. Should my VPN problem.

I run test file on my production server. It's worked.

Thank you
