### ISSUE TITLE
getEntries returns promise that never resolves or rejects it seems

### ISSUE THREAD

**Issue by garethmcc** [contentful/contentful.js#185]
* **Node Version**: v6.11.2
* **Npm Version**:3.10.10
* **Platform**:Linux xenial64 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* **Package Version**: contentful@4.6.1

A call to client.getEntries and passing content_type and a field value never seems to return a result. In the code below an error is not logged and the text Entered then is never logged.

```
'use strict'

const contentful = require('contentful')

module.exports = class Cms {
  constructor () {
    this.client = contentful.createClient({
      space: process.env.CONTENTFUL_SPACE_ID,
      accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
    })
  }

  getContent (contentType, slug) {
    console.log(contentType)
    console.log(slug)
    let entriesReturn = []
    console.log('Getting entries')
    
    this.client.getEntries({
      'content_type': contentType
      'fields.slug': slug
    }).then(returnedEntries => {
      console.log("Entered then")
      console.log(JSON.stringify(returnedEntries))
      returnedEntries.items.forEach(entry => {
        entriesReturn.push(entry)
      })
      return entriesReturn
    }).catch(error => {
      console.log(error)
    })
  }
}
```

**Comment by Khaledgarbaya** [comment]
Hi @garethmcc,
Can you also add the snippet that shows how are you executing this code?

Best,
Khaled

**Comment by garethmcc** [comment]
You know those problems where you have looked at it all ways and sideways and up ways and are sure that the problem does not exist in your own code, and then the next day the one single way that you didn't happen to look at the problem is what helps you find the solution? Well this is one of those. My apologies but all sorted now. I was just not handling the promises correctly.

**Comment by Khaledgarbaya** [comment]
Happens to me every day no worries
