### ISSUE TITLE
Resolving links fails when using `getEntries` with locale `*`

### ISSUE THREAD

**Issue by sgronblo** [contentful/contentful.js#186]
* **Node Version**: v7.10.1
* **Npm Version**: 4.2.0 (actually using yarn 0.27.5)
* **Platform**: MacOS 10.12.6
* **Package Version**: contentful@4.6.1

I've been trying to upgrade our old version of the contenful npm package but ran into a problem where it seems that links are not generated correctly which breaks some functionality that seems to be working with out older version of the npm package (3.8.0). We are doing a quite simple query as follows: `return client.getEntries({ content_type: 'pageContent', 'fields.code': pageContent, locale: '*', 'include': 4 })`.

However when we try to access a property like this: `return response.items[0].fields.mainContent['en-US']` we get the following: `{ sys: { type: 'Link', linkType: 'Entry', id: '1JY18hZGfO6SaEI6CCy0i0' } }` which seems to indicate that the link has not been correctly resolved.

**Comment by sgronblo** [comment]
This is very bizarre. I checked out our older branch again. Checked that everything worked again with the old version. Then after checking my other branch where I have the new contentful version, the test is passing.

One thing I noticed earlier when it was breaking was that the item in our response had both `sys.locale: en-US` and locale-specific keys for each field at the same time. Could this be some sort of API bug?

**Comment by sgronblo** [comment]
This sounds similar to #178

**Comment by sgronblo** [comment]
I scrolled back up through the output of my tests cases to verify my findings:

In the working case I get this as the first items `sys`:

```
{ space: { sys: [Object] },
     type: 'Entry',
     id: 'ID_RETRACTED',
     contentType: { sys: [Object] },
     revision: 22,
     createdAt: '2017-01-26T18:10:43.441Z',
     updatedAt: '2017-08-01T12:29:38.453Z' }
```

And in the case where it doesn't work:

```
{ space: { sys: [Object] },
     type: 'Entry',
     id: '7LSWLmQS2ssCUwyG0gACg0',
     contentType: { sys: [Object] },
     revision: 22,
     createdAt: '2017-01-26T18:10:43.441Z',
     updatedAt: '2017-08-01T12:29:38.453Z',
     locale: 'en-US' }
```

Not the presence of `locale: 'en-US'` in the non-working case.

The code comments here: https://github.com/contentful/contentful.js/blob/v4.6.1/lib/mixins/link-getters.js#L23 mention that:

> If a field does not have a locale defined in sys, the content of that field
> is an object where the keys are each available locale, and we need to iterate
>  over each of those

So it seems either the implementer of the contentful package has mistaken assumptions about the API or the API is broken.

**Comment by sgronblo** [comment]
I forgot to mention that this is using `preview.contentful.com` as the client API host.

**Comment by axe312ger** [comment]
Thank you for your report. We are investigating :)

**Comment by sgronblo** [comment]
Is there any progress on this? We would love to upgrade our `contentful` but would like to confirm that the problem we are experiencing is not related to the new version of the package.

**Comment by axe312ger** [comment]
Hello there. I just want to give a short update that this bug is on API side and not related to the Javascript SDK.

Version 3 has a workaround in place, which did not catch all edge-cases which is why it got removed in version 4 of the SDK.

Unfortunately, this will be a breaking change for the API and that's why this link resolving feature breaking property can not simply be removed from the response on the preview API.

We will keep you updated when and how we are going to resolve this, I try to keep this issue here updated when the status changes in any way.

**Comment by sgronblo** [comment]
So, to summarize:

1. The bug exists in both versions 3.x and 4.x of the `contentful` npm package. However it's impact is more limited in the case of 3.x?
2. Why would fixing this be a breaking change for the API? Isn't the API simply returning an incorrect response which should be fixed so that the `locale` value is not included in `sys` when a locale: * query is performed?

**Comment by axe312ger** [comment]
1. Yes, both versions are affected, version 3 fails less due it's incomplete workaround
2. Since the API is also used by non-SDK consumers, we might break software of customers by changing this response structure. We want to avoid this at any cost.
3. Yes, it does only appear on the preview api

Hope that helps, I keep u posted.

**Comment by sgronblo** [comment]
I got a response to my API support request which recommends me to perform content resolving manually. I'd rather not spend valuable time on implementing that and have to worry about whether my custom implementation matches the functionality you get when using the CD API. The response to my support request also mentioned a quite simple workaround:

> get your entries as usual
> when on preview, remove the faulty sys.locale property from all items in the response
> use https://github.com/contentful/contentful-resolve-response to resolve the links

If it's this simple, why wasn't this implemented correctly in this package for example?

**Comment by axe312ger** [comment]
Because we won't add code which fixes bugs based on assumptions. Since there is no flag for preview in the SDK, we could only relate to the URL. Since customers might use proxies to redirect requests, this is not a reliable solution.

We are still investigating what we can do asap.

**Comment by abdul-qadir** [comment]
contentful: "^3.7.0",
node - v8.4.0,
npm - 5.3.0,
locale - * is not working. Is there any workaround to get entries for specific content type for all locales?

**Comment by axe312ger** [comment]
![Good news everyone](https://freethoughtblogs.com/affinity/files/2017/06/good-news-everyone.jpg)

Hello everyone,

I have good news:

Our API team rolled out a bugfix for the preview API. `locale=*` will now no more output the `sys.locale` property. This means, that the SDK is now working as expected. You do **not** need to update anything. It will just work.

All the best,
Benedikt
