### ISSUE TITLE
markdown content is rendered as string

### ISSUE THREAD

**Issue by jorcons** [contentful/contentful.js#187]
* **Node Version**: 6.10.0
* **Npm Version**: 5.4.0
* **Platform**: Mac OSX
* **Package Version**: contentful@4.6.1

Content of fields with markdown not render correctly. Are rendered as string.

![2017-09-18 12 39 32](https://user-images.githubusercontent.com/8173987/30538485-87a3e762-9c6e-11e7-8258-5cbf9f435ef1.png)
![2017-09-18 12 39 57](https://user-images.githubusercontent.com/8173987/30538486-87d4f1cc-9c6e-11e7-9340-b72663b913a1.png)

**Comment by Khaledgarbaya** [comment]
Hi @jorcons,
The SDK does not do any rendering you will need to parse the markdown and render it yourself.

Best,
Khaled

**Comment by jorcons** [comment]
Esta dirección en breve dejará de funcionar.
Rogamos tome nota del nuevo email: jconstanti@visibletic.com

Visible IT Comunicación
visibletic.com

**Comment by jorcons** [comment]
Ok Khaled, thanks for the response. Maybe marked is a good tool to do this?

**Comment by Khaledgarbaya** [comment]
@jorcons,
Yes that's we use in our example apps

**Comment by jorcons** [comment]
ok thanks!
