### ISSUE TITLE
unsafe-eval needs to be set in CSP since update to v10

### ISSUE THREAD

**Issue by edlerd** [contentful/contentful.js#1881]
## Expected Behavior

Data should be loaded

## Actual Behavior

An error happens, because execution of code is prevented

## Possible Solution

Change how code is executed and loaded

## Steps to Reproduce

I load data in a next.js app, until version 9.0 it worked fine with a CSP like this

   add_header Content-Security-Policy "default-src 'none'; connect-src 'self' https://cdn.contentful.com/spaces/my-id/environments/master/entries; font-src 'self'; script-src 'self' style-src 'self'; 'unsafe-inline'; prefetch-src 'self';" always;

Since update to version 10.0 I get a csp error and only after allowing unsafe eval it works:

   add_header Content-Security-Policy "default-src 'none'; connect-src 'self' https://cdn.contentful.com/spaces/my-id/environments/master/entries; font-src 'self'; script-src 'self' **'unsafe-eval'**; style-src 'self' 'unsafe-inline'; prefetch-src 'self';" always;

I load the data in the pages of the next.js app. It works if stuff is server-side rendered. But when navigating to other pages, that fetch data directly from contentful the data loading fails. A reload (that will load that page on server side) works, but obviously navigation can't be broken like that.

I'd like to avoid having to set unsafe-eval and it shouldn't be necessary as the old v9 shows.

**Comment by veu** [comment]
Hi, do you still see the issue with the current version (10.1.4)?

**Comment by edlerd** [comment]
I can confirm it is fixed with the recent update. Thank you :)
