### ISSUE TITLE
`ContentfulClientApi` type should not require a `Modifiers` type

### ISSUE THREAD

**Issue by prichey** [contentful/contentful.js#1885]
The type declaration for `ContentfulClientApi` in v10 (10.1.0) looks like this:

```ts
export interface ContentfulClientApi<Modifiers extends ChainModifiers> {
  // ...
}
```

Not providing a default value to the generic `Modifiers` type makes TS always expect it to be passed. I don't think this should be the case (sometimes, modifiers are not desired or required). Above, `undefined` is declared as a valid member of `ChainModifiers`. I believe the code above should be replaced with the following.

```ts
export interface ContentfulClientApi<Modifiers extends ChainModifiers = undefined> {
  // ...
}
```

Writing `ContentfulClientApi<undefined>` everywhere is much less ergonomic than `ContentfulClientApi`. I believe the modification above functions as expected in all situations, though admittedly I've just begun to look at the v10 code. Let me know if my understanding is mistaken.

Thanks!

**Comment by veu** [comment]
Hi, I understand the interest in having short type but not adding a default here is intentional as it helps avoiding errors when the type parameter is omitted by accident.
I suggest creating type aliases in your project for types you use a lot.

**Comment by prichey** [comment]
Alright, thanks for the response
