### ISSUE TITLE
ECONNABORTED Error: timeout of 30000ms exceeded

### ISSUE THREAD

**Issue by krazylearner** [contentful/contentful.js#189]
* **v6.11.1**:
* **3.10.10**:
* **Linux chatbot 3.13.0-125-generic #174-Ubuntu SMP Mon Jul 10 18:51:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux**:
* **contentful@4.6.1**:

HI i am getting connection timeout errors .everything was working fine in my production app and suddenly getting these errors

`
"stack":"Error: timeout of 30000ms exceeded\n    at createError (/home/ankur/the-daily-horoscope/node_modules/contentful/dist/contentful.node.js:952:15)\n    at Timeout.handleRequestTimeout [as _onTimeout] (/home/ankur/the-daily-horoscope/node_modules/contentful/dist/contentful.node.js:4062:16)\n    at ontimeout (timers.js:386:14)\n    at tryOnTimeout (timers.js:250:5)\n    at Timer.listOnTimeout (timers.js:214:5)","config":{"transformRequest":{},"transformResponse":{},"timeout":30000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/vnd.contentful.delivery.v1+json","X-Contentful-User-Agent":"sdk contentful.js/4.6.1; platform node.js/6.11.1; os Linux/3.13.0-125-generic;","Authorization":"Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","user-agent":"node.js/v6.11.1","Accept-Encoding":"gzip"},"baseURL":"https://cdn.contentful.com:443/spaces/xxxxxxx/","httpAgent":false,"httpsAgent":false,"proxy":false,"retryOnError":true,"method":"get","params":{"content_type":"welcomeIntent","select":"fields.fullfilment,sys","fields.bot[match]":"google","limit":1},"url":"https://cdn.contentful.com:443/spaces/st51kaan1rkp/entries"},"code":"ECONNABORTED","attempts":30,"level":"error","timestamp":"2017-10-04T05:28:50.189Z"}
{"message":"api.ai: Error from intenthandler","stack":"Error: timeout of 30000ms exceeded\n    at createError (/home/ankur/the-daily-horoscope/node_modules/contentful/dist/contentful.node.js:952:15)\n    at Timeout.handleRequestTimeout [as _onTimeout] (/home/ankur/the-daily-horoscope/node_modules/contentful/dist/contentful.node.js:4062:16)\n    at ontimeout (timers.js:386:14)\n    at tryOnTimeout (timers.js:250:5)\n    at Timer.listOnTimeout (timers.js:214:5)","config":{"transformRequest":{},"transformResponse":{},"timeout":30000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/vnd.contentful.delivery.v1+json","X-Contentful-User-Agent":"sdk contentful.js/4.6.1; platform node.js/6.11.1; os Linux/3.13.0-125-generic;","Authorization":"Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXX","user-agent":"node.js/v6.11.1","Accept-Encoding":"gzip"},"baseURL":"https://cdn.contentful.com:443/spaces/xxxxxx/","httpAgent":false,"httpsAgent":false,"proxy":false,"retryOnError":true,"method":"get","params":{"content_type":"welcomeIntent","select":"fields.fullfilment,sys","fields.bot[match]":"google","limit":1},"url":"https://cdn.contentful.com:443/spaces/st51kaan1rkp/entries"},"code":"ECONNABORTED","attempts":30,"__error_callsites":[{},{},{},{},{}],"level":"error","timestamp":"2017-10-04T05:28:50.189Z"}
`
Please help 
Thanks

**Comment by Khaledgarbaya** [comment]
Hi @krazylearner,
This looks like a request that timed out, this can be due to your internet connection.

**Comment by krazylearner** [comment]
HI @Khaledgarbaya ,
i am getting this error on every request to contentful. the application is running on server and it was working fine till yesterday .

**Comment by krazylearner** [comment]
ping cdn.contentful.com
PING prod.a.ssl.global.fastly.net (151.101.112.249) 56(84) bytes of data.
64 bytes from 151.101.112.249: icmp_seq=1 ttl=59 time=5.04 ms
64 bytes from 151.101.112.249: icmp_seq=2 ttl=59 time=4.97 ms
64 bytes from 151.101.112.249: icmp_seq=3 ttl=59 time=5.05 ms
64 bytes from 151.101.112.249: icmp_seq=4 ttl=59 time=4.98 ms
64 bytes from 151.101.112.249: icmp_seq=5 ttl=59 time=4.92 ms

**Comment by Khaledgarbaya** [comment]
Hi @krazylearner,
Are you able to debug the problem on the server?
Did you try to code in an another environment?

**Comment by krazylearner** [comment]
hi @Khaledgarbaya ,
the problem is resolved by itself. cant say what happened . our server admin says that contentful was responding very slowly for the duration of the problem.

Thanks

**Comment by istvanzsigovicsCasumo** [comment]
We are experiencing the same issue from time to time. We investigated it a bit more and find out that these calls are not hitting the contentful architecture. So it's a bit strange. Theoretically the problem should be within our infrastructure but I didn't find any difference between the successful and unsuccessful calls

**Comment by ignatospadov** [comment]
I can also confirm this issue happens intermittently with one of our applications. We have one application that does not use contentful's sdk library and makes direct GET requests. We never run into issues related to  ECONNABORTED or socket hang up. The other application we get random alerts with ECONNABORTED and socket hang up and it uses the library SDK. 

There is very little info on why this happens in the logs and on the internet. Both applications are using next.js, deployment is the same. The one with lower traffic is the one that has these connection issues all the time.
