### ISSUE TITLE
Link resolution doesn't occur if select param is provided

### ISSUE THREAD

**Issue by timwis** [contentful/contentful.js#190]
It seems if you include a `select` value in the options of `getEntries()`, link resolution doesn't occur. If you exclude that `select` property it works fine. Any idea why?

```javascript
const client = createClient({ space, accessToken })
client.getEntries({ content_type: 'foo', select: 'fields.name,fields.photo' }).then((response) => ...)
```

**Comment by Khaledgarbaya** [comment]
Hi @timwis,
I just tried the snippet with the SDK and it is working fine. 
You will only get the fields that you selected resolved.

**Comment by timwis** [comment]
Hi @Khaledgarbaya thanks for the quick response. After some troubleshooting on my end I figured out what caused the issue: if you include `sys.id` in your `select`, resolution fails. For example `select: 'sys.id,fields.name,fields.photo'`.

Here's a test to illustrate:

```javascript
test('Gets entries with linked includes and select', (t) => {
  t.plan(5)
  return client.getEntries({
    content_type: 'cat',
    select: 'sys.id,fields.name,fields.image'
  })
  .then((response) => {
    console.log(JSON.stringify(response, null, 2))

    t.ok(response.includes, 'includes')
    t.ok(response.includes.Asset, 'includes for Assets')
    t.ok(Object.keys(response.includes.Asset).length > 0, 'list of includes has asset items')
    t.equal(response.items[0].fields.image.sys.type, 'Asset', 'image is resolved')
    t.ok(response.items[0].fields.image.fields, 'resolved image has fields')
  })
})
```

I'm personally fine with just excluding that from the `select` query -- I was just trying to optimize the query.

Thanks again.
