### ISSUE TITLE
SyntaxError Unexpected token '?' in file create-contentful-api.ts

### ISSUE THREAD

**Issue by wadehammes** [contentful/contentful.js#1901]
## Expected Behavior

No error should occur.

## Actual Behavior

Getting a SyntaxError Unexpected token '?' in file create-contentful-api.ts, which appears to only be happening on older browser versions, and has been happening ever since 10.0.0 was released. It has been causing "Application error: a client-side error has occurred" within my Next.js application the last few weeks for only a small subset of users using outdated browser versions.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/222170/236294288-b790c99e-d460-468b-af77-2a30ca1b1f8b.png">

## Possible Solution

Not sure, from what I gather this is a compiling issue potentially?

## Steps to Reproduce

Have next.js installed with latest Contentful, use a old browser like Chrome 75 or something.

**Comment by wadehammes** [comment]
Anything regarding this?

**Comment by marcolink** [comment]
Hi @wadehammes,

Would you be able to provide more details about the browser where this occurs? [Here](https://github.com/contentful/browserslist-config/blob/main/index.js) you can find the `browserlist` config we use to build our libraries.

**Comment by wadehammes** [comment]
It was happening in various browsers, mostly chrome. I saw one instance of it in Chrome 104. Most were mobile Chrome versions going back to 75.

**Comment by wadehammes** [comment]
I also want to add that reverting back to 9.3.5 resolved the error and I haven't seen it again in Sentry, so definitely isolated to this update.

**Comment by wadehammes** [comment]
@marcolink is this something your team can look into, it's preventing me from updating. I am happy to provide more sentry logs or whatever is needed.

**Comment by dsolanorush** [comment]
I am also seeing this error, along with a couple of other errors from the same file (create-contentful-api.ts), including `Unexpected token ';'. Expected an opening '(' before a method's parameter list.`. I also reverted back to `9.3.5` to resolve the issue

I would certainly like to upgrade if this issue can be identified and resolved. Any progress @marcolink?

**Comment by wadehammes** [comment]
Any movement here @marcolink ?

**Comment by marcolink** [comment]
@wadehammes 
a new version with higher browser compatibility has just been released https://github.com/contentful/contentful.js/releases/tag/v10.3.1

Please let us know if this is still not solving your case!

**Comment by wadehammes** [comment]
@marcolink thanks going to do some testing today and will let you know. Trying to determine what is the lowest version of browsers we've seen over the last 90 days but Im fairly certain this should cover most since Chrome 75 is from 4 years ago.

**Comment by marcolink** [comment]
@wadehammes here you can check the current coverage: 
https://browsersl.ist/#q=%3E0.3%25%2C+Chrome+%3E%3D+75%2C+Edge+%3E%3D+74%2C+Firefox+%3E%3D+73%2C+Safari+%3E%3D+13

**Comment by wadehammes** [comment]
@marcolink unfortunately still seeing this (but for a much smaller subset of users now). Chrome Mobile 77/76 seem to be a culprit. We've had 17 instances of this happening in the two hours since I released v10 back to production. Going to have to revert again, not worth the upgrade for us.
