### ISSUE TITLE
Expo and Contentful

### ISSUE THREAD

**Issue by crivera** [contentful/contentful.js#191]
Hi

i was playing around with contentful and tried to run it in combination with expo.io.

This seemed to work before version 5.0.1 without issues but now when I update and just run the app i get the following error:

<img width="478" alt="screen shot 2017-10-18 at 11 51 47 am" src="https://user-images.githubusercontent.com/356611/31728687-f64f8790-b3fa-11e7-8de6-ccb691bfdf8a.png">

it seems like its trying to require the http module which doesnt exist in react native.

Any help would be great
Chris

**Comment by crivera** [comment]
that worked! thanks!

**Comment by psadanowicz** [comment]
@axe312ger I had same issue but your solution worked. Please add this information to readme. Thanks a lot.
