### ISSUE TITLE
EntriesQueries v10 parameters issue 

### ISSUE THREAD

**Issue by lNikolayl** [contentful/contentful.js#1911]
Hello! I'm not really sure if it's an issue or not. However my expectation and current workflow are not matched with new TS implementation. May be here there is another way to migrate to the v10

## Expected Behavior

Typescript implementation of `EntriesQueries` should accept both "types" of parameters (static and dynamic). 

## Actual Behavior

On the current workflow `getEntries` function accepts static and dynamic query keys. However TS implementation accepts only one. In this case I can't filter entries properly.

## Possible Solution

```typescript
export type EntriesQueries<
  EntrySkeleton extends EntrySkeletonType,
  Modifiers extends ChainModifiers
> =
  & (EntryFieldsQueries<EntrySkeleton['fields']> &
      EntryContentTypeQuery<EntrySkeleton['contentTypeId']>)
  & ((SysQueries<Pick<EntrySys, 'createdAt' | 'updatedAt' | 'revision' | 'id' | 'type'>> &
      MetadataTagsQueries &
      EntrySelectFilter &
      EntryOrderFilter &
      FixedQueryOptions &
      FixedPagedOptions &
      FixedLinkOptions) &
      // eslint-disable-next-line @typescript-eslint/ban-types
      ('WITH_ALL_LOCALES' extends Modifiers ? {} : LocaleOption))
```

## Context

In this case filtering is not working in proper way.

## Environment

Contentful: 10.1.0
Typescript": 5.0.4

**Comment by veu** [comment]
Hi, can you give me an example of a query that is not accepted by the current types?

**Comment by claudiorivera** [comment]
@veu I was going to create a new issue, but I wonder if this might be the same thing I'm seeing in [my reproduction here](https://github.com/claudiorivera/contentful-types)?

My client call is:
```javascript
contentfulClient.getEntry(CONTENTFUL_ENTRY_ID, {
          content_type: CONTENTFUL_ENTRY_TYPE, // ie. "blog"
        });
```

The TypeScript error I'm getting:

```
Argument of type '{ content_type: string; }' is not assignable to parameter of type 'EntryQueries<undefined>'.
  Object literal may only specify known properties, and 'content_type' does not exist in type 'EntryQueries<undefined>'.ts(2345)
```

**Comment by veu** [comment]
@claudiorivera The `content_type` parameter is used to filter by content type when calling `getEntries`. `getEntry` doesn’t have the parameter because you’re fetch a single entry. There’s no need to filter by content type as there is only one entry with one content type.

**Comment by claudiorivera** [comment]
> @claudiorivera The `content_type` parameter is used to filter by content type when calling `getEntries`. `getEntry` doesn’t have the parameter because you’re fetching a single entry. There’s no need to filter by content type as there is only one entry with one content type.

I understand the `content_type` is extraneous, but I'm using [Zod for inference and validation](https://www.jussinevavuori.com/blog/using-contentful-with-nextjs-part-1-2i0a) and was having validation issues without it.

I do wonder, if the extraneous query is still being respected (ie. if you include the query `content_type: 'nonExistentContentType'`, you will get no results even though you've specified an ID), then it seems like it should be allowed by TypeScript.

In any case, I appreciate the response! I'll see if there's something in my Zod implementation that could be improved.
