### ISSUE TITLE
Cannot use map or length on Array<EntryLink> types

### ISSUE THREAD

**Issue by holdenmad** [contentful/contentful.js#1913]
## Expected Behavior

I expect that I am able to get the 'length' of 'props.boxGrid.box', which has worked in Contentful v9. A `map` function also does not work and leads to the same error. 
If I hover over the property, the type is indeed an Array. 
I have generated the content types with v10. 

In my call for `getEntries` I've tried `withoutUnresolvableLinks` and `withoutLinkResolution` and with neither. 

## Actual Behavior

I am getting an error that says that I cannot get the length of the 'Array' of 'box', which is stopping the building process.
`Property 'length' does not exist on type 'Array<EntryLink<TypeBoxSkeleton>>'.ts(2339)`
```
 const boxRefs = useRef<Array<MutableRefObject<HTMLDivElement | null>>>(
    Array.from(
      { length: props.boxGrid?.box.length || 0 },
      () => React.createRef<HTMLDivElement>()
    )
  )
```

My props look like this: 
```
export default function BoxGrid(props: {
  boxGrid: TypeBoxGridFields | undefined
}) {
```

I'm really not sure why it's not recognizing that the type is an array, since everything else seems to work as expected from the types. 

## Possible Solution

If this is an issue with v10, then it seems that something about the `Array<EntryLink<TypeTYPEHERE>>` is not working as expected. 

## Steps to Reproduce

1. Generate types with the [cf-content-types-generator-app](https://github.com/marcolink/cf-content-types-generator-app)
2. Have one content model be an array (multiple links) 
3. Use `map`, `length`, or another array function on the data that is an array of links (for example to create a conditional or to render the array)

## Context

In multiple parts of my code I want to render data from an array coming from Contentful, for example customer testimonials or footer links. I want to have the correct types to avoid errors (and also avoid ignoring TypeScript in those files). 

## Environment

-   **Language Version**: v16.13.0
-   **Package Manager Version**: 8.1.0
-   **Operating System**: Darwin Kernel Version 21.6.0
-   **Package Version**: ^10.1.8
-   **Which API are you using?**: Delivery

**Comment by veu** [comment]
Hi, to answer your question I need some more information about your example.
* contentful.js contains two types called `EntryLink`. Which one are you using?
* Which `Array` type are you using?

**Comment by veu** [comment]
Closed due to inactivity
