### ISSUE TITLE
Code samples in API docs do not load on right sidebar

### ISSUE THREAD

**Issue by ragnarbull** [contentful/contentful.js#1918]
## Expected Behavior

- Code samples in all API docs do not open eg. clicking on [Get all entries of a Space(https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/entries/entries-collection)" in the Content Delivery API 

## Actual Behavior

- Code sample should open on right sidebar with language options.
- Full warning & TypeError in the console: ![contentful-api-docs-code-sample-error](https://github.com/contentful/contentful.js/assets/83689282/87cbc40b-559b-445d-a16a-00544fa38f48)

## Possible Solution

- Upgrade to Version 9 of Highlight.js (console warning: _Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877_ )
- Change build system to not interpret warnings as errors (if the sql warning is causing this)
- Some fix for TypeError

## Steps to Reproduce

1. Visit API docs and click on any code sample link

## Environment

-   Browser Version: Chrome Version 113.0.5672.127, Firefox Version 113.0.1, Microsoft Edge Version 113.0.1774.50

**Comment by colomolo** [comment]
Hello @ragnarbull,
Thanks for reporting. We will look into that.

**Comment by colomolo** [comment]
Should now be fixed. @ragnarbull can you please check and confirm?

**Comment by ragnarbull** [comment]
> Should now be fixed. @ragnarbull can you please check and confirm?

Fixed. Tested on Chrome, Edge, Firefox. Thanks, good work.
