### ISSUE TITLE
Example in README is incorrect

### ISSUE THREAD

**Issue by robertsvensson** [contentful/contentful.js#192]
The example used to point to a specific version for browsers, like 4.1.1, does not work.
<script src="https://unpkg.com/contentful@4.1.1/dist/contentful.browser.min.js"></script>

Error:
Cannot find module "/dist/contentful.browser.min.js" in package contentful@4.1.1

**Comment by axe312ger** [comment]
Thanks, going to fix it today with the README suggestion from #191
