### ISSUE TITLE
How to fetch content via URN?

### ISSUE THREAD

**Issue by vimkin** [contentful/contentful.js#1920]
Spoiler: this is rather a question or indirect feature request.

## Actual Behavior

My code fetches an article to display on a page:
```javascript
const articles = await client.getEntry("${entry_id}", {
  include: 2,
});
```

The article shows is supposed to display recommendations below the main body. Recommendations may include resource links from another spaces such as:
```json
{
  "recommendations": [
    {
      "sys": {
        "type": "ResourceLink",
        "linkType": "Contentful:Entry",
        "urn": "crn:contentful:::content:spaces/{space_id}/entries/{entry_id}"
      }
    }
  ]
}
```

## Question

How can I fetch the related recommendations from another space via the `urn`? Does this client or Contentful Delivery API support fetching data via `urn`?

**Comment by veu** [comment]
Hi, when you have the URN you just create a new client for the linked space and fetch the entry from there. We also released a [version](https://www.npmjs.com/package/contentful/v/9.4.0-beta-resource-links.2) that integrates this into the library but it is experimental.
Having said that, we’re also working on automating the resolution of resource links more so keep an eye on our new releases.

**Comment by veu** [comment]
@vimkin Resource link resolution is now available. https://www.contentful.com/developers/changelog/#cda-now-supports-retrieval-of-references-from-different-spaces

**Comment by veu** [comment]
Closing because the question has been answered.
