### ISSUE TITLE
GET request to entries not resolving Links

### ISSUE THREAD

**Issue by EmilAvramov** [contentful/contentful.js#1941]
I am doing a GET request (not via client, but with vanilla JS fetch) to the following endpoint, but my Links in items are not resolving. I do have them in the include array. What am I doing wrong?

https://cdn.contentful.com/spaces/XXXXX/environments/XXXXX/entries?access_token=XXXXX&content_type=categoryLandingPage&fields.categoryName[in]=womens&include=5

My Links are within the include depth level.

Edit: The response comes out like this:
 "fields": {
                "pageName": "Women Category Page",
                "componentContainers": [
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "4xk2EfWThXECbGscMhIWdc"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "3iVu81tVzGNgHlXAPsJMXG"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "2iQ4TP02AxnZhQdg4zpsEf"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "5cbklve4NFSFYEI5Mf5qvV"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "5SQ7ddcRyH9lr5rsVTcbCO"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "7u8JhB00TtlZ3TM4flqzro"
                        }
                    },
                    {
                        "sys": {
                            "type": "Link",
                            "linkType": "Entry",
                            "id": "LbnINfAI5pzs2DU7IfA9s"
                        }
                    }
                ],
                "categoryName": "womens"
            }

**Comment by rishabhkum-Dev-1799** [comment]
Hi , the API will give not give you the data in hierarchical  manner , if you want to get it in hierarchical way you need to get a library Contentful.js  and just hit your entries end point and it will provide you the data in hierarchical manner
