### ISSUE TITLE
Can you access the raw response from the CDA?

### ISSUE THREAD

**Issue by mrsteele** [contentful/contentful.js#196]
This is simply a suggestion.

It looks like there is a bit of juggling before the promise resolves with the response from the CDA, however we wanted to know if it was possible to get the response in the resolved promise.

Perhaps something similar to the following:
```javascript
client.getEntry('entryid').then((entry) => {
  // Now we can get into the juicy stuff!
  console.log(entry.res.headers['X-Contentful-RateLimit-Reset'])
})
```

This is simply a suggestion but we would appreciate having insight on the response.

**Comment by Khaledgarbaya** [comment]
Hi @mrsteele,
Unfortunately, that is not possible for now, we might add it at some point to the SDK.
BEst,
Khaled
