### ISSUE TITLE
TypeError: Converting circular structure to JSON     at Object.stringify (native)

### ISSUE THREAD

**Issue by calvinmuller** [contentful/contentful.js#197]
* **Node Version**:v6.9.1
* **Npm Version**:3.10.8
* **Platform**: MacOSX
* **Package Version**: 5.0.2

I'm trying to serve content as a proxy in express,

`async getIndex(req: Request, res: Response, next: NextFunction) {

    const news = await this.cf.getNews();

    res.send(news);

  }`

However it is throwing this TypeError: Converting circular structure to JSON     at Object.stringify (native).

Do you know anyway around this so I can serve the content via res.json(), res.send() etc?

Thanks

**Comment by Khaledgarbaya** [comment]
Hi @calvinmuller,
You can use libraries like `json-stringify-safe` to achieve that.
```
const stringify = require('json-stringify-safe')
const news = await this.cf.getNews();
// as json
res.json(news.toPlainObject())
// as text
res.send(stringify(news.toPlainObject()))
```

**Comment by calvinmuller** [comment]
@Khaledgarbaya thanks however even when using toPlaintObject() is seems as thought it still throws

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at stringify (/Users/xxx/Sites/xxx/dist/server.js:211744:12)

I'll give the stringify library a bash and let you know.

Thanks

**Comment by calvinmuller** [comment]
Okay so after some investigation, this occurs when you have eg. news articles with authors and authors with created entries and with the include level set to 2.

**Comment by Khaledgarbaya** [comment]
Yeah since Contentful allows you to create circular refs. I think your best option now is to use the stringify library.

**Comment by kyriediculous** [comment]
Struggling with the same problem.

I have blogposts and categories in a many to many relationship.

**Comment by Khaledgarbaya** [comment]
Please use `json-stringify-safe` to solve that as I mentioned it before

**Comment by kyriediculous** [comment]
That doesn't solve anything. That's just an easy way out.

**Comment by webdesignberlin** [comment]
Same problem with many to many relationship. Usage of json-stringify-safe doesnt work every time. In addition, the memory usage of the client is strained.

**Comment by huesoamz** [comment]
same problem when in the model have in atleat one field "References, many" because that brings a array and cannot be converted to a json...
    let model = await client.getEntries({
      content_type: 'modeltype',
      include: 4
    })

Any thougths?

**Comment by muhammadabad** [comment]
I'm trying to serve content as a proxy in express,

`async getIndex(req: Request, res: Response, next: NextFunction) {

const news = await this.cf.getNews();

res.send(news); 
}`


DO THIS:- 

res.send(news.data);     //Replace this line
