### ISSUE TITLE
Ranges in getEntries API Call

### ISSUE THREAD

**Issue by lsbyerley** [contentful/contentful.js#198]
* **Node Version**: 6.10.2
* **Npm Version**: 3.10.10
* **Platform**: Linux
* **Package Version**: 4.6.0

More so a question, than an issue. I can't seem to find any documentation on how to use a range search parameter in a getEntries call. More specifically, pulling events that have a startDate after todays date. How would I integrate the greater than range [gt] into this api call?

    contentful_client.getEntries({
        content_type: 'events',
        limit: 10,
        order: 'fields.startDate'
    })

**Comment by axe312ger** [comment]
You can do it by just having the operator in your object property name. The whole object then gets translated into a query string and send to the API. For example:

```js
client.getEntries({
  content_type: '<content_type_id>',
  'sys.updatedAt[gte]': '2013-01-01T00:00:00Z'
})
```

You can find more examples in our documentation, just click the huge grey buttons and you will find more details, including an example snippet for all SDKs:
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/ranges

**Comment by lsbyerley** [comment]
Thank you, I did see the docs and the snippet, although I wasn't sure exactly how to implement it using the contentful node package as opposed to the api url. Thank you for the feedback!
