### ISSUE TITLE
Live preview mode with Next.js 13 app directory

### ISSUE THREAD

**Issue by sebpowell** [contentful/contentful.js#1987]
Hi there, 

I'm not sure if this is the right place to ask this, but not sure where else so trying my luck. 

I'm using Next.js 13 with the app directory, and would like to get live preview mode working. The tutorial recently published [here](https://www.contentful.com/blog/elevate-your-contentful-and-next-js-workflow-with-live-preview/) seems to be based on the old version of Next – for example, this:

```TSX
function MyApp({ Component, pageProps }) {
  return (
<ContentfulLivePreviewProvider 
      	  locale="en-US" 
        enableInspectorMode={pageProps.draftMode}
  enableLiveUpdates={pageProps.draftMode}
      >
      <Component {...pageProps} />
    </ContentfulLivePreviewProvider>
  );
}

export default MyApp;
```

I'm not sure how this would work now with Next.js 13 and the app directory. Has anyone had any success converting the above? Any guidance would be greatly appreciated. Thank you in advance.

**Comment by marcolink** [comment]
Hi @sebpowell, 
This would be an excellent question for the brand [new community discord](https://www.contentful.com/developers/discord/).
