### ISSUE TITLE
Hash mismatch on axios when installing with a lockfile

### ISSUE THREAD

**Issue by SpainTrain** [contentful/contentful.js#201]
* **Node Version**: v8.9.1
* **Npm Version**: 5.5.1
* **Yarn Version**: 1.3.2
* **Platform**: CircleCI v1 (Ubuntu 14.04)
* **Package Version**: 5.0.2 and 5.0.3

Since https://github.com/contentful/contentful.js/pull/195 we get the following lockfile hash mismatch when installing on CircleCI:

```
$yarn install --frozen-lockfile
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
⠁ [3/5] Fetching packages...
error https://github.com/contentful/axios/archive/fix/https-via-http-proxy.tar.gz: Fetch succeeded for undefined. However, extracting "https://github.com/contentful/axios/archive/fix/https-via-http-proxy.tar.gz" resulted in hash "76fe9fcbb0e5907608bf2fa55d01846493474f48", which did not match the requested hash "bb534c3cb2894129e223c56f1bdad574a7c9f1b7".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

yarn install --frozen-lockfile returned exit code 1

Action failed: yarn install --frozen-lockfile
```

When using forked libraries like this, these and related issues can be avoided by publishing the forked version to the npm registry under a scope (e.g., `@contentful/axios`) or other name (e.g., `axios-contentful-fix`).  If you would like, I am happy to create the package and open a PR to use it here, just LMK. Thanks!

**Comment by zcei** [comment]
How is the hash calculated? Shouldn't be the git-ref, right?

Because if it is, then I might be the one who broke it, as I rebased the PR branch, to make it mergeable again 😞 

You're right, we should indeed release it by ourselves, but I'm personally quite concerned people will start relying on this module outside of our SDK. As soon as the PR gets merged (if ever 🙄 ) we wouldn't want to further support our fork, which is definitely easier when the "entry burden" is bigger, as you need to rely on a branch - no one likes this haha.

Given the timeframe the branch & PR are open already, I agree more and more with you, a release is necessary! 

@SpainTrain ❤️ thanks for the offer of creating the package, but better to have it in our org then.
@Khaledgarbaya let's see whether we can pair on this today.

**Comment by Khaledgarbaya** [comment]
Hi @SpainTrain ,
as @zcei said we'll try to pair on this today and fix it hopefully.

**Comment by SpainTrain** [comment]
> I'm personally quite concerned people will start relying on this module outside of our SDK

Funny you mention this, because it is a *very* valid concern.  *Exact* same thing happened to me with a module specifically only intended for browserify - https://www.npmjs.com/package/querystring-es3 ; now has 55 dependents :anguished:  Publishing under a scoped name may help with this issue ¯\_(ツ)_/¯

> rebased the PR branch

Thank you for solving the mystery!  This makes sense as our lockfile would have the old git-ref and the live branch would have the new one.  The bright side is that the lockfile is doing its job :smile_cat: 

Thanks for your quick reply and help with this!

**Comment by zcei** [comment]
@SpainTrain Good news!
We had time pairing on this today, and there's [`v5.0.4`](https://github.com/contentful/contentful.js/releases/tag/v5.0.4) which makes use of `@contentful/axios`

**Comment by zerdos** [comment]
Hey guys, the new version (5.0.4) is also buggy. 
We had to downgrade back to 4.6.1 - this was the only option for us to be build the our project.
On a Friday.

**Comment by SpainTrain** [comment]
Thanks! Looks like I am getting the following while building a bundle:

```
ERROR in ./node_modules/contentful/dist/es-modules/contentful.js
       Module not found: Error: Can't resolve 'axios' in '/tmp/build_432a5fc110f712411fba1437061d6d31/homezen-hz-webapp-506bb01c87a66341cf7e596cd60b022220d05003/node_modules/contentful/dist/es-modules'
       @ ./node_modules/contentful/dist/es-modules/contentful.js 10:0-26
       @ ./app/contentful/storage-client.js
       @ ./app/contentful/contentful.js
       @ ./app/contentful/index.js
       @ ./app/client-main.js
       @ multi babel-polyfill ./app/client-main
```

**Comment by SpainTrain** [comment]
opened a PR for the fix - https://github.com/contentful/contentful.js/pull/204
