### ISSUE TITLE
The type I set for Generic is replaced with "never" when used in the fields variable.

### ISSUE THREAD

**Issue by LeeSeongJinCa** [contentful/contentful.js#2054]
## Expected Behavior
- The type I set to Generic should be the type of the fields variable.

## Actual Behavior
- But now, the type I set for Generic is replaced with "never" when used in the fields variable.

## Possible Solution
- How can I solve this problem?
- Just using type guard?

## Steps to Reproduce

```ts
const entry = await client.withoutUnresolvableLinks.getEntry<{ contentTypeId: string; fields: { name: string } }>('entryId', {});
const name = (entry.fields as { name: string }).name; // like this?
```
<img width="587" alt="image" src="https://github.com/contentful/contentful.js/assets/48551881/f00344a2-84b2-4a92-87cb-fd1e23e24d6a">

## Environment
```json
{
  "contentful": "^10.6.5"
}
```

-   **Language Version**: v18.18.2
-   **Package Manager Version**: 9.8.1
-   **Browser Version**: Version 118.0.5993.117 (Official Build) (arm64)
-   **Operating System**: Apple M2 Max
-   **Package Version**: ^10.6.5
-   **Which API are you using?**: Delivery

**Comment by marcolink** [comment]
Hi @LeeSeongJinCa,
the field type should be one of [EntryFieldTypes](https://github.com/contentful/contentful.js/blob/master/lib/types/entry.ts#L27). 

```ts
const entry = await client.withoutUnresolvableLinks.getEntry<{ 
   contentTypeId: string; 
   fields: { 
      name: EntryFieldTypes.Symbol 
   } 
}>('entryId', {});
```
This will give you a typed response.
