### ISSUE TITLE
Types are broken and do not match api data

### ISSUE THREAD

**Issue by CalebJamesStevens** [contentful/contentful.js#2060]
## Expected Behavior
Contentful types should reflect data coming back from the API and contenful types should accurately reflect the types they are trying to reflect.

## Actual Behavior
Contentful types assum data that does not exists and types do not reflect type they are are attempting to extends.

## Possible Solution
Is there a reason to have the extra data? Can we just have it extend string like before?

## Steps to Reproduce
<img width="518" alt="Screenshot 2023-11-10 at 3 30 15 PM" src="https://github.com/contentful/contentful.js/assets/61043345/0ef2a160-fd48-4ce4-ad03-e6ca4db003a3">
<img width="512" alt="Screenshot 2023-11-10 at 3 34 38 PM" src="https://github.com/contentful/contentful.js/assets/61043345/0f6cc4f9-2a86-4af2-b40c-492931599c38">
<img width="685" alt="Screenshot 2023-11-10 at 3 36 37 PM" src="https://github.com/contentful/contentful.js/assets/61043345/e3a02f95-c34d-436c-b614-884d55612e9e">

import EntryFieldTypes type from 'contentful' package. 
Set a variable typed to EntryFIeldTypes.Symbol or Array JUST AS AN EXAMPLE

Notice the string and array functions are not available on variable.

Also noticed that if string is passed in manually typescript will throw and error saying that 
`Type 'string' is not assignable to type 'Symbol<string>'.`

## Context

The new contentful updates (especially with axios dependencies) is throwing up our automation alarms because of security issue. We have to update. Our pipelines are currently blocked because of this and after upgrading all our types and code is broken because the types do not match the usage anymore.

## Environment

-   **Language Version**: node v18.16.0
-   **Package Manager Version**: yarn 1.22.19
-   **Operating System**: Darwin MacBook Pro 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
-   **Package Version**: 10.6.6
-   **Which API are you using?**:  Delivery

**Comment by veu** [comment]
Hi, 

with contentful.js v10 we overhauled the types to provide more flexibility and give you a more accurate representation of your data that wasn’t possible before. The basis of the new types is the new `Entry` type which takes a skeleton type (an abstract representation of your entry) and the configuration of contentful.js you’re using to tell you what shape the returned data takes.
The `Symbol` type you’re looking at is part of the abstract entry representation which is why it doesn’t extend `string`. It’s meant to be passed either into the `Entry` type or to the client methods as described in our [documentation](https://github.com/contentful/contentful.js/blob/master/TYPESCRIPT.md).

Here’s an example of how to get to the symbol field manually.

```typescript
import * as Contentful from "contentful";

type ExampleEntrySkeleton = Contentful.EntrySkeletonType<{
  textField: Contentful.EntryFieldTypes.Symbol,
}>;

type ExampleEntry = Contentful.Entry<ExampleEntrySkeleton, undefined>;

const entry = {} as ExampleEntry;

entry.fields.textField; // this is a string now
```

**Comment by restfulhead** [comment]
Could I get some advice on how to query with `sys.publishedVersion` and `sys.archivedVersion`?

The following does not work:

```
client.getEntries({
     'sys.publishedVersion[exists]': false, 
     'sys.archivedVersion[exists]': false,
    })
```

Error:

```
Argument of type '{ 'sys.publishedVersion[exists]': boolean; 'sys.archivedVersion[exists]': boolean; }' is not assignable to parameter of type 'EntriesQueries<T, "WITHOUT_LINK_RESOLUTION"> | undefined'.
  Object literal may only specify known properties, and ''sys.publishedVersion[exists]'' does not exist in type 'EntriesQueries<T, "WITHOUT_LINK_RESOLUTION">'.ts(2345)
```

**Comment by marcolink** [comment]
Hi @restfulhead, 
[here](https://github.com/contentful/contentful.js/blob/master/lib/types/sys.ts#L17-L24) you can find the known fields for the entry `sys` object. The fields you mentioned only [exist on the CMA](https://github.com/contentful/contentful-management.js/blob/master/lib/common-types.ts#L215-L216) (management API) and not on the CDA (delivery API)

**Comment by restfulhead** [comment]
@marcolink Yes, it does work with the preview content delivery API: 

https://preview.contentful.com/spaces/***/environments/***/entries?content_type=articlePage&sys.publishedVersion[exists]=false&sys.archivedVersion[exists]
