### ISSUE TITLE
Unit Testing and mocking

### ISSUE THREAD

**Issue by mbenjamin618** [contentful/contentful.js#209]
* **Node Version**: v8.9.1
* **Npm Version**: 5.5.1
* **Platform**: Darwin Kernel Version 17.2.0
* **Package Version**: 4.6.4

I am trying to write a unit test for an action that uses the `createClient` API. I've attempted to ___intercept___ the URL that it should be hitting, but to no avail. I am seeking help on the best way to test this by intercepting the request to Contentful. Below is a bit of the code:

### actions.js
```
meow = () => {
  mergedParams = {
    limit: 100,
    'content_type': 'XXXXX',
  }
  return client.getEntries(mergedParams)
    .then((response) => {
      response = JSON.parse(response.stringifySafe())
      dispatch(returnAuthorFetchSuccess(response.items))
    })
    .catch((response) => {
      dispatch(returnAuthorFetchFailure({
        error: 'Unable to fetch XXXXX.',
        response,
      }))
    })
}
```

### test.js
```
fetchMock.getOnce(`https://cdn.contentful.com:443/spaces/${process.env.REACT_APP_CONTENTFUL_SPACE}/entries?access_token=${process.env.REACT_APP_CONTENTFUL_TOKEN}&content_type=XXXXX`, { value: 'meow' })

    return store.dispatch(actions.meow())
      .then(() => {
        const response = store.getActions()
     })
```

Does anyone have any insight on the best way to approach this?

**Comment by Khaledgarbaya** [comment]
Hey @mbenjamin618 ,
There is different ways of mocking the library depends on your use case.
there is a library called [contentfaux](https://www.npmjs.com/package/contentfaux) that maybe can help you.

**Comment by mbenjamin618** [comment]
I can't believe I never came across this in all my googling, thank you @Khaledgarbaya

**Comment by mbenjamin618** [comment]
So after some investigating, this library isn't that great for my solution. I edited the original post to post a more specific question.

**Comment by Khaledgarbaya** [comment]
Hi @mbenjamin618 ,
You can mock the contentful dependency to tell it to return the result you expect.
using libraries like `sinon` or if you are using jest you can [mock](https://facebook.github.io/jest/docs/en/manual-mocks.html) the entire module

**Comment by axe312ger** [comment]
If you still stuck, https://github.com/jhnns/rewire might help you to. Not the most beautiful way but it works.

Please let us know if it worked, I'd like to help you or close this issue, depending on your state :)

**Comment by mbenjamin618** [comment]
Ended up using the Jest Mock library to mock Contentful. Thank you for all your feedback.

**Comment by ChazUK** [comment]
@matthewfbenjamin any example of this?

**Comment by marcolink** [comment]
In your test, you can initialise the client using an [adapter](https://github.com/contentful/contentful.js#request-configuration-options). This allows for using https://www.npmjs.com/package/axios-mock-adapter (contentful.js uses axios under the hood)
