### ISSUE TITLE
Contentful 5.0.5 does not work on AWS

### ISSUE THREAD

**Issue by bradley-marker-ck** [contentful/contentful.js#210]
* **Node Version**: v6.11.5
* **Npm Version**: 3.10.10
* **Platform**: centos7
* **Package Version**: contentful@5.0.5

We have to set http_proxy and https_proxy on AWS. Contentful has a branched version of Axios because of a bug with the proxy settings.

It looks like it broke again in 5.0.4 or 5.0.5 (it was scoped and moved?). We work with 5.0.3. We fail with 5.0.5. The behavior is the same as running with Axios without the fix from the Contentful branch of Axios.

It works in environments that do not require the proxy settings.

**Comment by bradley-marker-ck** [comment]
contentful@5.0.3
  └── axios@0.17.1

contentful@5.0.5
  └── @contentful/axios@0.18.0

Looks like there were proxy related changes between the two versions, not just the package scope change.

**Comment by Khaledgarbaya** [comment]
Hi @bradley-marker-ck,
we'll look into that, can you share a code snippet to get more details.
Best,
Khaled

**Comment by bradley-marker-ck** [comment]
From AWS, you can only connect outside using a proxy. We set http_proxy and
https_proxy. The only Contentful API we call is the sync API. If http_proxy
and https_proxy are not set, the sync request times out after 30 seconds
(and Contentful or Axios retries with backing off).

const params: CreateClientParams = {
    space: config.get('space.id'),
    accessToken: config.get('space.accessToken'),
    resolveLinks: false,
}

Bradley

**Comment by bradley-marker-ck** [comment]
On 5.0.3, it works as expected with http_proxy and https_proxy set but on
5.0.5 is behaves the same as if the environment variables were not set.

Bradley

**Comment by Khaledgarbaya** [comment]
Hi @bradley-marker-ck,
you need explicitly pass the proxy when creating the client.
```
const HttpsProxyAgent = require('https-proxy-agent')
const {createClient} = 'contentful'

const params: CreateClientParams = {
    space: config.get('space.id'),
    accessToken: config.get('space.accessToken'),
    resolveLinks: false,
    httpsAgent: new HttpsProxyAgent({ host, port })
}
const client = createClient(params)
```

**Comment by bradley-marker-ck** [comment]
The Axios client defaulted to using the environment variables in 5.0.3.
You’ve broken this in 5.0.4 or 5.0.5.

Bradley

**Comment by bradley-marker-ck** [comment]
In addition to http_proxy and https_proxy, the environment variables
support no_proxy. This is much harder to re-implement as a caller of your
client. We run the same container image in different environments where the
proxy settings are different so we depend on the environment variables.

Bradley

**Comment by marcolink** [comment]
With no action on this issue, 
i will close it for now. 

Feel free to open it again.
