### ISSUE TITLE
Typing Error: Type '{ [x: string]: never; }' is missing the following properties

### ISSUE THREAD

**Issue by enersis-pst** [contentful/contentful.js#2103]
Argument of type '{ [x: string]: never; }' is not assignable to parameter of type 'Document'.
  Type '{ [x: string]: never; }' is missing the following properties from type 'Document': nodeType, content, datats(2345)

I want to define a entry of a specific contentType. For this i create this interface:
```
type OrderFormFields = {
  moduleId: EntryFields.Symbol;
// some more
};
export type OrderFormEntry = Entry<EntrySkeletonType<OrderFormFields>>;
```

But for every field i got this type error:
```
Argument of type '{ [x: string]: never; }' is not assignable to parameter of type 'Document'.
  Type '{ [x: string]: never; }' is missing the following properties from type 'Document': nodeType, content, datats(2345)
(property) condition: {
    [x: string]: never;
}
```

What im doing wrong?

## Environment

node: v18.16.1
"contentful": "^10.6.10",
"typescript": "~5.1.3",

**Comment by veu** [comment]
`EntryFields.Symbol` should be replaced with `EntryFieldTypes.Symbol` like this.

```typescript
type OrderFormFields = {
  moduleId: EntryFieldTypes.Symbol;
// some more
};
export type OrderFormEntry = Entry<EntrySkeletonType<OrderFormFields>>;
```

`EntryFieldTypes` are the abstract types to describe the shape of your data while `EntryFields` represent the actual data.

You can also use [cf-content-types-generator](https://github.com/contentful-userland/cf-content-types-generator) to generate the types.
