### ISSUE TITLE
How to filter out drafts?

### ISSUE THREAD

**Issue by angelod1as** [contentful/contentful.js#2104]
According to the [documentation](https://www.contentful.com/developers/docs/tutorials/general/determine-entry-asset-state/), I should be able to filter out if an entry is a draft in Content Management API, but how can I do it in Content Delivery API?

## Expected Behavior
I should be able to filter out drafts in the Content Delivery API

## Actual Behavior
I can't filter out drafts in the Content Delivery API

## Possible Solution
A property that explicitly says if an entry is a draft or not would be good — or a good soul that points me to how to do it.

## Environment

-   **Language Version**: v18.17.0
-   **Package Manager Version**: 9.6.7
-   **Operating System**: Darwin MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
-   **Package Version**: 9.3.5
-   **Which API are you using?**: Delivery & Management

**Comment by marcolink** [comment]
The Content Delivery API only returns published entries. If you are interested in draft states, you can use the [Content Preview API](https://github.com/contentful/contentful.js?tab=readme-ov-file#using-this-library-with-the-preview-api).
