### ISSUE TITLE
Is logHandler supported  in contentful.createClient?

### ISSUE THREAD

**Issue by adamrisser** [contentful/contentful.js#212]
* **Node Version**: 8.2.1
* **Npm Version**: 5.3.0
* **Platform**: osx high sierra
* **Package Version**: 5.0.5 

In the `README` it mentions you can supply your own `logHandler` to `createClient`

https://github.com/contentful/contentful.js#loghandler-default-function-level-data-

But it looks like its actually not supported in the `createClient` section of the 
https://contentful.github.io/contentful.js/contentful/5.0.5/contentful.html#.createClient

I also don't see mention of it in the actual code. Is the `README` incorrect or am I just missing something? Thanks!

**Comment by zcei** [comment]
The library is passing your user-provided `params` [into the `contentful-sdk-core` here](https://github.com/contentful/contentful.js/blob/c085f3558b82a1f894fa3ffdce00fcb56d9da4a8/lib/contentful.js#L63). Within there [the `logHandler` is available](https://github.com/contentful/contentful-sdk-core/blob/e040ba6820bf96197ac19e32480ceb152db150b4/lib/create-http-client.js#L29)

So yes, you can use it and the docs should reflect this, thanks 👍
