### ISSUE TITLE
Update Axios to 1.6.5

### ISSUE THREAD

**Issue by JabraJim** [contentful/contentful.js#2136]
Hello, can we get Axios updated to 1.6.5? [Snyk](https://app.snyk.io/org/listenlively/project/9c121a31-580f-4242-ba31-9005cd80b6f1#issue-SNYK-JS-AXIOS-6144788) is reporting there's an issue with Axios 1.6.0. If it gets upgraded to 1.6.4 then there's still a [follow-redirects issue](https://app.snyk.io/org/listenlively/project/9c121a31-580f-4242-ba31-9005cd80b6f1#issue-SNYK-JS-FOLLOWREDIRECTS-6141137)

**Comment by marcolink** [comment]
The client is currently [build](https://github.com/contentful/contentful.js/blame/master/package-lock.json#L4040) with `axios@1.6.4`. The version is not pinned to a fix version. depending on how your project is build, you can define the axios version yourself. Additionally, please feel free to open a PR on this repo!
