### ISSUE TITLE
CDA delivers Draft Links without `fields` property

### ISSUE THREAD

**Issue by dganoff** [contentful/contentful.js#214]
* **Node Version**: 7.10.1
* **Npm Version**:  4.2.0
* **Platform**: MacOS
* **Package Version**: 5.0.5

Is there a way to tell the Content Delivery API to **not include** Draft reference links?

I have a contentful site where some of the **published** content has reference links to content that is **not published (aka in Draft status)**. When the API returns data for this content, it resolves the links, but only includes the `sys` property and no `fields` property which breaks my app. I would have expected the link reference to be `undefined` or simply not be included in the response since the content it refers to is not yet published. 

I considered using the `select` query to only return the `fields`, but that doesn't seem possible when I am using `getEntries` that searches by `sys.id` for a specific entry ID. Also, I _do_ need the `sys` property for some of my content, so filtering our the `sys` property entirely isn't really an option.

It seems like there should be any easy way around this rather than adding a bunch of logic in my application that accounts for content with `sys` property, but no `fields` property.

Thanks.

**Comment by Khaledgarbaya** [comment]
hi @dganoff,
Thanks for your feedback, I will add that to our todo list.
Meanwhile as a workaround to filter all drafts you can
```js
client.getEntries()
  .then(response => response.items)
  .then(items => items.filter(item => item.fields))
  .then(itemsWithNoDraft => {
    // ...
})
```

**Comment by dganoff** [comment]
Thanks @Khaledgarbaya for the quick response. Your filter function only goes one level deep. I actually wrote a recursive function that loops through all the nested linked entries and removes those without the `fields` property, however that function sometimes exceeds the maximum call stack because of how many nested references there are.

Perhaps I've implemented an anti-pattern, but my site has page content types that basically have nested references for all the sections of the page. This results in me having to use the `include: 10` query to get all the nested references. I did this so I'd have all the content for the page in one request, otherwise I'd have to make many separate API requests to retrieve all the linked content on the page.

Thanks for any advice you can provide on this topic.

**Comment by Khaledgarbaya** [comment]
he @dganoff ,
This [PR](https://github.com/contentful/contentful.js/pull/218) exposes an option to ignore non resolved fields. when creating the client you can add `removeUnresolved: true` to achieve your request.

please try the new version mentionned in the PR and tell me if that works for you.

```
const client = creatClient({space: '<space-id>', accessToen: '<token>', removeUnresolved: true})
```
Best,
Khaled

**Comment by dganoff** [comment]
Hey @Khaledgarbaya, wow thanks for implementing a solution to my issue!

I did however find a bug in the parsed response that the client returns for a `getEntries` request. It seems to be removing (setting to `undefined`) the `sys.contentType` and `sys.space` fields from the `items` array objects.

I believe the bug lies somewhere related to this line in the `contentful-resolve-response` package: https://github.com/contentful/contentful-resolve-response/blob/master/index.js#L71

I'll see if I can dig some more to find exactly where the logic bug is. 

Thanks!

**Comment by Khaledgarbaya** [comment]
Hey @dganoff that's why I released it as Beta, Thanks for the quick test, we'll fix that by next week

**Comment by dganoff** [comment]
Thanks @Khaledgarbaya I'll look out for that update!

**Comment by dganoff** [comment]
@Khaledgarbaya I just installed `contentful@5.1.0-beta2` and it looks like things have improved, but I am seeing missing entries replaced with `undefined` instead of completely removed from the JSON response. Is that intended?

**Comment by dganoff** [comment]
Bump /cc @Khaledgarbaya

**Comment by axe312ger** [comment]
No it is not, let me check @dganoff  👀

**Comment by axe312ger** [comment]
@dganoff I created a pull request ☝️ which should fix this issue. Please have a look, we will code review it next week.

Have a great weekend,
Benedikt

**Comment by dganoff** [comment]
Thanks @axe312ger I will take a look now!

**Comment by dganoff** [comment]
@axe312ger I see you closed the PR. Do you know when this will be released? Thanks!

**Comment by Khaledgarbaya** [comment]
@dganoff soon, probably today

**Comment by hustleandcuss** [comment]
@Khaledgarbaya 
Is this suppose in v1.5.3? I can't get it to work, for one the key isn't in the ts definition, but event after adding it locally, I get no difference in the response. 

"This PR exposes an option to ignore non resolved fields. when creating the client you can add removeUnresolved: true to achieve your request.
please try the new version mentionned in the PR and tell me if that works for you.
const client = creatClient({space: '<space-id>', accessToen: '<token>', removeUnresolved: true})
Best,
Khaled"

**Comment by axe312ger** [comment]
@hustleandcuss There was a bug which, in some cases, prevented the fields from being removed. Version `v5.1.2` should have fixed the problem. 

Not sure what the `v1.5.3` is you are referencing, that would be a very old version.

**Comment by MarineLB** [comment]
What's the best way to work around this when using Sync API ?

**Comment by MarineLB** [comment]
I am already using : `resolveLinks: false`, to resolve the links myself on Sync Update, won't `removeUnresolved: true` remove every link in the response ?

**Comment by axe312ger** [comment]
Correct, it would do that.

**Comment by axe312ger** [comment]
I am not exactly sure what you want to workaround.

If `resolveLinks ` is turned off, the SDK will return the API result untouched aka with Link entities to represent the relation between two entries.

If enable `removeUnresolved`, it will remove these Link Entities.

If you combine both, it will resolve everything that is resolveable and remove only links that link to draft entries or deleted entries.

If you resolve on your own, you have to take care of your own to delete unresolveable entries. https://github.com/contentful/contentful-resolve-response might help, but this is exactly what we do internally in the SDK.

Does this help?

**Comment by MarineLB** [comment]
Basically, we resolve the links ourself because the on Sync API update, we lose the link resolve. 
Now, we get all of the entries, even though they are not published.
I'm only trying to know if there's a way to detech unpublished entries in the response.

**Comment by axe312ger** [comment]
Here you can find the checks we do to detect the entry states like unpublished (draft) and so on:

https://github.com/contentful/contentful-management.js/blob/e5f80afd1382d5e9209b32d01ab1cbe1c4c0616b/lib/instance-actions.js#L76-L112

**Comment by o-az** [comment]
`removeUnresolved: true` is no longer an option. How can we filter out unpublished posts?

**Comment by Kiran-KumarR** [comment]
> `removeUnresolved: true` is no longer an option. How can we filter out unpublished posts?

As of now , looks like ```removeUnresolved``` prop has been removed

**Comment by axe312ger** [comment]
@Kiran-KumarR @o-az this is documented in the steps to migrate: https://github.com/contentful/contentful.js/blob/master/MIGRATION.md#migration-to-contentfuljs-10x
