### ISSUE TITLE
TypeScript definition for stringifySafe, the parameters should be optional

### ISSUE THREAD

**Issue by briancodes** [contentful/contentful.js#215]
Hi

In `index.d.ts`, the `stringifySafe` function might need to have optional params. Currently `stringifySafe(null, '')` works, but looking at the JS I don't think the params are actually required. If none passed TypeScript gives an error `Expected 2 arguments, but got 0.`

`stringifySafe(replacer: any, space: any): string;`
change to
`stringifySafe(replacer?: any, space?: any): string;`

**Comment by googol** [comment]
PRs are welcome for these fixes!

**Comment by axe312ger** [comment]
Thank you Brian for that report. As googol said, PRs are very welcome.

We may update the definitions while adding type definitions to the management SDK.

Best,
Benedikt

**Comment by marcolink** [comment]
This is already fixed, closing this issue now.
