### ISSUE TITLE
Update axios library on Contentful v9 due to security findings

### ISSUE THREAD

**Issue by dhardjono** [contentful/contentful.js#2156]
Hi, would it be possible to bump the `axios` library on Contentful v9 (current latest `9.3.5`) to use `axios 1.6.5`? The current `axios` on `contentful 9.3.5` is `"axios": "^0.27.0",`, which is very old and has multiple security findings (e.g. [XSRF](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx)).

Due to the amount of users still using v9 of Contentful, perhaps it would be great to fix this. Or is there any explicit reason not to do this? Thanks!

**Comment by dhardjono** [comment]
Related issue (presumably this one is for v10): https://github.com/contentful/contentful.js/issues/2136

**Comment by dhardjono** [comment]
It's fixed! https://github.com/contentful/contentful.js/blob/v9.3.6/package.json Thanks to everyone involved :)

**Comment by axe312ger** [comment]
🙇
