### ISSUE TITLE
Minified build is not exported correctly as ESM

### ISSUE THREAD

**Issue by Techn1x** [contentful/contentful.js#2157]
## Expected Behavior

I should be able to import contentful.js into my production build and use the createClient function

## Actual Behavior

`createClient is not a function` when using the minified export

See my comment here for more info
https://github.com/contentful/contentful.js/issues/1936#issuecomment-1900027685

## Possible Solution

Ensure the minified build is exported as ESM

## Steps to Reproduce

Failing test; https://github.com/contentful/contentful.js/pull/2130
and/or
import contentful.js `>= 10.1.4` & use createClient in a production build

## Context

More info here in my comment.
https://github.com/contentful/contentful.js/issues/1936#issuecomment-1900027685

Failing test here. 
https://github.com/contentful/contentful.js/pull/2130

Creating a dedicated issue so this can get some eyes on it. Comment & PR alone didn't seem to get much traction.

## Environment

pnpm 8
contentful 10.6.21

**Comment by Techn1x** [comment]
I'm using the pnpm patch mentioned in the linked issue, to use the unminified file

**Comment by lorenzo-del-rosario** [comment]
@Techn1x how do you apply the pnpm patch?

**Comment by Techn1x** [comment]
If you use pnpm as a package manager, it has a patcher built in
https://pnpm.io/cli/patch
`pnpm patch contentful`
It gives you a path where to edit the package as needed, then follow instructions to commit the change.

Otherwise you can install and use something like patch-package to do a similar thing
https://www.npmjs.com/package/patch-package

**Comment by Techn1x** [comment]
Can confirm this is no longer an issue in 10.9.0+ 🎉 I was able to remove my pnpm patch code, and production builds work just fine. Closing this issue
