### ISSUE TITLE
Problem with snyc

### ISSUE THREAD

**Issue by imjustabillr** [contentful/contentful.js#22]
Hi. I've pulled the latest contentful.js and am trying to test the synchronization and it gives me an error : 

Uncaught TypeError: undefined is not a function

at 

// Get all data in a space
        client.sync({initial: true})
            .then(function(data){
                syncToken = data.nextSyncToken;
            });

Any idea what is going on? I've copied your example exactly. The only thing I've changed is the space id and access token.

**Comment by sdepold** [comment]
Hi @imjustabillr,

could you paste the whole code (including the require statement and the client initialization) as well as the stacktace? Please mask the auth token and space id though :)

**Comment by imjustabillr** [comment]
`
    <script src="js/angular.min.js"></script>
    <script src="js/contentful.min.js"></script>
   
    <script type="text/javascript">

        var client = contentful.createClient({
            space: 'myspace',
            accessToken: 'myaccess',
            secure: true,
            host: 'cdn.contentful.com'
        });

        var log = console.log.bind(console); // wat

        // Get Space
        client.space().then(log, log);

        // Get all Entries
        client.entries().then(log, log);

        // Get Assets using callback interface
        client.entries({}, function(err, entries) {
            if (err) { console.log(err); return; }
            console.log(entries);
        });

        var syncToken;
        // Get all data in a space
        client.sync({initial: true})
            .then(function(data){
                syncToken = data.nextSyncToken;
            });

        // Get all data since the last sync
        client.sync({nextSyncToken: syncToken})
            .then(function(data){
                syncToken = data.nextSyncToken;
            });

    </script>`


The error I'm getting is :
Uncaught TypeError: undefined is not a functionTest4.php:35 (anonymous function)

Line 35 is  client.sync({nextSyncToken: syncToken})

**Comment by sdepold** [comment]
Could you do the following for me?

```
console.log(client.sync.toString()) 
```

And send me the result?

**Comment by imjustabillr** [comment]
Uncaught TypeError: Cannot read property 'toString' of undefinedTest4.php:33 (anonymous function)

**Comment by sdepold** [comment]
Are you using the latest version of the client (which is 1.1.1) ?

**Comment by imjustabillr** [comment]
That was my thought as well. I don't know which version I'm using. I'm using whichever one is linked to on the main contenful,js page under "Latest contentful.min.js" . Where should I be getting it?

**Comment by sdepold** [comment]
Should be working now :)

**Comment by imjustabillr** [comment]
That did it. Thank you.
