### ISSUE TITLE
Expose sync pagination to the client

### ISSUE THREAD

**Issue by josephg** [contentful/contentful.js#220]
* **Node Version**: (all)
* **Npm Version**: (all)
* **Platform**: (all)
* **Package Version**: 5.1.0

I'm building a search indexer built on top of the sync API. To do this I'm going to be walking through all the data on first run, then periodically polling to get changes and reindexing the updated fields.

Contentful.js gathers all paginated data before returning any to the client. This is dangerous for me - on first run this means we'll be scooping up the entire database into the node process's memory before we can process any of it. I don't know how big the data will grow in the future, and I don't want to rely on it fitting in memory. I'd rather process the data one page at a time.

Can you expose an option to turn off the automatic pagination handling in sync?

**Comment by axe312ger** [comment]
@josephg Hey there 👋 

We just released a new beta with this functionality.  May you please try it out and report back if it is working for you?

`npm install contentful@next`

All the best,
Benedikt

**Comment by josephg** [comment]
Woohoo! Thanks for the fast turn around! I'll have a play with it today and let you know if I run into any issues!

**Comment by josephg** [comment]
Its working, but the documentation in the readme lists it as `{pagination: true}`, in the code its actually `{paginate: true}`. It'd be good to clarify that.

**Comment by axe312ger** [comment]
Awesome and thanks for pointing that out. Will fix the docs asap :)
