### ISSUE TITLE
Why is there no EntryFieldTypes for Asset?

### ISSUE THREAD

**Issue by LookRain** [contentful/contentful.js#2203]
I have an asset field in my content named `featureImage`, on my frontend I want to correctly type this field, however there's no suitable EntryFieldTypes that gives me the correct inference of the `featureImage` type

```ts
const res = await client.getEntries<{
      fields: {
        resource_title: EntryFieldTypes.Text;
        author: EntryFieldTypes.Text;
        summary: EntryFieldTypes.Text;

        featureImage: // how do I type this??
      };
      contentTypeId: string;
    }>();

res.items[0].featureImage.fields.file.url
                          ^ TS error

```

## Expected Behavior

```ts
const res = await client.getEntries<{
      fields: {
        resource_title: EntryFieldTypes.Text;
        author: EntryFieldTypes.Text;
        summary: EntryFieldTypes.Text;

        featureImage: // how do I type this??
      };
      contentTypeId: string;
    }>();

res.items[0].featureImage.fields.file.url
                          ^ I should be able to type featureImage so that this can be correctly inferred

```

## Actual Behavior
TS error

## Possible Solution
How should I type asset fields?

## Steps to Reproduce

1.
2.
3.
4.

## Environment

-   **Language Version**: 
-   **Package Manager Version**: 
-   **Browser Version**: 
-   **Operating System**: 
-   **Package Version**: 
-   **Which API are you using?**:

**Comment by marcolink** [comment]
Hey @LookRain, 
[here](https://codesandbox.io/p/sandbox/contentful-cda-image-ym868b?file=%2Fsrc%2FApp.tsx%3A46%2C1-47%2C1) is an example of an entry with an image field - fully typed! maybe that helps

**Comment by emavitta** [comment]
got the same problem here. The example seems exactly like mine, still doens't work (i'm using nuxt3 and contentful 10.8.7)

**Comment by emavitta** [comment]
NVM, @marcolink your code is correct and works to me too.

Thanks

**Comment by LookRain** [comment]
hi @marcolink thanks for the example. 

it seems to work with getEntry but not with getEntries though.

**Comment by LookRain** [comment]
actually it doesn't even work in the example you provided... 
<img width="672" alt="image" src="https://github.com/contentful/contentful.js/assets/11829847/6e08311b-abb4-43de-83cb-9724576337c5">

**Comment by marcolink** [comment]
@LookRain you're right, the example is outdated, here is an [updated version](https://www.typescriptlang.org/play/?ts=5.4.5#code/JYWwDg9gTgLgBDAnmApnA3gKDnAwgCwENgA7AWQgBNgAzYFKAZwBps4BREmKRVnT7ogBi9ADaUAKshQs2AngGUA1ilEoYEElNR84AGQgBjQmtxUUmAL5waUCCDgAiQ5pgouNAK6jHAbkyYoJCwGHCGUCiEbrii9Fxw1rb2Ti5c7jBePv5B0PDocJ6MKLgmogBGhIZKzAVF7DQ0KIYwNYUoCjBRaIl2Do4RlTB+AamM8AoACgCCuOwA+gCSACJwALxOSgAMwMCMAO4AbpSeAF4AHABWw6PwM7MKCnMSAPIA0uwAcmtOL3MAaidREIAEwAZkQAEZDIgHgBNMofTZgGASCSiABaBzm7DOwEoMFBS02ojmACEAOx-C4XWHXTRjDgfCQAJVhixW60cwJoz0YZRAHwA4qC0fgoKIFiQhKSAOo0MqvYaYG5hWLpb7hSLRNVcAAUWBwlUMMkYEggKhIAC44Hd2A8nm9PrpGGBKihrZMZvNllYAJT+TAoAAewXgpDcUBobrg2naQTUCxAhAA5igRKpKIwMGwYMAYGprfJhGJJNJGAA6BSIEBlCCifw4UAp90cLg8dPiWMVqaMIowPSkJT+SwBYOhhDSGPSBTxlCJ5vKVTqTTfIuLtQaLTSAA8bFjM-ACaTqY7md0jkYs-nqccmAAfAGx7kJ6gp6gD2Aj83dzgKNQ6AwWbBm4JCZngRCkH+tD0EwugGMYahAUGIFgfBJjFOY96rm2iDbvuV7Hu0KgbpoNRQQBsH6EY6GMA+o4hs+lAoFG3jwF4JDNMAK5TGAYC6r62Y4CqADa6Q8DUfZFgAut8bQdF0eHTgR34AOQygsEgABLPAAqhIcw6R8zJ2s8eh-FMpJ6PMegLB8rwKCpNSOO4AC0OkKI4d53vxAZCfS8DCaIECENQJDJhJ6gGCFpDJjJ6xyZ0bjbrWdaRCQ3lRqIRT+gEfkkAyQUhQwslFCUojlJUSi6oQjCIBxcD8Wsd6CTgcB9lFoXJrq3CeCgOWtWE-lwGJiDfIQezEPAhg6jA5Z7Hm+AQJ4MA6SQESMHWByEGUagDiQSgVqmMBFop77Kam67LuluqfCybLLP1rWSThuojY9ODtcFnW6pl2UNgkNTCVJOVsG09SNM0uqNaszUGq1tANQAhIVnVwAAZGjcCI29LUDSjDA+WwOAjsTIN5QyTapt8I0APzlgB4gVpTKD-SqzM6eK3zM3TDOZvTwBqHTnicwA1E4NN7KsAAsmybGj+DS7LaM0CAqx7CgZRgEq5OpeWQVdez4pk3AAD0JtwBEMDCyQDVsGbrXbtQByqjVjAfIQIAoKsjg8Vrd52+bA3bvgEJ3mYaQeN4cAyhrExwNeKDbibIf+zg9sDegiPI19MXo5j25gHeKMxUnhck6bgetZn2M4XncDbqAyZtVAhirOghuiNYJgwN7jim3e5fp-XJtO6nFdwDlI5AA).

**Comment by LookRain** [comment]
> @LookRain you're right, the example is outdated, here is an [updated version](https://www.typescriptlang.org/play/?ts=5.4.5#code/JYWwDg9gTgLgBDAnmApnA3gKDnAwgCwENgA7AWQgBNgAzYFKAZwBps4BREmKRVnT7ogBi9ADaUAKshQs2AngGUA1ilEoYEElNR84AGQgBjQmtxUUmAL5waUCCDgAiQ5pgouNAK6jHAbkyYoJCwGHCGUCiEbrii9Fxw1rb2Ti5c7jBePv5B0PDocJ6MKLgmogBGhIZKzAVF7DQ0KIYwNYUoCjBRaIl2Do4RlTB+AamM8AoACgCCuOwA+gCSACJwALxOSgAMwMCMAO4AbpSeAF4AHABWw6PwM7MKCnMSAPIA0uwAcmtOL3MAaidREIAEwAZkQAEZDIgHgBNMofTZgGASCSiABaBzm7DOwEoMFBS02ojmACEAOx-C4XWHXTRjDgfCQAJVhixW60cwJoz0YZRAHwA4qC0fgoKIFiQhKSAOo0MqvYaYG5hWLpb7hSLRNVcAAUWBwlUMMkYEggKhIAC44Hd2A8nm9PrpGGBKihrZMZvNllYAJT+TAoAAewXgpDcUBobrg2naQTUCxAhAA5igRKpKIwMGwYMAYGprfJhGJJNJGAA6BSIEBlCCifw4UAp90cLg8dPiWMVqaMIowPSkJT+SwBYOhhDSGPSBTxlCJ5vKVTqTTfIuLtQaLTSAA8bFjM-ACaTqY7md0jkYs-nqccmAAfAGx7kJ6gp6gD2Aj83dzgKNQ6AwWbBm4JCZngRCkH+tD0EwugGMYahAUGIFgfBJjFOY96rm2iDbvuV7Hu0KgbpoNRQQBsH6EY6GMA+o4hs+lAoFG3jwF4JDNMAK5TGAYC6r62Y4CqADa6Q8DUfZFgAut8bQdF0eHTgR34AOQygsEgABLPAAqhIcw6R8zJ2s8eh-FMpJ6PMegLB8rwKCpNSOO4AC0OkKI4d53vxAZCfS8DCaIECENQJDJhJ6gGCFpDJjJ6xyZ0bjbrWdaRCQ3lRqIRT+gEfkkAyQUhQwslFCUojlJUSi6oQjCIBxcD8Wsd6CTgcB9lFoXJrq3CeCgOWtWE-lwGJiDfIQezEPAhg6jA5Z7Hm+AQJ4MA6SQESMHWByEGUagDiQSgVqmMBFop77Kam67LuluqfCybLLP1rWSThuojY9ODtcFnW6pl2UNgkNTCVJOVsG09SNM0uqNaszUGq1tANQAhIVnVwAAZGjcCI29LUDSjDA+WwOAjsTIN5QyTapt8I0APzlgB4gVpTKD-SqzM6eK3zM3TDOZvTwBqHTnicwA1E4NN7KsAAsmybGj+DS7LaM0CAqx7CgZRgEq5OpeWQVdez4pk3AAD0JtwBEMDCyQDVsGbrXbtQByqjVjAfIQIAoKsjg8Vrd52+bA3bvgEJ3mYaQeN4cAyhrExwNeKDbibIf+zg9sDegiPI19MXo5j25gHeKMxUnhck6bgetZn2M4XncDbqAyZtVAhirOghuiNYJgwN7jim3e5fp-XJtO6nFdwDlI5AA).

thanks for the updated example, I think this one would work.

however I'm still confused as why isn't image asset entry typed out of the box since it's pretty standard? doing this manual typing feels quite awkward and most people wouldn't know how to do it

**Comment by marcolink** [comment]
@LookRain have you already checked out the [types generator](https://github.com/contentful-userland/cf-content-types-generator)? It would generate all the relevant types for you, including the different response types for different chains (also in combination).

**Comment by LookRain** [comment]
@marcolink no I have not, but it looks pretty useful, will give it a try! Thanks!

**Comment by marcolink** [comment]
Closing this for now.

**Comment by StDensity** [comment]
> @LookRain have you already checked out the [types generator](https://github.com/contentful-userland/cf-content-types-generator)? It would generate all the relevant types for you, including the different response types for different chains (also in combination). Please make sure you set the flag for version 10 when using it (will become the default in the next major version.

I'm getting this ts error:

Property 'fields' does not exist on type 'UnresolvedLink<"Asset"> | Asset<undefined, "en-US">'.
  Property 'fields' does not exist on type 'UnresolvedLink<"Asset">'.ts(2339)
  Its an image asset
