### ISSUE TITLE
New contentful-resolve-response dependency publishes ES6 code

### ISSUE THREAD

**Issue by kayneb** [contentful/contentful.js#223]
General convention when publishing a library is that it is at least compiled to ES5, and sometimes with an ES6 like version published alongside it that only contains ES6 import statements, with the rest being ES5. However, this new dependency, `contentful-resolve-response` publishes pure ES6, meaning that build systems need to be reconfigured to transpile dependencies rather than just source code. This is undesirable as it slows down the build process significantly.

Please publish transpiled code.

**Comment by axe312ger** [comment]
@kayneb we released a new version of `contentful-resolve-response`

If you make sure to get the new sub-dependency, your bundler should now pick up the `modules` version which will work in ES5 environments.
