### ISSUE TITLE
5.1.0 Assignment to constant variable

### ISSUE THREAD

**Issue by likwrk** [contentful/contentful.js#224]
* **Node Version**: v9.5.0
* **Npm Version**: 5.6.0
* **Platform**: Linux 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
* **Package Version**:  contentful@5.1.0

This error occurs only in production build of nuxtjs. Sorry for the minificated code below. I tried to show the correct place where error happens.

```
TypeError: Assignment to constant variable.
    at i (vendor.58499df3a3e8e97438a5.js:2)
    at i (vendor.58499df3a3e8e97438a5.js:2)
    at s.forEach.t (vendor.58499df3a3e8e97438a5.js:2)
    at Array.forEach (<anonymous>)
    at t.exports (vendor.58499df3a3e8e97438a5.js:2)
    at e.wrapEntryCollection (vendor.58499df3a3e8e97438a5.js:2)
    at vendor.58499df3a3e8e97438a5.js:2
    at <anonymous>
```
The part of the vendor.js file where error occurs:
```
xzCt:function(t,e,n){const r=n("kvU2"),o=t=>t&&t.sys&&"Link"===t.sys.type,i=(t,e,n)=>{if(e(t))return n(t);if(t&&"object"==typeof t)for(const r in t)t.hasOwnProperty(r)&&(t[r]=i(t[r],e,n),void 0===(t=t)[r=r]&&(Array.isArray(t)?t.splice(r,1):delete t[r]));return t}
//                              scroll to the right, error is there ->                                                                                                             error is in this place ^^^
```

**Comment by likwrk** [comment]
Hey. I don't have an error in unminificated build while developing. So this happens only in prod build when `client.getEntries` is called. I also tried to find the part of the code in the source, but didn't find it in the source. So how else can I help you?

**Comment by axe312ger** [comment]
The code comes from https://github.com/contentful/contentful-resolve-response

But this is not an issue with the SDK, the nuxt.js minification causes the issues. Please check https://github.com/nuxt/nuxt.js if you can find similar issues or open a ticket over there.

Thank you,
Benedikt

**Comment by likwrk** [comment]
Nuxt uses `webpack@3.10.0` which uses `uglify-js@2.8.29`. Should I make an issue in uglify-js that it produces invalid min.js file?

**Comment by axe312ger** [comment]
Maybe, cus:

Weird thing: We are using `webpack@3.10.0` && `uglify-js@2.8.29` too and it works fine. Feels like a wrong uglify config to me in nuxt.js.

The same code your posted above, but with our minified output from the bundle:

```
d=function(e){return e&&e.sys&&'Link'===e.sys.type},p=function(e,t){for(var r=0,n=e.length;r<n;r++)if(t(e[r]))return e[r]},l=function(e,t){var r=t.sys,n=r.linkType,o=r.id;return p(e,function(e){var t=e.sys;return t.type===n&&t.id===o})}
```

as you can see, it results in a valid `for(var r=0,n=e.length;r<n;r++)` and _not_ `for(const r=0,n=e.length;r<n;r++)`

I'd start in the nuxt.js repo with your issue, maybe point to this one so others have more details :)

Best,
Benedikt

**Comment by likwrk** [comment]
Understood. Thanks a lot for clarification!

**Comment by axe312ger** [comment]
Wait, stop, no, we are using `webpack@3.10.0` with https://github.com/webpack-contrib/babel-minify-webpack-plugin. So yes, might be an uglify issue 🤷‍♂️

**Comment by axe312ger** [comment]
To test this, I switched to uglify-js on my local machine and recreated the bundle, the output still does not contain any `for(const...`
-->

```
u=function(e){return e&&e.sys&&"Link"===e.sys.type},s=function(e,t){for(var n=0,r=e.length;n<r;n++)if(t(e[n]))return e[n]},f=function(e,t){var n=t.sys,r=n.linkType,o=n.id;return s(e,function(e){var t=e.sys;return t.type===r&&t.id===o})},l=function(e,t){void 0===e[t]&&(Array.isArray(e)?e.splice(t,1)
```

**Comment by likwrk** [comment]
I'll try to investigate more before creating more issues :) I assume the code can be minificated twice.

**Comment by axe312ger** [comment]
@likwrk any progress here? :)

**Comment by Tjitse-E** [comment]
@likwrk @axe312ger i've got the same problem with Nuxt and Contentful 5.1.0. I've switched back to the previous version of Contentful i've used (v5.0.5) and the downgrade solved the problem.

**Comment by likwrk** [comment]
sorry @axe312ger, I stuck to the prev version. Didn't have time to try anything with nuxt minifier.

**Comment by stefanjudis** [comment]
Hmm... I'm running with nuxt and contentful without any problems (just finished a build on netlify with updated deps). 

Here are my deps 👉🏻 https://github.com/stefanjudis/stefan-judis-website/blob/master/package.json

Running on node [9.4.0](https://github.com/stefanjudis/stefan-judis-website/blob/master/.nvmrc).
