### ISSUE TITLE
Entry returns undefined field values

### ISSUE THREAD

**Issue by nathan-t-swiftotter** [contentful/contentful.js#2268]
## Expected Behavior
When passing an EntrySkeletonType to Entry, the resulting type should match the field types that were set on the fields object for the EntrySkelatonType.

```
import { Entry } from 'contentful'

type EntryFields = {
  items: Entry<{
    fields: {
      title: string
      slug: string
    }
    contentTypeId: 'detailListPage'
  }, undefined>
}

function PageName({items}: EntryFields) {
  // page value should be { title: string, slug: string }
  const page = items.fields
}
```

## Actual Behavior
page value is `{ title: undefined, slug: undefined }`

## Steps to Reproduce
Create a function like the one above and observe the resultant type value.

## Environment

-   **Language Version**: v20.14.0
-   **Package Manager Version**: 10.7.0
-   **Operating System**: Darwin Kernel Version 23.5.0
-   **Package Version**: v10.12.3
-   **Which API are you using?**: Delivery / Preview

**Comment by marcolink** [comment]
Hi @nathan-t-swiftotter 👋 
I believe `items` is a multi reference field? in that case, you want to define the field as:

```ts
type PageFields = {
   fields: {
      title: string
      slug: string
    }
}

type PageSkeleton = EntrySkeletonType<PageFields, "detailListPage">

type EntryFields = {
  items: EntryFieldTypes.Array<EntryFieldTypes.EntryLink<PageSkeleton>>
}

type EntrySkeleton = EntrySkeletonType<EntryFields, "entry">
```

Have you tried using https://github.com/contentful-userland/cf-content-types-generator to generate your types already?

**Comment by nathan-t-swiftotter** [comment]
The issue here is that the fields must map to one of Contentful's EntryFieldTypes enums. In this case, that would be this:
```
import { EntryFieldTypes }   from "contentful";

type PageFields = {
   fields: {
      title: EntryFieldTypes.Text
      slug: EntryFieldTypes.Text
    }
}
```

https://www.contentful.com/developers/docs/javascript/tutorials/typescript-in-javascript-client-library/#:~:text=type%20BlogPostSkeleton%20%3D

**Comment by marcolink** [comment]
How could I've missed that 🙈  good catch @nathan-t-swiftotter
