### ISSUE TITLE
Issue with Proxy Connection - Boilerplate Code

### ISSUE THREAD

**Issue by rnarsinaLilly** [contentful/contentful.js#230]
**Node Version: v8.9.4
Npm Version: 5.6.0
Platform: Windows 7 64-bit
Package Version: output of `npm list contentful`
boilerplate-javascript@1.0.0 C:\DevOps\Contentful\Node-boilerplate
`-- contentful@4.6.4**

**Using Boilerplate code dowloaded from Contentful Space after Space Creation --> Model Creation --> API Creation is completed**

Works very well when running outside Corporate network

Errors Out when running within the Corporate network, tried with Proxy settings too. This is the error I am getting

Using Proxy as below

```js
const client = contentful.createClient({
  // This is the space ID. A space is like a project folder in Contentful terms
  space: SPACE_ID,
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: ACCESS_TOKEN,
  proxy: {
	    host: '**<Proxy-server host>**',
	    port: 9000,
		auth : {
			username : 'foo',
			password: 'bar'
		}
	  }
})
```
```js
Error occurred while fetching Content Types:
{ Error: Request failed with status code 400
    at createError (C:\DevOps\Contentful\Node-boilerplate\node_modules\contentful\dist\contentful.node.js:703:15)
    at settle (C:\DevOps\Contentful\Node-boilerplate\node_modules\contentful\dist\contentful.node.js:788:12)
    at IncomingMessage.handleStreamEnd (C:\DevOps\Contentful\Node-boilerplate\node_modules\contentful\dist\contentful.node.js:2936:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 30000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/vnd.contentful.delivery.v1+json',
        'X-Contentful-User-Agent': 'sdk contentful.js/4.6.4; platform node.js/8.9.4; os Windows/6.1.7601;',
        Authorization: 'Bearer 431af929600e24ad1c4826106434620549a9feefcb19cdba6d1d64653306193a',
        'user-agent': 'node.js/v8.9.4',
        'Accept-Encoding': 'gzip',
        host: 'cdn.contentful.com:443',
        'Proxy-Authorization': 'Basic Zm9vOmJhcg==' },
     baseURL: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/',
     httpAgent: false,
     httpsAgent: false,
     paramsSerializer: [Function],
     proxy: { host: 'proxy.gtm.lilly.com', port: 9000, auth: [Object] },
     logHandler: [Function: logHandler],
     retryOnError: true,
     method: 'get',
     params: {},
     url: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types',
     data: undefined },
  request:
   ClientRequest {
     domain: null,
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 5,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'proxy.gtm.lilly.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 508,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 10,
        [Symbol(bytesRead)]: 2412 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'proxy.gtm.lilly.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 508,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 10,
        [Symbol(bytesRead)]: 2412 },
     _header: 'GET https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\
nContent-Type: application/vnd.contentful.delivery.v1+json\r\nX-Contentful-User-Agent: sdk contentful.js/4.6.4; platform node.js/8.9.4; os W
indows/6.1.7601;\r\nAuthorization: Bearer 431af929600e24ad1c4826106434620549a9feefcb19cdba6d1d64653306193a\r\nuser-agent: node.js/v8.9.4\r\n
Accept-Encoding: gzip\r\nhost: cdn.contentful.com:443\r\nProxy-Authorization: Basic Zm9vOmJhcg==\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http://**<Proxy-server host>**/https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types',
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _redirectCount: 0,
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http://**<Proxy-server host>**/https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types' },
     [Symbol(outHeadersKey)]:
      { accept: [Array],
        'content-type': [Array],
        'x-contentful-user-agent': [Array],
        authorization: [Array],
        'user-agent': [Array],
        'accept-encoding': [Array],
        host: [Array],
        'proxy-authorization': [Array] } },
  response:
   { status: 400,
     statusText: 'Bad Request',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'text/html; charset=utf-8',
        'proxy-connection': 'close',
        connection: 'close',
        'content-length': '2235' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 30000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        baseURL: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/',
        httpAgent: false,
        httpsAgent: false,
        paramsSerializer: [Function],
        proxy: [Object],
        logHandler: [Function: logHandler],
        retryOnError: true,
        method: 'get',
        params: {},
        url: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types HTTP/1.1\r\nAccept: application/json, text/plain, */*
\r\nContent-Type: application/vnd.contentful.delivery.v1+json\r\nX-Contentful-User-Agent: sdk contentful.js/4.6.4; platform node.js/8.9.4; o
s Windows/6.1.7601;\r\nAuthorization: Bearer 431af929600e24ad1c4826106434620549a9feefcb19cdba6d1d64653306193a\r\nuser-agent: node.js/v8.9.4\
r\nAccept-Encoding: gzip\r\nhost: cdn.contentful.com:443\r\nProxy-Authorization: Basic Zm9vOmJhcg==\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: '<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\r\n<title>Unknown website</title>\r\n\t<style ty
pe="text/css">\r\n\t\t* { margin:0; padding:0; }\r\n\t\tbody { background:#dbe0e6; text-align:center; }\r\n\t\t#main_container  { margin:20p
x auto; width:500px; }\r\n\t\t#header { height:75px; border-bottom:1px solid #dbe0e6; }\r\n\t\t#content_container { float:left; margin-top:-
5px; background:#ffffff; }\r\n\t\t#image { width:168px; padding:2px 2px 2px 2px; text-align:center; background:#ffffff; }\r\n\t\t#content {
padding-top:15px; width:328px; float:right; text-align:left; }\r\n\t\t#content h1 { padding:0 10px 10px 0; font:12pt verdana; font-weight:bo
ld; color:#cc0000; }\r\n\t\t#content p { padding:0 15px 10px 0; font:10pt verdana; color:#000000; }\r\n\t</style>\r\n</head>\r\n<body style=
"background-color: rgb(219, 224, 230);">\r\n<br>\r\n<table style="background-color: rgb(255, 255, 255); margin-left: auto; margin-right: aut
o;" align="center" cellspacing="0" cellpadding="0" border="0">\r\n  <tbody>\r\n    <tr>\r\n      <td style="text-align: center;" colspan="2"
 rowspan="1">\r\n<img src="http://zone1.proxies.lilly.com/IE/config/ExceptionsImg/pl_swipe.png">\r\n      </td>\r\n    </tr>\r\n    <tr>\r\n
      <td>\r\n        <div id="image">\r\n<img src="http://zone1.proxies.lilly.com/IE/config/ExceptionsImg/Blue_question.png">\r\n        </
div>\r\n      </td>\r\n      <td>\r\n        <div id="content">\r\n\t\t\t\t<h1>Unknown website</h1>\r\n\t\t\t\t<p style="color:#000000;">\r\
n<b>Action:</b> Check the spelling of the website, alternatively use a search engine instead of typing the website address.<p>\r\nIf you sti
ll see this error then either raise a <a href="https://lilly.service-now.com/nav_to.do?uri=%2Fcom.glideapp.servicecatalog_cat_item_view.do%3
Fv%3D1%26sysparm_id%3Dface9e21db4a030010a9f3331d96198d">self service incident</a> or contact the Lilly IT Service Desk requesting that this
site be investigated referring to the <b><i>Proxy Blue ?</i></b>\r\n<p>\r\n<b>Reason:</b> Website does not appear to be a valid website.\r\n
<p>\r\n<b>Website:</b> https://cdn.contentful.com/spaces/a081cuik7q0t/content_types\r\n<p></p>\r\n<!-- START --- DO NOT REMOVE --- START -->
\r\n<!-- END --- DO NOT REMOVE --- END --> </div>\r\n      </td>\r\n    </tr>\r\n  </tbody>\r\n</table>\r\n</body>\r\n</html>\r\n\r\n' } }

Error occurred:
TypeError: Cannot read property 'forEach' of undefined
    at fetchContentTypes.then (C:\DevOps\Contentful\Node-boilerplate\index.js:64:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by axe312ger** [comment]
Hi @rnarsinaLilly,

thats related to a bug in our HTTP client axios. Try to pass `httpAgent` or `httpsAgent` based on your setup for more info check the reference [docs](https://contentful.github.io/contentful.js/contentful/4.6.2/contentful.html#.createClient).

You code should look like so : 

```js
const client = contentful.createClient({
  // This is the space ID. A space is like a project folder in Contentful terms
  space: SPACE_ID,
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: ACCESS_TOKEN,
  httpAgent = new HttpProxyAgent('http://foo@bar:**<Proxy-server host>**:9000')
})
```

Hope that helps
Best,
Benedikt

**Comment by rnarsinaLilly** [comment]
Tried your solution, still does not work. Please see the log below. Best Regards, Raj Narsina

const client = contentful.createClient({
  // This is the space ID. A space is like a project folder in Contentful terms
  space: SPACE_ID,
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: ACCESS_TOKEN,
  httpAgent : new HttpProxyAgent('http://foo:bar@<Proxy-server>:9000') //replaced with right server, not including here for security reasons
})



Connecting to Contentful


Welcome to the Contentful JS Boilerplate

This is a simplified example to demonstrate the usage of the Contentful CDA

Fetching and displaying Content Types ...
[warning] Connection error occurred. Waiting for 2070 ms before retrying...
[warning] Connection error occurred. Waiting for 2631 ms before retrying...
[warning] Connection error occurred. Waiting for 3490 ms before retrying...
[warning] Connection error occurred. Waiting for 4533 ms before retrying...
[warning] Connection error occurred. Waiting for 6354 ms before retrying...

Error occurred while fetching Content Types:

Error occurred:
{ Error: connect ECONNREFUSED 151.101.46.49:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '151.101.46.49',
  port: 443,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 30000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/vnd.contentful.delivery.v1+json',
        'X-Contentful-User-Agent': 'sdk contentful.js/4.6.4; platform node.js/8.9.4; os Windows/6.1.7601;',
        Authorization: 'Bearer 431af929600e24ad1c4826106434620549a9feefcb19cdba6d1d64653306193a',
        'user-agent': 'node.js/v8.9.4',
        'Accept-Encoding': 'gzip' },
     baseURL: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/',
     httpAgent:
      { domain: {},
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _promisifiedCallback: false,
        timeout: {},
        options: [Object],
        secureProxy: false,
        proxy: [Object] },
     httpsAgent: false,
     paramsSerializer: [Function],
     proxy: false,
     logHandler: [Function: logHandler],
     retryOnError: true,
     method: 'get',
     params: {},
     url: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types',
     data: undefined },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { maxRedirects: 21,
        protocol: 'https:',
        hostname: 'cdn.contentful.com',
        port: '443',
        path: '/spaces/a081cuik7q0t/content_types',
        method: 'get',
        headers: [Object],
        agent: false,
        auth: undefined,
        pathname: '/spaces/a081cuik7q0t/content_types' },
     _redirectCount: 0,
     _bufferedWrites: [],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /spaces/a081cuik7q0t/content_types HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/vnd.contentful.delivery.v1+json\r\nX-Contentful-User-Agent: sdk contentful.js/4.6.4; platform node.js/8.9.4; os Windows/6.1.7601;\r\nAuthorization: Bearer 431af929600e24ad1c4826106434620549a9feefcb19cdba6d1d64653306193a\r\nuser-agent: node.js/v8.9.4\r\nAccept-Encoding: gzip\r\nHost: cdn.contentful.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/spaces/a081cuik7q0t/content_types',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'https://cdn.contentful.com:443/spaces/a081cuik7q0t/content_types' },
  response: undefined,
  attempts: 6 }
TypeError: Cannot read property 'forEach' of undefined
    at fetchContentTypes.then (C:\DevOps\Contentful\Node-boilerplate\index.js:56:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by axe312ger** [comment]
Try to unset the following environment variables in the beginning of your script, another bug in the axios proxy implementation since it is picking these environment variables up and offers no option yet to disable this behaviour.

```
delete process.env.https_proxy
delete process.env.HTTPS_PROXY
delete process.env.http_proxy
delete process.env.HTTP_PROXY
```

**Comment by rnarsinaLilly** [comment]
Still does not help. Thank you for looking into this with Urgency ☺ Best Regards, Raj Narsina

delete process.env.https_proxy
delete process.env.HTTPS_PROXY
delete process.env.http_proxy
delete process.env.HTTP_PROXY
delete process.env.proxy

console.log(chalk.green.bold('\nConnecting to Contentful\n'))

//const agentProxy = new ProxyAgent('http://proxy.gtm.lilly.com:9000')

const client = contentful.createClient({
  // This is the space ID. A space is like a project folder in Contentful terms
  space: SPACE_ID,
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: ACCESS_TOKEN,
  /**proxy : {
         host: 'proxy.gtm.lilly.com',
         port : 9000,
         auth : {
               username: 'foo',
               password: 'bar'
         }

  } **/

  httpAgent: new HttpProxyAgent('http://proxy.gtm.lilly.com:9000')
})

FYI :

Suppose If I replace with
  proxy : {
         host: 'proxy.gtm.lilly.com',
         port : 9000,
         auth : {
               username: 'foo',
               password: 'bar'
         }

  }

Instead of
httpAgent: new HttpProxyAgent('http://proxy.gtm.lilly.com:9000')

It errors out in same place immediately than timing out after multiple reties.

**Comment by axe312ger** [comment]
Are you sure it is a http proxy? Maybe try the https package + url

**Comment by rnarsinaLilly** [comment]
Yes, I am sure ☺. The same proxy works when I am installing npm packages, but it is failing when a node.js code calling to access Conentful space.

Best Regards,
Raj Narsina

**Comment by gupta-abhi** [comment]
Hi @rnarsinaLilly ,
Could you please check your contentful package. We also faced similar issue few days back. We switched back to **Contentful@4.3.0** and it started to work fine for us.

Best Regards,
Abhishek Gupta.

**Comment by rnarsinaLilly** [comment]
Hi Abhishek,
Does it mean, it has the issue with contentful@4.6.4<mailto:contentful@4.6.4>? When I checked my version, I have contentful@4.6.4<mailto:contentful@4.6.4>


C:\DevOps\Contentful\Node-boilerplate>npm list contentful
boilerplate-javascript@1.0.0 C:\DevOps\Contentful\Node-boilerplate
`-- contentful@4.6.4

Best Regards,
Raj Narsina

**Comment by gupta-abhi** [comment]
Hi @realityking ,

I can't confirm but yes it seems so. Also, kindly note that we had used `httpsAgent` parameter while creating the Contentful client (Although we are using the *http* proxy).

Kind Regards,
Abhishek Gupta

**Comment by axe312ger** [comment]
@gupta-abhi yeah, I guess this is the solution. A co-worker pointed out that you might need to use the `httpsAgent` with `HttpsProxyAgent` but pass your `http://...` url into.

Not really intuitive but that's because our API is https secured and your proxy is running on http.

Best,
Benedikt

**Comment by rnarsinaLilly** [comment]
Thank you Abhi and Benedikt, Finally Hurray ☺

This is the one works for me –

const client = contentful.createClient({
 // This is the space ID. A space is like a project folder in Contentful terms
  space: SPACE_ID,
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: ACCESS_TOKEN,
  httpsAgent: new HttpsProxyAgent('http://foo:bar@XXXXXXXXXXXXXXX:9000')
})

And I am using Contentful@5.1.3<mailto:Contentful@5.1.3>, some reason 4.3.0 didn’t work for me ☺

Best Regards,
Raj Narsina
