### ISSUE TITLE
vulnerable dependency (axios 1.6.8) - need to update axios to 1.7.4 (released on 13.08.2024)

### ISSUE THREAD

**Issue by Marujah** [contentful/contentful.js#2303]
## Expected Behavior

When starting a dependency check pipeline job for a project, we realized that axios 1.6.8 is vulnerable with a high severity (https://github.com/axios/axios/issues/6463).
Axios released 1.7.4 yesterday with a fix for this.

## Possible Solution
upgrade the dependency Axios to 1.7.4

**Comment by simon141** [comment]
Also failing our checks. Running `npm audit fix --force` recommends downgrading the contentful package in the meantime.

**Comment by guillaume-moreau** [comment]
Will the fix be also pushed on v9 ?
We're still using to keep support of Safari 12.

**Comment by t-col** [comment]
Thank you for reporting. The axios dependency is bumped to 1.7.4 in contentful.js versions 10.13.3 & 9.3.7

**Comment by Marujah** [comment]
@t-col , thousand Thx!!!
