### ISSUE TITLE
Retried requests duplicate query parameters resulting in 400 response 

### ISSUE THREAD

**Issue by guillaume-moreau** [contentful/contentful.js#2314]
Hello !

Sorry, I didn't succeed in reproducing the issue, so I can only give you assumptions.

We got error loging on our apps with Sentry; recently we saw new errors popping on Contentful requests:

This seems to start with an unsuccessful request (probably because of API rate limit, or network issue)
![image](https://github.com/user-attachments/assets/aaac2b6f-d709-40cb-903b-feedce5ce425)

Then followed with a request on Contentful with query params duplicated, resulting in a htpp 400 error.

While browsing in your repo I saw this issue : https://github.com/contentful/contentful.js/issues/2246
This was caused by an Axios update to v1.7.

Recently, Axios version in this project was updated to v1.7 because of a CVE; see : https://github.com/contentful/contentful.js/issues/2303

On our side it also seems that this issue appears since an update on Axios.

**Comment by jjolton-contentful** [comment]
Hey @guillaume-moreau thanks for reporting, this has been resolved in [v10.11.11](https://github.com/contentful/contentful.js/compare/v10.11.10...v10.11.11) so I'll go ahead and close this issue, please feel free to reopen if you are still having any problems, and see https://github.com/contentful/contentful.js/issues/2246 for more details.

**Comment by guillaume-moreau** [comment]
Hi ! 

Thank you for your answer !

Yeah it was fixed with v10.11.11.
Maybe I'm wrong but I think that v10.13.3 and the update of Axios to v1.7 bring back the bug.
