### ISSUE TITLE
contentful 5.1.2 + babel-polyfill = Refused to set unsafe header "user-agent", "Accept-Encoding"

### ISSUE THREAD

**Issue by antokara** [contentful/contentful.js#232]
* **Node Version**: v8.9.4
* **Npm Version**: 5.6.0
* **Platform**: Linux computer 4.15.3-300.fc27.x86_64 #1 SMP Tue Feb 13 17:02:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* **Package Version**: contentful@5.1.2
* **Browser**: Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)

This change that was introduced to "simplify node detection":
https://github.com/contentful/contentful-sdk-core/pull/48/files#diff-6cc946b8c61ada93f3727db8d3ef52bdR86
appears to have created a problem, where the **create-http-client.js** thinks it is running as a node.js process and thus, tries to set the **user-agent** and **Accept-Encoding** headers, which in turn throws warnings in the console of the browser...

The problem happens on projects that use
https://babeljs.io/docs/usage/polyfill/
which sets a global **process** variable (process.browser === true)

so this function
```
export function isNode() {
  return typeof process !== 'undefined';
}
```
returns true where previously, it returned false in the same setup...

**Comment by axe312ger** [comment]
This should be fixed with the freshly released `v5.1.3` :)
