### ISSUE TITLE
Release notes for v11

### ISSUE THREAD

**Issue by alvarlagerlof** [contentful/contentful.js#2334]
## Expected Behavior

Major versions have releases and release notes in https://github.com/contentful/contentful.js/releases

## Actual Behavior

No releases notes (as far as I can find) for v11, which makes upgrading hard.

**Comment by axe312ger** [comment]
Preparing them right now, for now, here is my draft for the release notes:

* No internal logic was changed. If you get the new imports working, all your other code should be able to stay untouched.
* We now provide real ESM by default, while also providing CJS variants for older environments
  * This was tested in 22 browsers/devices, AngularJS, GatsbyJS, NextJS, NextJS + TS, Node (with and without TS, with CJS and MJS files), Nuxt, React Native (Expo), Rollup, Svelte, Vite, Vite + TS, Webpack
  *To support all these environments, we define our package type in package.json via the "type": "module" with the regular main field and as well support the new  exports field.
* We no more provide pre bundles code for nodejs (removes eval from our exported code)
* Improved tree shaking support (finally)
* Reduced browser bundles sizes almost by factor 3 (128kb -> 45kb)
* Reworked our internal test environment from jest to vitest
