### ISSUE TITLE
Proper way of returning an image? 

### ISSUE THREAD

**Issue by thebetterjort** [contentful/contentful.js#237]
I posted my issue here at Stack. [here](https://stackoverflow.com/questions/49002238/getting-image-url-using-contentful)

I'm very confused on how to return an image. I'm unable to follow the documentation. I'm sorry, I typically try until I cry. 

Thank you for any help.

**Comment by axe312ger** [comment]
Just access it within the SDK result like we do here for example:
https://github.com/contentful/the-example-app.nodejs/blob/master/views/mixins/_lessonModuleImage.pug#L5

There is no difference in accessing any of the Contenful properties compared to normal arrays and objects.

Best,
Benedikt

**Comment by thebetterjort** [comment]
undefined if i put in the ListView. Hmm -- I need more debugging tools.

**Comment by thebetterjort** [comment]
Looks like an issue with the data not getting to the client and React Native over reacted. No pun intended.

```
    if (this.state.dataSource)
      console.log(
        this.state.dataSource.fields.featuredImage[0].fields.file.url
      );

```
Thanks.

**Comment by thebetterjort** [comment]
```    if (this.state.dataSource)      console.log(        this.state.dataSource.fields.featuredImage[0].fields.file.url      );```

**Comment by thebetterjort** [comment]
```    if (this.state.dataSource)      console.log(        this.state.dataSource.fields.featuredImage[0].fields.file.url      );```
