### ISSUE TITLE
Calling getEntries right after a webook publish event doesn't always fetch the updated content

### ISSUE THREAD

**Issue by tleunen** [contentful/contentful.js#245]
* **Node Version**: 8.11.1
* **Npm Version**: 5.6.0
* **Platform**: MacOS 10.13.4
* **Package Version**: 6.1.0

I'm using the webhook system to know when an entry has been published in my space. The webhook works fine and I'm getting the event on my server. But then, when I get the event, I'm calling `getEntries` to fetch the data related to my entry and all the links, and most of the time, the data I get is the old data, not the new one.
I've found out that if I wait at least 20 seconds before calling `getEntries`, it will work fine and I'll receive my updated data.

Any reason why calling `getEntries` when receiving the webhook result in out of date data?

The issue is particularly present when, on the webhook event, I need to fetch the parents entries (using `links_to_entry`, and finally calling `getEntries` on the final entries id. So the flow might be like this:
1) Receive webhook publish event
2) Calling `getEntries` with `links_to_entry` equals to the webhook entry id.
3) Potentially calling 2) multiple times
4) Once I have the entries I need, I'm calling `getEntries` again, but this time with `include` and `sys.id` set to what I need.
5) Notice that the result of 4) is not the updated content, but the old one. [Unless I wait 20 seconds before doing 4)]

**Comment by Khaledgarbaya** [comment]
Hi @tleunen,
The data needs a little bit of time to be propagated through the CDN, one solution to this could be adding a delay before getting the data. You can also get the newly published entry in the wehbhook payload.

**Comment by tleunen** [comment]
Yeah.. but 20 seconds seems to be quite long :/ Would it be able to have a way or webhook when we're sure the data is propagated everywhere?

About the data in the payload, the problem is that most of the time, I don't need that specific data alone, but the entire hierarchy.
If I have an entry (A), which references another entry (B) which references (C), when I update (C), I actually need to fetch (A). But the webhook doesn't give me that. It only gives me (C). And same thing if I update (A), I need the full tree, not (A) alone. And the webhook always gives only the direct entry that has been updated.

**Comment by ilkka** [comment]
@tleunen we had the same problem, which we mitigated by using webhook calls to trigger calls to the sync API instead. This seems to work and our pipeline is nice and snappy.

**Comment by axe312ger** [comment]
So we got 2 solutions here to workaround. Closing this for now :)

**Comment by tleunen** [comment]
@ilkka Do you mean that the sync api doesn't have the same limitations than the delivery api (waiting x seconds for the changes to be propagated)?

**Comment by ilkka** [comment]
Won't start a long discussion here, but @tleunen the method I described works for us with immediate updates, so no waiting for a sync. The downside is that we end up essentially maintaining a content cache (a microservice that does a full sync on boot and then incremental updates), but it lets us do our own tricks with how we resolve content for our UIs while still being able to use contentful's tools for managing it.
