### ISSUE TITLE
Some page links are broken

### ISSUE THREAD

**Issue by ricardograca** [contentful/contentful.js#259]
## Expected Behavior

Clicking on the "Advanced Concepts" file link in the [documentation's home page](http://contentful.github.io/contentful.js/contentful/6.1.2/) should open the relevant page. 

## Actual Behavior

It returns a 404 error.

## Steps to Reproduce

1. Go to the docs Home page: http://contentful.github.io/contentful.js/contentful/6.1.2/
2. Scroll down to the "Advanced Concepts" section
3. Click on the link to the `ADVANCED.md` file
4. The `MIGRATION.md` file has the same problem

I should also note that none of the same page element anchor tags seem to be working. Example: http://contentful.github.io/contentful.js/contentful/6.1.2/#configuration

**Comment by helloroman** [comment]
Hey i would love to tackle this one – let me know if you still need help with it.

**Comment by Khaledgarbaya** [comment]
Hey @ricardograca and @helloroman this is because the link is relative to github. To solve this we can have maybe full URL or we include the `Advanced.md` in the [jsdoc](https://github.com/contentful/contentful.js/blob/master/jsdoc.json#L8) files as we do with the README.
