### ISSUE TITLE
Automatically build dist before publishing to npm

### ISSUE THREAD

**Issue by johanneswuerbach** [contentful/contentful.js#26]
npm has the `prepublish` hook, which allows to execute a command before publishing. We should use that to keep dist automatically in sync.

**Comment by grncdr** [comment]
This is not actually solving much, because bower (which is the only thing using the `dist` directory) doesn't actually look at the registry.

**Comment by trodrigues** [comment]
@grncdr but if you have it as a prepublish hook, it means that we wouldn't forget rebuilding those files when we actually publish, so we'd just perform the two actions with one command. Otherwise we'd have to remember to perform the two actions, which seems to be what's happened so far.
