### ISSUE TITLE
NPM install contentful but show error 404 Not Found: @contentful/axios@^0.18.0

### ISSUE THREAD

**Issue by sithuhlaing** [contentful/contentful.js#264]
I clean up with npm cache. I install again still error.

**Comment by axe312ger** [comment]
A `npm i @contentful/axios@^0.18.0` works fine for me, also is working for a lot of other peoples.

The issue must be your npm cache, proxy or connection 😅

**Comment by PLaRoche** [comment]
I'm having the same issue, any suggestions?

**Comment by axe312ger** [comment]
Alright, let us dig deeper :)

Can you please provide the following information:

* Your node version
* Your npm version
* Your operating system
* Are you behind a proxy in your network?
* Did you modify your npm registry? (If you don't know what this is, probably not)
* Your install command plus the complete output.

Thanks 🙇

**Comment by PLaRoche** [comment]
Sovled, and will share it was non obvious but easy
- remove node modules folder
- remove package-lock.json

Then do npm install/ etc from scratch.  Fixed for me at least

**Comment by Khaledgarbaya** [comment]
Glad it worked
