### ISSUE TITLE
Add option to disable link resolving

### ISSUE THREAD

**Issue by ehd** [contentful/contentful.js#27]
Hey,

I wonder if it would be possible to add an option to disable the automatic resolving of links in query responses. I'm doing post-processing on query response data and the circular references are making recursive traversal hard because it's easy to run into loops. It also means that responses from the client can never be JSON stringified. The optional flag could look like this in the current API:

``` js
client.entries({
  foo: 'bar',
  include: 3,
  resolveLinks: false // Resolve links to actual objects? (new, defaults to true)
}).then(function(enries) {
  console.log(entries); // Entries without resolved links
  console.log(entries.includes); // Includes from query response
});
```

Alternatively the option could be passed per client when creating it.

More background:

- Post processing that's happening is flattening of fields and removing of dead links
- Circular traversal can be difficult to handle. Having to keep track of cycles by mutating or in a map is not ideal. Would rather not have cycles in the data structure

What do you think?

**Comment by sdepold** [comment]
this makes a lot of sense, imho. we could also use this in the api console. @madtrick ?

**Comment by trodrigues** [comment]
This was actually fixed some versions ago.
