### ISSUE TITLE
Why include custom axios?

### ISSUE THREAD

**Issue by bayssmekanique** [contentful/contentful.js#273]
## Expected Behavior

Contentful SDK should use the main `axios` repo.

## Actual Behavior

Contentful is using an older forked version of `axios` with a few tweeks for `https` over `http` proxy.  This is causing anyone using `axios` anywhere else on their site to either use the older `@contentful/axios` fork or ship their customers an extra `~30kB` of almost identical code because of 6 lines of code change.
https://github.com/axios/axios/compare/master...contentful:master 

I believe this was the original issue: https://github.com/contentful/contentful.js/issues/116

And here were comments on the latest related commit: https://github.com/contentful/contentful.js/commit/f640b0140ee021d3a3756ce5a08aeaa21384bbd5

## Possible Solution

There appears to be a PR on the main Axios branch which would resolve this issue: https://github.com/axios/axios/pull/1673

If this PR is not merged soon, however, it might be better to build an adapter as previously discussed on the initial commit.

**Comment by axe312ger** [comment]
We are aware of this but we had to use our custom version since a required proxy patch was not merged/released to Axios for 12 months or more.

We are currently testing latest Axios beta which now contains our PR with the proxy patch.

--> https://github.com/contentful/contentful-management.js/pull/187

**Comment by axe312ger** [comment]
I just released `7.1.0-beta0` which contains the latest community Axios beta. Install via `npm i contentful@next`

Can you please give feedback if it solves your issue and works fine with your project?

Thanks a lot,
Benedikt

**Comment by bayssmekanique** [comment]
@axe312ger, this resolves the issue for me and works well.  Many thanks!
