### ISSUE TITLE
Fields exclusion from entry

### ISSUE THREAD

**Issue by Xaz16** [contentful/contentful.js#279]
Hi guys

Do we have any way to exclude some fields from entry without creating and splitting to new references?
I found this way, but as I understand it's only for fields content and it exclude whole entry:
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/exclusion
And as well we have this query: 
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator
But I think I need something opposed to this one.

**Comment by Xaz16** [comment]
@Khaledgarbaya 
Sure, thank you. But I want exclude some fields rather than select.
I have situation like this. I have big Content Model with a lots of fields, but not all I need to retrieve in request... And it is more simply exclude list of them rather than select each one.

**Comment by Khaledgarbaya** [comment]
Hey @Xaz16,
That's not possible unfortunately

**Comment by Xaz16** [comment]
@Khaledgarbaya 
Thank you anyway. I will try to find another solution.

**Comment by tsaulon** [comment]
> Hey @Xaz16,
> If I understand correctly you want to get only a few fields you need from the entry.
> for that, you can use the select operator which is the second link.
> Here is a link to a snippet that you can use https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator/query-entries/console/js

@Khaledgarbaya Are we able to use the select operator for properties retrieved from an entry's reference as well? In the context of `.getEntries({ . . . })`

**Comment by Khaledgarbaya** [comment]
@tsaulon Yes
