### ISSUE TITLE
Mapbox account over limit

### ISSUE THREAD

**Issue by TStrothjohann** [contentful/contentful.js#28]
Hey,

just wanted to let you know that your mapbox account is over limit. Hence, the ufo sightings example lacks a map...

```{
message: "Account over limit."
}```

**Comment by grncdr** [comment]
Thanks for reporting this! Unfortunately we will likely remove this example, since it seems to depend on an individual account that isn't actually managed by Contentful.

/cc @ehd

**Comment by grncdr** [comment]
Chatted a bit with @ehd offline, seems we _could_ replace mapbox with Google maps and maintain the same functionality. Unfortunately I can't give any ETA on when we will get around to this.
