### ISSUE TITLE
TypeError: instance.defaults.logHandler is not a function

### ISSUE THREAD

**Issue by colin-johnson** [contentful/contentful.js#282]
## Context
We have a project built on Next.js, React.js and Contentful. 

We gather all our Contentful data before page build so data is ready. During Contentful requests, we hit rate limits, which is expected, but the API is supposed to wait until it's ready and continue fetching data when it is. 

However, instead of logging the warning and waiting as it is supposed to. We consistently get this error:

TypeError: instance.defaults.logHandler is not a function
    at /node_modules/contentful/dist/contentful.node.js:2590:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

The logHandler is not referenced or instantiated correctly, so it errors thinking it isn't a function. 

When I comment out this line, 2590,  in contentful.node.js

// instance.defaults.logHandler('warning', retryErrorType + ' error occurred. Waiting for ' + wait + ' ms before retrying...');

the API works as expected, waiting x amount of milliseconds before trying API request again, and correctly pulls in all our data.

This specifically happens in the Preview API, that we can see. The Delivery API seems to fetch all the data and persists even if we hit the rate limit.

This is preventing us from correctly using the Preview API in any environment that isn't local.

-   **Language Version**: node v8.2.1
-   **Package Manager Version**: npm 6.1.0
-   **Browser Version**: Chrome
-   **Operating System**: Mac OS
-   **Package Version**: 7.0.4
-   **Which API are you using?**: Happens in Preview specifically

**Comment by Khaledgarbaya** [comment]
Hi @colin-johnson,

Can you provide a small snippet on how you are creating the client?
Are you overriding the `logHandler`in the client options?

**Comment by colin-johnson** [comment]
@Khaledgarbaya Thanks for your response. We actually were, and I was unaware of it. Thank you for your response which led us to the solution. Appreciate it!
