### ISSUE TITLE
Preview API with createClient

### ISSUE THREAD

**Issue by nataliawww** [contentful/contentful.js#287]
Wondering if there is a way to configure `defaultHostname` from cdn.contentful.com to preview.contentful.com and be able to test the preview API key as the `accessToken`?

**Comment by Khaledgarbaya** [comment]
you can change the host as mentioned [here](https://github.com/contentful/contentful.js#using-this-sdk-with-the-preview-api)

```js
const contentful = require("contentful");
const client = contentful.createClient({
  space: "developer_bookshelf",
  accessToken: "preview_0b7f6x59a0",
  host: "preview.contentful.com" // host
});
```

**Comment by marcolink** [comment]
Closing this issue for now since it's open for a long time with no reaction.

**Comment by xzhub** [comment]
Can't believe in the official document (https://www.contentful.com/developers/docs/tutorials/general/content-preview/#preview-content-in-your-online-environment), it didn't say anything about the host parameter!
![image](https://user-images.githubusercontent.com/3990687/87727326-5bd6b700-c7f3-11ea-85d6-2b6ba3e31cd8.png)
