### ISSUE TITLE
sync resolveLinks options bug

### ISSUE THREAD

**Issue by NoahHahm** [contentful/contentful.js#288]
## Expected Behavior

For sync, the resolveLinks option applies only on the first (initial = true) call,
Afterwards (initial = false), resolveLinks does not apply for sync.

## Actual Behavior

initial = flase,
resolveLinks = true
In the option, the entry and asset data comes in the form of a link.

## Possible Solution

resolveLinks should work fine even in the initial = false state.

## Steps to Reproduce

`const contentful = require('contentful')

const client = contentful.createClient({
  space: '<space_id>',
  accessToken: '<content_delivery_api_key>'
})

client.sync({
  initial: false,
  resolveLinks: true
})
.then((response) => console.log({
  entries: response.entries,
  assets: response.assets,
  nextSyncToken: response.nextSyncToken
}))
.catch(console.error)`

OUTPUT
`{
    "_id": {
        "$oid": "5becf5a5a16cdd74bf6c4e1d"
    },
    "fields": {
        "development": {
            "en": [
                {
                    "sys": {
                        "type": "Link",
                        "linkType": "Entry",
                        "id": "2zWM0bR44IWmWSYCmC664s"
                    }
                }
            ]
        }
    },
    "sys": {
        "space": {
            "sys": {
                "type": "Link",
                "linkType": "Space",
                "id": "ttn7jks47ozr"
            }
        },
        "id": "3eGnB4QJagukcqswmUIWug",
        "type": "Entry",
        "createdAt": "2018-11-14T13:26:40.047Z",
        "updatedAt": "2018-11-15T04:28:48.910Z",
        "environment": {
            "sys": {
                "id": "master",
                "type": "Link",
                "linkType": "Environment"
            }
        },
        "revision": {
            "$numberInt": "6"
        },
        "contentType": {
            "sys": {
                "type": "Link",
                "linkType": "ContentType",
                "id": "contentOrderingTest"
            }
        }
    }
}`

## Context

This is to prevent unnecessary Link API calls by sinking the data.

## Environment

-   **Language Version**: node 9
-   **Package Manager Version**: npm
-   **Browser Version**: 
-   **Operating System**: mac
-   **Package Version**: latast
-   **Which API are you using?**: Delivery

**Comment by Khaledgarbaya** [comment]
Hi @NoahHahm,
the link resolution is only possible on initial sync because in subsequent syncs there is not enough data to do the link resolution.
