### ISSUE TITLE
Cannot Render the content by using Angular7 SSR 

### ISSUE THREAD

**Issue by glorment** [contentful/contentful.js#289]
After using Angular7 SSR , I click the browser and View the page source . Cannot show the value get from the contentful . 

## Expected Behavior
Click the view page source at the browser. It should show all the value that receive from contentful

## Actual Behavior
All the value from contentful at the **page source** is empty

## Steps to Reproduce

1.
2.
3.
4.

## Environment
Angular 7 . Angular universal 

-   **Language Version**: V10.4.1
-   **Package Manager Version**: 6.4.1 
-   **Browser Version**: Version 70.0.3538.102 (Official Build) (64-bit)
-   **Operating System**: Mac OS 10.14
-   **Package Version**: v7.0.5
-   **Which API are you using?**: Delivery

**Comment by patrickhousley** [comment]
Maintainers, can you please expose the Axios adapter config option? This will allow Angular developers to write a custom adapter for Axios based on Angular's HttpClient. This will allow us to use SSR with contentful in the Angular platform. At some point, a nice developer might even publish an axios angular adapter :).

Example using just plain Axios that worked is below. Should be fine for contentful.

```
@Injectable({
  providedIn: 'root',
})
export class HomeContentAdapterService {
  constructor(private readonly httpClient: HttpClient) {}

  getAdapter(): AxiosAdapter {
    return (config: AxiosRequestConfig): Promise<any> => {
      const { auth, headers, data, params } = config;

      if (auth) {
        const username = auth.username || '';
        const password = auth.password || '';
        headers.Authorization = 'Basic ' + btoa(username + ':' + password);
      }

      const request = this.httpClient.request(
        config.method.toUpperCase(),
        config.url,
        {
          body: data,
          headers,
          params,
          withCredentials: !!auth,
          reportProgress: true,
          observe: 'response'
        }
      );

      return request.toPromise().then((response: HttpResponse<any>) => {
        return {
          data: response.body,
          // IE sends 1223 instead of 204 (https://github.com/axios/axios/issues/201)
          status: response.status,
          statusText: response.statusText,
          headers: response.headers,
          config: config,
          request
        };
      });
    };
  }
}

@Injectable({
  providedIn: 'root',
})
export class HomeContentResolverService implements Resolve<any> {
  constructor(private readonly adapter: HomeContentAdapterService) {}

  async resolve() {
    const response = await axios.get('https://jsonplaceholder.typicode.com/todos/1', {
      adapter: this.adapter.getAdapter()
    });

    return response.data;
  }
}
```

**Comment by patrickhousley** [comment]
The basic adapter is available at https://www.npmjs.com/package/@ngx-axios-adapter/core

**Comment by r3plica** [comment]
I have tried this and it doesn't work. Now I just get 404 errors and looking in the network tab, it's actually trying to call from the localhost instead of contentfuls API url

**Comment by marcolink** [comment]
@r3plica 
You should be able to define your custom (angular) axios adapter when creating the contentful client. ([see here](https://github.com/contentful/contentful.js/blob/master/ADVANCED.md#angular-universal))
