### ISSUE TITLE
Javascript SDK crashing in electron window

### ISSUE THREAD

**Issue by ba4z** [contentful/contentful.js#290]
## Expected Behavior
To connect to Contentful using the SDK and perform a query.

## Actual Behavior
As soon as the client is instantiated like this:
```
const breedLibraryClient = createClient({
    space: <space-id>,
    accessToken: <access-token>
});
```

It results in the following error (from the minified code):
```
main.392e6e54098a29879fdf.js:1 ERROR TypeError: Object(...) is not a function
    at main.392e6e54098a29879fdf.js:1
    at main.392e6e54098a29879fdf.js:1
    at Xb (main.392e6e54098a29879fdf.js:1)
    at new t (main.392e6e54098a29879fdf.js:1)
    at factory (main.392e6e54098a29879fdf.js:1)
    at main.392e6e54098a29879fdf.js:1
    at Hr (main.392e6e54098a29879fdf.js:1)
    at Br (main.392e6e54098a29879fdf.js:1)
   at t.get (main.392e6e54098a29879fdf.js:1)
    at Io (main.392e6e54098a29879fdf.js:1)
ge @ main.392e6e54098a29879fdf.js:1
```
Which boils down to this line:
```var t = Object(Ab.platform)() || "linux"```

## Possible Solution
I've worked around this issue by going straight to the api instead of using the SDK.
It looks like the sdk is trying to determine what platform it's on such as nodejs, or a browser and electron is not a part of those checks, so it crashes.

## Steps to Reproduce

1. Setup any electron app ([like this one](https://github.com/electron/electron-quick-start))
2. Open window inside electron app that loads a url that uses contentful javascript sdk

## Context
When the app loads it tries to load content from contentful to display in the app. Since the client creation doesnt work, the app breaks on startup.

## Environment
The environment is an electron app that opens a new window inside the app to load a remote url that uses the contentful javascript sdk.

-   **Language Version**: 9.8.0
-   **Package Manager Version**: 5.6.0
-   **Electron Version**: 1.6.2 and 3.0.8 
-   **Operating System**: macOs Mojave 10.14.1
-   **Which API are you using?**: Delivery

**Comment by GunnarHolwerda** [comment]
I get this error as well in my Angular 7 application.
