### ISSUE TITLE
info request - more info on proximity search

### ISSUE THREAD

**Issue by openbook** [contentful/contentful.js#292]
Hi - I'm using the proximity / near search to create a paginated list of items ordered by their distance from a user entered search point.  

As far as I can tell, there is no way of retrieving the distance from the search point in the results returned by the API, so I'm using my own custom (although rather generic) haversine function to calculate this.  The problem with this is that my function doesn't return the same value used by the API, so the ordering on the front end is incorrect  i.e. i get a list containing items like:

item 1
distance 0.3 miles

item 2
distance 10.1 miles

item 3
distance 15.5 miles

item 4
distance 11.5 miles

Could you confirm, is there any way to have the API return a 'distance from' value when using a 'near' query?  Or, failing that, are you able to provide details on the calculation you use when ordering your 'near' query results so that it can be replicated in a function more accurately?

**Comment by Khaledgarbaya** [comment]
Hey @openbook,
Unfortunately not, the results will be sorted by the distance but the distance won't be there.

**Comment by openbook** [comment]
Ok.  In that case, would you be able to offer any advice with the second request -  can give details on the calculation you are using to sort by distance?
