### ISSUE TITLE
getEntries fails with limit above 278

### ISSUE THREAD

**Issue by ruanodendaal** [contentful/contentful.js#295]
## Expected Behavior

Calling
```
.getEntries({
      content_type: 'post',
      order: '-fields.reviewDate',
      limit: 1000,
    })
```

Should return up to 1000 posts in reverse order by review date.

## Actual Behavior

Passing any limit above 278 returns `Request failed with status code 400`.
Your documentation states that the limit is 1000, so no idea why this doesn't work anymore.

## Context

We have ~350 posts (and growing) that we're trying to fetch however can't. This implementation hasn't changed and has been working fine until I noticed it today.

## Environment

-   node: 8.11.4
-   npm: 6.4.1
-   contentful: 7.0.5
-   API:  Delivery

**Comment by Khaledgarbaya** [comment]
Hey @ruanodendaal,
What was the error message?

**Comment by ruanodendaal** [comment]
`Error: Request failed with status code 400`

**Comment by ruanodendaal** [comment]
I sent an email to support and in their response, they mentioned the maximum response size is 8mb so I might be hitting that.

So will paginate through the results.
