### ISSUE TITLE
Link Resolution doesn't work if select contains sys.id

### ISSUE THREAD

**Issue by erik-wendt** [contentful/contentful.js#296]
## Expected Behavior

I'm using the JavaScript SDK and try to "select" only some fields from the content entries and the ID of it, e.g. "select: 'sys.id,fields.route,fields.pages". 

The "field.pages" are links to other content entries and with param "include: 3" I expect to get the result with link resolution enabled. 

## Actual Behavior

If I'm Using "sys.id" in the "select" param the link resolution doesn't work anymore and I get the data without the related fields.

## Possible Solution

workaround: remove "sys.id" from the select param

## Example

I have a simple content model "page" which contains a field "route" and a field "pages" for linked entries of the same model. 

```
client
        .getEntries({
            content_type: 'page',
            // link resolution works! will contain all sys data
            //select: 'fields.route,fields.pages',
            // link resolution doesn't work. will contain sys.id only
            select: 'sys.id,fields.route,fields.pages',
            include: 3
        })
        .then((result) => result.items)
        .then((pages) => {
            pages.forEach((page) => console.log(page.sys, page.fields));
        })
        .catch(console.error)
```

## Environment

-   **Browser Version**: Chrome 70.0.3538.110
-   **Operating System**: macOS Serria
-   **Package Version**: v7.0.5
-   **Which API are you using?**: Delivery API

**Comment by erik-wendt** [comment]
BTW: it worked before SDK Version 5.1.0. If I'm using 5.0.5 I get the expected result.

**Comment by marcolink** [comment]
Hi @erik-wendt,

could you provide an actual and expected example result?

**Comment by erik-wendt** [comment]
Hi @marcolink,

I've tested it again for the new version "7.14.2" and it's still not working.

If I use this query the link resolution just works as expected

```
client.getEntries({
  content_type: 'page',
  // link resolution works! will contain all sys data
  select: 'fields.route,fields.pages',
  include: 3
})
``` 
and produces the following output:

![image](https://user-images.githubusercontent.com/7628803/78771393-61b93280-7990-11ea-990c-20dd1d226772.png)


But if i try to filter the "sys" object to get the ID only the link resolution is not working anymore
```
client.getEntries({
  content_type: 'page',
  // link resolution doesn't work. will contain sys.id only
  select: 'sys.id,fields.route,fields.pages',
  include: 3
})
```
![image](https://user-images.githubusercontent.com/7628803/78771352-536b1680-7990-11ea-977f-2ba0c1fe4a28.png)

**Comment by TimBeyer** [comment]
Could you try adding `sys.type` to the `select`?  
I believe the entity lookup is indexed by a combination of `type` and `id` since you could have an entry and an asset with the same ID in the includes. Since the link objects have the type, but the entity objects don't, it won't resolve the links.
The reason why it works without doing a select on `sys` is that the SDK implicitly requests the full `sys` object then to do link resolution.
