### ISSUE TITLE
Optional Headers on Requests

### ISSUE THREAD

**Issue by skorth** [contentful/contentful.js#30]
Hey there, i want to add my own Caching layer. To archieve this i need to set header information like ETag/If-None-Match. Is there a good way to still use [this](https://github.com/contentful/contentful.js/blob/fad36516f754460f7432021bf003f65ac701c80a/index.js#L25), but to add optional header params without a monkey patch or something like that? Also [this](https://github.com/contentful/contentful.js/blob/fad36516f754460f7432021bf003f65ac701c80a/index.js#L42-L49) Part is a problem i think. I need the response header information and not just the data itself. Any idea?

**Comment by sdepold** [comment]
I think it's not possible at the moment but a pull request would be very welcome :)

**Comment by trodrigues** [comment]
This is now possible with 3.x

**Comment by ilkka** [comment]
How does this work with 3.x? Can't find any examples. I see I can pass headers when I create the client, but is the idea to always create a new client for each request?

**Comment by Khaledgarbaya** [comment]
Hi @ilkka,
You can pass headers when creating the client. You can use the same client for making multiple requests.

```js
var contentful = require('contentful')
var client = contentful.createClient({space:'SPACE_ID, accessToken:'ACCESS_TOKEN', 'headers:{'key': 'value'. 'key1':'value2'}})

// make requests with the client 
//e.g
client.getEntries()
  .then((entryCollection) => {
    console.log(entryCollection.items)
  })

client.getEntry('ENTRY_ID').then((entry) => console.clog(entry))
```

**Comment by ilkka** [comment]
Yeah, that is what I meant: if I know that the `Etag` for some resource `res` is `abcd`, I have to create a new client if I want to check if my cached resource is out of date:

```
contentful.createClient({... headers: { 'If-None-Match': 'abcd' }}).getEntries() ...
```

**Comment by Khaledgarbaya** [comment]
Hi @ilkka ,
Can you give me more details about the caching layer you have. is it a layer between the SDK and Contentful ?
I want to understand exactly the use case so maybe there is a better way of doing it.

**Comment by ilkka** [comment]
I have an app that generates content from templates + user data. The templates are stored in Contentful. I want to be able to use a locally cached version of a template, if that template has not been updated in Contentful. To achieve this, I was thinking I could just rely on the `Etag`s Contentful returns.

**Comment by Khaledgarbaya** [comment]
@ilkka ,
You can achieve that using the [sync](https://contentful.github.io/contentful.js/contentful/3.8.0/ContentfulClientAPI.html#.sync) realy easily and each time you sync you will get a syncToken, you can store it and use with the next sync so the server will return only the changed items.
If you want to automate this you can use [webhooks](https://www.contentful.com/developers/docs/concepts/webhooks/) to trigger a ci build for your app.

e.g code for the sync
```js
client.sync()
.then((response) => console.log(response.entries, response.assets, response.nextSyncToken))
```

**Comment by ilkka** [comment]
Okay, thanks! I did see something about sync when reading through the code, I'll take a look at it. Also thanks for linking to the JS API docs, I have somehow entirely missed those.

**Comment by Khaledgarbaya** [comment]
Cool, let me know if you know any more help. Feel free to create any issues in that regard
