### ISSUE TITLE
createClient requires API key nuxt issue

### ISSUE THREAD

**Issue by patrickblackjr** [contentful/contentful.js#312]
https://codesandbox.io/s/github/emeraldcoasthub/gulfcoastimmediatecare.com

I'm trying to get the blog function to generate correctly.

I have this in my nuxt.config.js and it's giving me this error when I try and generate: `TypeError: Expected parameter accessToken`. Any ideas as to why?

```js
generate: {
    routes: () => {
      const client = contentful.createClient({
        space: process.env.CTF_SPACE_ID,
        accessToken: process.env.CTF_CD_ACCESS_TOKEN
      });

      return client.getEntries({
        content_type: 'blogPost'
      }).then((response) => {
        return response.items.map(entry => {
          return {
            route: entry.fields.slug,
            payload: entry
          };
        });
      });
    }
  },
```

**Comment by patrickblackjr** [comment]
Why is it complaining that `.getEntries` requires an access token when I have provided one?

**Comment by phoebeschmidt** [comment]
Hi @patrickblackjr, are you sure you are setting your environment variables correctly? The env variables should be set in `nuxt.config.js`. 

Perhaps this blog post would be helpful: https://www.contentful.com/developers/docs/javascript/tutorials/integrate-contentful-with-vue-and-nuxt/
