### ISSUE TITLE
getEntry specify locale

### ISSUE THREAD

**Issue by Kinark** [contentful/contentful.js#316]
It's a simple issue. Idk if this is a feature request, but you can't specify the locale when executing `contentfulClient.getEntry('entry_id')`.

I' ve tried something like this: `contentfulClient.getEntry({ entry_id: match.params.id, locale: context.locale })` but no success.

What can I do to fetch an entry in another locale?

**Comment by phoebeschmidt** [comment]
Hi @Kinark, sorry this isn't better documented. 

You send the locale as part of the query object, like this: 
`client.getEntry('m8lVPmkODym9g4lRCSs3f', {locale: 'en-AU'}).then(console.log)`

Every method takes a query object. Usually it's the first and only arg for the collection methods, or the second arg for the non-collection methods. This information is all available in the sdk documentation: https://contentful.github.io/contentful.js/contentful/7.4.3/ContentfulClientAPI.html

**Comment by Kinark** [comment]
It shouldIt should be documented in here, shouldn't it?
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/entries/entry/get-a-single-entry/console/js

In the code example it should be like:
```js
const contentful = require('contentful')

const client = contentful.createClient({
  space: '<space_id>',
  environment: '<environment_id>', // defaults to 'master' if not set
  accessToken: '<content_delivery_api_key>'
})

client.getEntry('<entry_id>, [queryObject]') // <<<< Here
.then((entry) => console.log(entry))
.catch(console.error)
```

**Comment by phoebeschmidt** [comment]
@Kinark thanks for finding this shortcoming in our docs. If you see something you'd like improved, I'm happy to review a PR :)
