### ISSUE TITLE
when querying using links_to_entry you are not able to use Order

### ISSUE THREAD

**Issue by adamrogas** [contentful/contentful.js#317]
## Expected Behavior

```Javascript
client.getEntries({
                    "links_to_entry": locals.data.tag,
                    skip: 0, limit: 10, order: '-fields.published'
})
```

This should return an ordered result but it returns empty result.

## Possible Solution

```Javascript
client.getEntries({
                    "links_to_entry": locals.data.tag,
                    skip: 0, limit: 10
})
```

This however returns a full result.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

-   **Language Version**: v10.15.3
-   **Package Manager Version**: 
-   **Browser Version**: 
-   **Operating System**: Windows 64 
-   **Package Version**: 5.4.2
-   **Which API are you using?**: Delivery

**Comment by Khaledgarbaya** [comment]
Hey @adamrogas,
Thanks for reporting this. What's the type of `fields.published` ?

**Comment by adamrogas** [comment]
fields.published is date and when doing a normal query without links_to_entry it returns a full data set.

**Comment by marcolink** [comment]
Closing this for now as there hasn't been any activity in a while and we assume
you were able to solve it at hand.

But feel free to reach out again if you have more questions.
