### ISSUE TITLE
CORS issue with getEntry in Chrome

### ISSUE THREAD

**Issue by dgoerdes** [contentful/contentful.js#319]
## Expected Behavior

`client.getEntry('<entry_id>')` should return the desired entry.

## Actual Behavior

The request results in a CORS error.

> Access to XMLHttpRequest at 'https://cdn.contentful.com/spaces/<SPACE_ID>/environments/master/entries/?sys.id=<ENTRIY_ID>' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

## Possible Solution

Seems like the problem is related to the URL used to get the entry from the API.
As `https://cdn.contentful.com/spaces/<SPACE_ID>/environments/master/entries/?sys.id=<ENTRIY_ID>` has a prefilight request which responds with the status `307 Internal Redirect` it violates the CORS policy.

A possible solution would be to use the following URL instead:
`https://cdn.contentful.com/spaces/<SPACE_ID>/environments/master/entries/<ENTRIY_ID>`

## Environment

-   **Browser Version**: Chrome 74.0.3729.131 (64-Bit)
-   **Package Version**: 7.5.1
-   **Which API are you using?**: Delivery

**Comment by Khaledgarbaya** [comment]
Hey @dgoerdes,
This is the first time I see this issue.
I'll look into it and get back to you but I am not aware of any redirect

**Comment by Khaledgarbaya** [comment]
Hey @dgoerdes,
I could not reproduce your issue, this could be a CDN hiccup or probably a proxy setting.
Please let me know if you still have the issue

**Comment by dgoerdes** [comment]
Hey @Khaledgarbaya,
I also can not reproduce it anymore now. As instantly the issue occurred, it was gone.
Thanks anyway!

**Comment by Ancinek** [comment]
I still have this happening, but it's hard to catch – as @dgoerdes stated, it appears and then it's gone. This is the error in the browser (Firefox):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.contentful.com/spaces/my_space_id/environments/master/entries?locale=pl&content_type=post. (Reason: CORS request did not succeed).
```

**Comment by ahopkins94** [comment]
Hi I am also having this issue but for `getEntries` also from a localhost request. It does not seem to be disappearing though so any help would be greatly appreciated

**Comment by Ancinek** [comment]
@ahopkins94 I managed to resolve it (fully and reliably) only by creating an under the same domain that accesses the contentful, instead of accessing it directly from the browser.

**Comment by ahopkins94** [comment]
@Ancinek what was it you created under the same domain exactly?
