### ISSUE TITLE
Link/Asset resolving issues

### ISSUE THREAD

**Issue by trodrigues** [contentful/contentful.js#32]
Link and asset resolving do not always work properly.

**Comment by tomxor** [comment]
Also, one has to transform:

~~~javascript
client.entry('foo')
~~~

into:

~~~javascript
client.entries({'sys.id': 'foo'})
~~~

In order to have any included links in the response/result object, other SDKs transparently use the latter for single resource requests.

**Comment by slang800** [comment]
I ran into this same issue with nested content. Setting `include=10` in the HTTP API querystring seems to fix it. I'm not sure if this is the same issue you're describing, @trodrigues. But it's worth noting because it used to work a few months ago, and without any code changes or warnings from the library, it stopped working.

**Comment by moreguppy** [comment]
I have also run into this problem, but have also found inconsistencies between contentful spaces.

So I am using this demo as a working example of data being returned with resolved asset links: https://github.com/contentful/cdn-webinar-store-demo

In the app.js, I have thrown in this to log the response:

```
client.entries().then(function (entries) {
  console.log(entries);
});
```

and the demo returns the entries with resolved assets; works perfectly.

Now I have a space set up with my contentful account with entries that have similar data (title, image, description), and all I replace in the demo is the authentication details. But the response I get for this doesn't return links with assets.

**Comment by trodrigues** [comment]
Hi @moreguppy, a couple of questions:

- Are you using entries() or entry() ? Links should only be resolved on collection methods like entries().
- Are the assets published? The asset links will only be resolved if the asset is published.

**Comment by moreguppy** [comment]
Problem solved, turns out the assets were not published. Was pointed in the right direction by the support@contentful.com team.

@trodrigues I was using entries.

**Comment by trodrigues** [comment]
Right, it's what I thought :) At the moment we don't have a right answer to prevent these kinds of issues but as this has happened multiple times, the product team is aware of this and they'll come up with a solution to improve the UI and/or publishing process to avoid these situations.

**Comment by trodrigues** [comment]
As for the initial issue that was opened here, link resolution is only available on collection endpoints, therefore on `entries()` and not on `entry()`.

**Comment by tucq88** [comment]
@trodrigues This should be included in [official doc](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items) as well :( 
Current causes confusion that I could use `include` for query single entry

**Comment by axe312ger** [comment]
@tucq88 this is included in the readme: https://github.com/contentful/contentful.js#link-resolution

The official doc you linked is the endpoint documentation of the API. This is not related to the link resolving feature of the JavaScript CDA SDK :)

**Comment by forwardadvance** [comment]
I'm curious as to why links cannot be resolved on getEntry, but only on the collection? It would certainly be useful to be able to get linked content for a show page with a single http request.

**Comment by Khaledgarbaya** [comment]
@forwardadvance when requesting an entry using the single entity endpoint we don't receive the data necessary to resolve the links, mainly the `includes`, in that situation resolving the links will require additional request which is counted toward the usage limit and that is something we are trying to avoid
