### ISSUE TITLE
Feed synced data to client on restart

### ISSUE THREAD

**Issue by matejkramny** [contentful/contentful.js#320]
Hi,

If I'm understanding the sync feature correctly, it downloads the data from contentful and then uses the local data to resolve content/links without hitting your api.

Upon restart / refresh of the app the content would need downloading again since contentful doesn't store this data anywhere.
What's the purpose then of giving us the next sync token etc?

There is no way I can see we can implement a storage mechanism behind the sync feature. We would like to store the sync data to then restore it if the user restarted the app/website.

Please correct this if i'm misunderstanding the sync feature.

Cheers!

**Comment by walpolea** [comment]
You can do the intial sync of all of the data and have your app to store it locally, in something like indexed DB or localstorage (on the web) or other device storage systems for mobile apps. Then the next time the user comes back, you won't have to do the intial sync again, you can just provide the sync token and you'll only get the adds, edits, and deletes that happened while the user was away, which you can then use to update that local storage mechanism you saved it all in.

**Comment by matejkramny** [comment]
Thanks @walpolea. I get the part with the next sync token, however not clear which API could be used to feed the contentful client with the saved data.

- to get sync content (https://contentful.github.io/contentful.js/contentful/7.6.0/ContentfulClientAPI.html#.sync)
- resolve the links (https://contentful.github.io/contentful.js/contentful/7.6.0/ContentfulClientAPI.html#.parseEntries)

Looking at the SDK, it's not clear how to give contentful the `SyncCollection` in the next start.

It seems to be detailed in the iOS Swift SDK (https://www.contentful.com/developers/docs/ios/tutorials/offline-persistence-in-ios-sdk/) but no such API exists for the JS SDK?

Thanks!

**Comment by walpolea** [comment]
Ahh, correct, the js sdk just interfaces the API for you to do the initial and subsequent syncs. It's up to you to implement how you store, access and update the data locally. For example, I've used localforage and dexie has solutions for this. Once you have the data you don't have to give it back to the contentful sdk.

**Comment by matejkramny** [comment]
Oh, cool. Thanks a lot!

One more question please. How do you query the cached data, such as when using `getEntries`, `getEntry` etc?
Things like sort, filtering by content type and linked content wouldn't be available or have to be written by ourselves.

**Comment by walpolea** [comment]
Right, you have to implement it yourself, or use a library that has some query capabilities built in. With indexed db, that usually looks like making index tables, where you have the contentful field value that you want to search be the key, and the entry ID(s) as the value(s) at that key. I believe dexiejs has this built in, you just tell it which object fields you want to index.

**Comment by matejkramny** [comment]
Inspecting the network panel it seems the sdk fetches data from the api anyway rather than using the sync data..
It might be caching repeat queries but it's not really 'offline'.

Thanks again

Matej
