### ISSUE TITLE
Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by gagle** [contentful/contentful.js#323]
When creating a client I get this error:

```
ERROR TypeError: Cannot read property 'node' of undefined
    at getNodeVersion (utils.js:12)
    at createHttpClient (create-http-client.js:108)
    at createClient (contentful.js:72)
```

That's because `process` exists but process.browser does NOT exist, therefore `utils.isNode()` returns true and then it calls `utils.getNodeVersion()` and crashes because `process.versions` does NOT exist.

```
console.log(process)

logs

{
  env: {
    DEBUG: undefined
  },
  version: "1"
}
```

## Environment

Angular v7.2.15

**Comment by gagle** [comment]
Just close and ignore this. Sorry

**Comment by gayathrirajendran** [comment]
@gagle am facing the same issue, how did you get out of this ?
