### ISSUE TITLE
Fetch support

### ISSUE THREAD

**Issue by MatteoGioioso** [contentful/contentful.js#324]
If I am not mistaken your library is using `axios` is it possible to have support for `fetch` API?

Thanks

**Comment by Khaledgarbaya** [comment]
Hey @MatteoGioioso,
any reason you want to use fetch instead of axios?

**Comment by MatteoGioioso** [comment]
@Khaledgarbaya I think it might be better for `service worker` support

**Comment by MickL** [comment]
@Khaledgarbaya I am not able to use `contentful.js` on a Cloudflare worker since it uses axios. Axios does not work there and `fetch()` must be used instead.

**Comment by jeniamoroz** [comment]
@Khaledgarbaya 
`axios` support doesn't look too good (I would even say quite bad), despite it being "all-time awesome library".
This has been raised by many people externally and as issue on `axios` issue page, see following https://github.com/axios/axios/issues/1965.

Of course there are alternatives like https://github.com/googleapis/gaxios, but that just takes focus away from root problem:
- `contentful.js` library should not force to use one and only http library but rather suggest it and provide API to inject custom http library, either it's `fetch`, `axios`, `gaxios` or whatever will become popular in 2020.
- `axios` not being maintained/supported - yields more and more security issues overtime
Please consider this as a fair warning and reasonable concern.
Thank you!

**Comment by mendrik** [comment]
in general there should be a way to customize which library one wants to use. some simple adapter for each library can be easily written, I for one would love to get it working with https://github.com/sindresorhus/got

**Comment by wangzuo** [comment]
I also prefer `fetch` since its implemented in web, worker and deno.

**Comment by MickL** [comment]
I agree to @mendrik that contentful.js should use adapters. Axios should be one adapter and part of a separate package, then other adapters for fetch, or other http-clients, could easily be written.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.

**Comment by brunocordioli072** [comment]
For those with this issue, a solution:

```js
import { AxiosAdapter, AxiosResponse, AxiosResponseHeaders } from 'axios'
import { createClient } from 'contentful'

const fetchAdapter: AxiosAdapter = async (config) => {
  const { url, method, headers, data, params } = config
  if (!url || !method) throw new Error('Error on fetching data')

  const fetchConfig = {
    method: method.toUpperCase(),
    headers: new Headers(headers),
    body: ['GET', 'HEAD'].includes(method.toUpperCase()) ? null : JSON.stringify(data),
  }

  const urlObject = new URL(url)
  if (params) urlObject.search = new URLSearchParams(params).toString()

  const response = await fetch(urlObject.toString(), fetchConfig)

  const responseData = await response.json()

  const axiosResponse: AxiosResponse = {
    data: responseData,
    status: response.status,
    statusText: response.statusText,
    headers: response.headers as unknown as AxiosResponseHeaders,
    config,
    request: fetchConfig,
  }

  return axiosResponse
}

const client =  createClient({
  ...
  adapter: fetchAdapter
}) 

```

**Comment by brunocordioli072** [comment]
For those with this issue, a solution:

```js
import { AxiosAdapter, AxiosResponse, AxiosResponseHeaders } from 'axios'
import { createClient } from 'contentful'

const fetchAdapter: AxiosAdapter = async (config) => {
  const { url, method, headers, data, params } = config
  if (!url || !method) throw new Error('Error on fetching data')

  const fetchConfig = {
    method: method.toUpperCase(),
    headers: new Headers(headers),
    body: ['GET', 'HEAD'].includes(method.toUpperCase()) ? null : JSON.stringify(data),
  }

  const urlObject = new URL(url)
  if (params) urlObject.search = new URLSearchParams(params).toString()

  const response = await fetch(urlObject.toString(), fetchConfig)

  const responseData = await response.json()

  const axiosResponse: AxiosResponse = {
    data: responseData,
    status: response.status,
    statusText: response.statusText,
    headers: response.headers as unknown as AxiosResponseHeaders,
    config,
    request: fetchConfig,
  }

  return axiosResponse
}

const client =  createClient({
  ...
  adapter: fetchAdapter
}) 

```
I'm working on a project that uses Next.js v14, which basically requires the usage of fetch API to be able to handle caching on the application. That was the solution used to solve the problem.
