### ISSUE TITLE
post content to a content type from client side

### ISSUE THREAD

**Issue by shahzadhassan10** [contentful/contentful.js#331]
Is there any way to POST content to a content_type using the javascript SDK? I want to create records with couple of fields from client side. I can only see GET functions and no Post function in the documentation. An example for that would be great.

**Comment by phoebeschmidt** [comment]
Hi @shahzadhassan10,

This is just our SDK for the delivery API, which is read only. If you want to update content you should use our management API sdk, https://github.com/contentful/contentful-management.js.

Hope that helps!
