### ISSUE TITLE
When are we gonna get search queries on a multiple-reference field ?

### ISSUE THREAD

**Issue by JavRok** [contentful/contentful.js#333]
There's a need on my company (& the community) for this functionality, which is currently not available. Here's a discussion about it: 

https://www.contentfulcommunity.com/t/searching-on-multiple-reference-fields/377/10

## Expected Behavior

A simple use-case is Tags. Contentful doesn't have 'native' tags for articles. So we use an entity 'Tag' with just a keyword. In our case, an article can have several tags. I can search for an article that contains one tag, with &links_to_entry=[tagID]. But if I want to query with 2 or more tags, I get the error message "You are trying to search on a reference to an unsupported type. You can only search on references to single entries".

## Possible Solution

It would be awesome to have at least a query paramater called 'links_to_entries=[id1]OR[id2]...[idn]'. Of course having option to use both OR / AND would be optimal. 

Is this on your roadmap, or is a no-go for you guys?

Thanks !

## Steps to Reproduce

1.
2.
3.
4.

## Environment

-   **Language Version**: 
-   **Package Manager Version**: 
-   **Browser Version**: 
-   **Operating System**: 
-   **Package Version**: 
-   **Which API are you using?**:

**Comment by lmf-git** [comment]
Disappointing. How is this getting swept under the rug over and over again?

**Comment by marcolink** [comment]
Hi @JavRok,

Did you try out [tags](https://www.contentful.com/help/tags/) already?

**Comment by javier-eriks** [comment]
Hi, no I didn't, not sure if this was available when I posted this 2 years ago... 

I'm not working on Contenful anymore, but good to know, thanks. It seems this solves the problem specifically for Tags, since it says multiple tags can be used to filter, but this problem still exists for other custom entities, right? 

Cheers

**Comment by JavRok** [comment]
Hi, no I didn't, not sure if this was available when I posted this 2 years ago...

I'm not working on Contenful anymore, but good to know, thanks. It seems this solves the problem specifically for Tags, since it says multiple tags can be used to filter, but this problem still exists for other custom entities, right?

Cheers

**Comment by marcolink** [comment]
Closing this for now. 
If you have more feature requests, please post them in the [community slack](contentful-community.slack.com
) for visibility ✌️
