### ISSUE TITLE
JSON data is out of order

### ISSUE THREAD

**Issue by cinnamonkale** [contentful/contentful.js#334]
## Expected Behavior

My JSON field is structured like this in the Contentful JSON editor:

<img width="619" alt="Screen Shot 2019-08-01 at 3 00 05 PM" src="https://user-images.githubusercontent.com/6350880/62326423-a8ef3b00-b473-11e9-9523-5ce265ab9775.png">

where the order of the `data` key should be:

1. Payroll Issue
2. Relocation
3. Promotion
4. Leave of absence

## Actual Behavior

Looking at the raw response from Contentful, the items are out of order:

<img width="371" alt="Screen Shot 2019-08-01 at 15 43 15" src="https://user-images.githubusercontent.com/6350880/62326497-db993380-b473-11e9-8a24-be7aaa542221.png">

so now the actual order is:

1. Promotion
2. Relocation
3. Payroll Issue
4. Leave of absence

What's weird is the JSON returned in the HTTP response isn't alphabetical, so it's not an automatic ordering of object keys in the JSON object. It's being sent as raw data in the wrong order from Contentful

**Comment by alejandroiddev** [comment]
An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.

https://stackoverflow.com/questions/7214293/is-the-order-of-elements-in-a-json-list-preserved

**Comment by cinnamonkale** [comment]
Thanks for the link. We ended up using arrays to keep the insertion order:

```
{
    "data": [
        {
            "label": "Payroll issue",
            "values": [
                88
            ]
        },
        {
            "label": "Relocation",
            "values": [
                76
            ]
        },
        {
            "label": "Promotion",
            "values": [
                63
            ]
        },
        {
            "label": "Leave of absence",
            "values": [
                61
            ]
        }
    ]
}
```
