### ISSUE TITLE
Unable to retrieve correct results using "links_to_entry"

### ISSUE THREAD

**Issue by liamdanielduffy** [contentful/contentful.js#338]
Hi,

I have a content model with the following content models

Author (with content id “author”)
Article Category (with content id: "articleCategory)
Story (with content id: “story”)

Story contains the following fields:

author (single reference to “author” content)
article categories (multiple reference to “articleCategory” content)
Here is the problem I’m running into:

---

I have an author with id: “abc”
I have a category with id: “123”

I have multiple stories linked to the author with id “abc”
I have multiple stories linked to the category with id “123”

The following request returns a list of stories linked to the author with id “abc”

`contentful.getEntries({ content_type: “story”, links_to_entry: “abc” })`

The following request returns an empty list, even though I expect it to return all the stories linked to the category with id “123”

`contentful.getEntries({ content_type: “story”, links_to_entry: “123” })`

why doesn’t the second request return any stories? how can I retrieve all stories linked to category “123”?

**Comment by Khaledgarbaya** [comment]
Hey @liamdanielduffy,
What happens if you remove the `content_type: “story”` part?

**Comment by liamdanielduffy** [comment]
Hi @Khaledgarbaya 

This request returns all content entries linked to the category with id "123"
`contentful.getEntries({ links_to_entry: “123” })`

This request returns nothing
`contentful.getEntries({ content_type: "story", links_to_entry: “123” })`

The problem with the first request is that I have more than one type of content linked to the category with id "123". I need to only retrieve "story" type content linked to category with the id "123". Any reason why the second request wouldn't be working?

**Comment by Khaledgarbaya** [comment]
Hi @liamdanielduffy 
can you try `contentful.getEntries({ 'sys.contentType.sys.id': "story", links_to_entry: “123” })` ?

**Comment by liamdanielduffy** [comment]
Hi @Khaledgarbaya,

That works!

Would you mind explaining why the `sys.contentType.sys.id` was necessary, as opposed to `content_type `? or sharing documentation so I can better understand for the future?

Thanks so much for your help :)

**Comment by Khaledgarbaya** [comment]
Hi @liamdanielduffy The API cannot apply `content_type` query on the parent element, that's why we used `sys.contentType.sys.id` which is a normal search field.
In summary, we get all the parent entries and see if the field `sys.contentType.sys.id` matches `story` and return them.
