### ISSUE TITLE
Getting multiple content_types

### ISSUE THREAD

**Issue by cn-d** [contentful/contentful.js#341]
Is there a simple way using the Content Delivery API to multiple `content_types` when using `.getEntries()`? Currently, I'm getting both `content_type` by getting ALL entries and mapping the the ones I need.

```
const client = contentful.createClient(config)

return client
    .getEntries({
        content_type: 'blogPost' // I would like to get 'collections' here
    })
    .then(response => {
        const routes = ['404']

        response.items.forEach(entry => {
            routes.push('/blog/' + entry.fields.slug)
        })

        return routes
    })
```

**Comment by Khaledgarbaya** [comment]
Hi @cn-d 
you can try 
```
return client
    .getEntries({
        'sys.contentType.sys.id[in]': 'blogPost, author' // I would like to get 'collections' here
    })
```

**Comment by marcolink** [comment]
This issue has no reaction for some time. 
Will close it for now. Feel free to open it again.

**Comment by iAmServer** [comment]
> 'sys.contentType.sys.id[in]': 'blogPost, author'

This fails when I add filter by category ID

Ex.

` const getPostsByCategory = async (categoryId: string, limit: number = 10, skip: number = 0): any[] => {
    const entries = await client.getEntries({
      'sys.contentType.sys.id[in]': 'howToVideos,helpArticle',
      'fields.category.sys.id': categoryId,
      skip,
      limit,
    });

    if (!entries.items.length) {
      return [];
    }

    return entries.items;
  };`

throws

`
Uncaught (in promise) BadRequest: {
  "status": 400,
  "statusText": "",
  "message": "A Content Type ID is required. When querying for Entries and involving fields you need to limit your query to a specific Content Type. Please send a Content Type ID (not the name) as the URI query parameter \"content_type\"",
  "details": {},
  "request": {
    "url": "[https://cdn.contentful.com:443/spaces/oz8jheby8m1g/environments/master/entries](https://cdn.contentful.com/spaces/oz8jheby8m1g/environments/master/entries)",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.delivery.v1+json",
      "X-Contentful-User-Agent": "sdk [contentful.js/10.15.1](chrome://devtools/content/webconsole/contentful.js/10.15.1); platform browser; os macOS;",
      "Authorization": "Bearer ...3rZ6Q"
    },
    "method": "get"
  },
  "requestId": "f379f2cc-1e55-4795-b25a-434c2dff5e5d"
}
`
