### ISSUE TITLE
Error getspace with non master enviroment accessToken

### ISSUE THREAD

**Issue by PetroPavlenko** [contentful/contentful.js#344]
## Expected Behavior
My API key has access to QA environment only. But before initial request I would like to call `getSpace`. And received 404

## Actual Behavior, Possible Solution
Set space and environment

## Environment
QA

-   **Language Version**:  11*
-   **Operating System**: Ubuntu
-   **Package Version**: 2.1.47
-   **Which API are you using?**: Delivery / Preview

**Comment by nimajneb** [comment]
@Khaledgarbaya 
> Get space will try to get data about your master environment and since you didn't have access to it the API returns the error

Hi! I was just debugging the same problem before finding this issue.

If I understand the documentation at https://www.contentful.com/developers/docs/concepts/multiple-environments/ correctly, and a sandbox environment acts as kind of an override for specific space information, should `getSpace` then really get the data of the master environment's space?

Here's my code that failed:

```
const client = contentful.createClient({
  space: 'my-space-id',
  accessToken: 'my-access-token', // my-access-token does have access to test-environment, but not to master
  environment: 'test-environment',
});
try {
  const space = await client.getSpace();
} catch (e) {
  // ...
}
```

I'd expect `space` to contain the space information for the environment specified in `createClient`, but instead the `client.getSpace()` call actually throws an exception with a 404 error, just like mentioned by the OP.

This feels like a bug to me. Or do I misunderstand something here?

**Comment by Khaledgarbaya** [comment]
@nimajneb 
Every space has a master environment which is the actual space.
when you are requesting the space `spaces/spaceId/` that will get translated into `spaces/<spaceId>/environments/master`.
So if the API key is not allowed to access the master environment you won't be able to get the space information.

**Comment by PetroPavlenko** [comment]
Looks like that should be mention in docs. As I can do it with rest API.
And as @nimajneb posted logical code but it is failing
1. So If I create client with `environment: 'test-environment'`.
2. And `spaces/spaceId/` that will get translated into `spaces/<spaceId>/environments/master`. But should be translated to `spaces/<spaceId>/environments/test-environment` acording configuration

**Comment by Khaledgarbaya** [comment]
@petermakowski 
>And spaces/spaceId/ that will get translated into spaces/<spaceId>/environments/master. But should be translated to spaces/<spaceId>/environments/test-environment acording to configuration

`spaces/<spaceId>` is always pointing to `spaces/<spaceId>/environments/master` that's the main space what @nimajneb facing is that their API key is only set to work with `test-environment`

Here's some more Infos:
- https://www.contentful.com/developers/docs/concepts/multiple-environments/

**Comment by nimajneb** [comment]
@Khaledgarbaya Thank you for looking into this. I understand and I can also confirm that everything works when granting the API key access to the master environment.

Here's some background: In our project, we're consuming the Contentful API with the gatsby-source-contentful plugin. When fetching the content, the plugin uses `getSpace()`, probably to get some metadata from it. However, if the configured API key does not have access to the master space, an exception is thrown, which essentially breaks the build.

As it might not always be desirable to grant certain API keys access to the master environment, even during development, I think I should maybe report this in the gatsby project and see if there's some solution, even if it's only a note in the docs.

**Comment by Khaledgarbaya** [comment]
Hey @nimajneb I think the gatsby plugin should start using the `environment.getLocales()` instead of `client.getSpace()` to get the default locale.
I'll try to make a PR for that whenever I find time.

**Comment by nalgritz** [comment]
Hello all, I'm developing gatsby in accessing multiple contentful environements. Does anyone have update on it?

**Comment by designly1** [comment]
I'm trying to implement signed requests using the CMA adapter and it seems to generate this URL: https://api.contentful.com/spaces/fhn6yihuk8lh/environments/master/app_installations/6yl5Imq9FDfhtUqLPgUznr/signed_requests, which returns 404. Everything works fine in dev mode but when I deploy to master I get this error.
