### ISSUE TITLE
Data structure - Delivery API vs. Gatsby API

### ISSUE THREAD

**Issue by kompounder** [contentful/contentful.js#346]
Hi,

I am using Contentful with Gatsby and am looking to serve both statically & dynamically.

The static content is generated via the gatsby-source-contentful plugin from Contentful (with Graphql), while the dynamic content is sourced via the Contentful Delivery API.

For Rich Text, however, I am finding that there are some differences in the data structure:
- For data sourced via the Gatsby plugin, I am finding that all the rich text nodes usually require me to specify the locale (e.g. node.data.target.fields.url["en-US"]), while the regular API does not (e.g. node.data.target.fields.url).

Is there an easy way for me to make the data outputs consistent across these two APIs? There are some other minor differences as well (e.g. for long texts).

Thank you

**Comment by Khaledgarbaya** [comment]
Hi @kompounder,
When requesting the entries you can add `locale: *` query Example:
`client.getEntries({locale: '*'})`

**Comment by marcolink** [comment]
With no action for some months i will close this issue now. Feel free to reopen it.
