### ISSUE TITLE
About retryLimit

### ISSUE THREAD

**Issue by hikarut** [contentful/contentful.js#347]
Hello

I always use contentful.
Thank you very much.

With recent updates
I understand that I can use `retry` as an argument.
https://github.com/contentful/contentful.js/pull/340

However, when you look at the code, it is added to the documentation,
I don't think that `retry` can be set as an argument in the actual code.
https://github.com/contentful/contentful.js/blob/master/index.d.ts#L15-L34

Is it correct?

Thank you.

**Comment by lucaziz** [comment]
is type missing? 

Looks like interface CreateClientParams is missing retryLimit.

**Comment by ruderngespra** [comment]
Thank you! I added the missing type declaration.
