### ISSUE TITLE
Order By Sub Object value

### ISSUE THREAD

**Issue by olivinesguerra** [contentful/contentful.js#348]
Hello guys,

Is it possible to query entries via order from the sub object fields?

For example: 

let contentFullParams = {
  skip: params.skip, 
  limit: params.limit,
  "content_type":"home",
  **order:"fields.ageCategory.fields.value",**
  // order:"-sys.createdAt",
  select:"sys.id,fields"
};
const data = await client.getEntries(contentFullParams)
					.then(entries => {
						return this.processData(entries,ctx);
					})
					.catch(err => console.log(err));

Thanks,

**Comment by jroehl** [comment]
Hi, what exactly do you mean by `sub object fields`? You can only sort on the content field types mentioned [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/order). It is not possible to set `order` for `object` type fields..

**Comment by marcolink** [comment]
@olivinesguerra 

i will close this issue now. Feel free to open it again.
