### ISSUE TITLE
Sys interface in typings is missing revision property

### ISSUE THREAD

**Issue by jugglingthebits** [contentful/contentful.js#351]
The typings are missing the property `revision`, which is a `number` when an entry is published, and `undefined` when it is not.

https://github.com/contentful/contentful.js/blob/559733a47b2dcf8918f46c15f7d10ae366f09e49/index.d.ts#L135-L144

This should be changed so that the typings contain the `revision` property.

**Comment by digitalgravy** [comment]
It also seems to be missing the `createdBy` property?
