### ISSUE TITLE
getEntry() without specifying entry id argument returns latest Entry

### ISSUE THREAD

**Issue by noorhammad** [contentful/contentful.js#352]
#  Expected Behavior

When calling `getEntry()` _without_ specifying an entry id as an argument, there should be an error returned.

## Actual Behavior

The latest (most recently created) Entry is returned.

## Steps to Reproduce

```
<script src="https://cdn.jsdelivr.net/npm/contentful@latest/dist/contentful.browser.min.js"></script>
<script>
const client = contentful.createClient({
    space: "<space-id>",
    accessToken: "<access-token>",
    host: "cdn.contentful.com"
});

client.getEntry()
    .then((entry) => {
        console.log(entry)
        // Output is an Object of the most recently created Entry
    })
    .catch(console.error)
</script>
```

**Comment by marcolink** [comment]
@noorhammad 
what is the version of `contentful.js`  you're referring to?

A quick tests returns an `The resource could not be found.` Error for me.

**Comment by marcolink** [comment]
@noorhammad 

The provided example returns  `Error: The resource could not be found.` for me. 

I will close this issue now. Feel free to open it again.
