### ISSUE TITLE
Updating entries with an api call

### ISSUE THREAD

**Issue by tzookb** [contentful/contentful.js#353]
## Expected Behavior

being able to update an entry after fetching it with `client.getEntries`

## Actual Behavior

I get "update" undefined error

## Steps to Reproduce

1. using the javascript sdk package
2. using the snippet code:
```javascript
client.getEntries({content_type: 'product'})
.then(function (entries) {
  entries.items[0].update({.....})
})
```

## Context

I want to use the api, to update contenful items.

## Environment

-   **Language Version**: v8.12.0
-   **Package Manager Version**: 6.8.0
-   **Package Version**: "contentful": "^7.10.0",
-   **Which API are you using?**: Delivery / Management / Preview (not sure, still confused with them)

**Comment by mxmtsk** [comment]
The Delivery API is read only. Can't you use the the Content Management API for it?

[Contentful Management API on GitHub](https://github.com/contentful/contentful-management.js)

**Comment by phoebeschmidt** [comment]
Exactly-- this is the delivery SDK, which uses the delivery API. If you need to update entries, you should use our contentful-management SDK, which uses the management API (Linked above).

Here's the management SDK: https://github.com/contentful/contentful-management.js
