### ISSUE TITLE
Formatting data for react native

### ISSUE THREAD

**Issue by austinthetaco** [contentful/contentful.js#354]
I'm trying to load rich text into a react-native application, but the data isn't in an easily digestible format. At the very least if it was a string i could use an html-react-native-renderer. Is there any common practice or library used to convert the typical contentful rich text structure (body.content[0].content[0].marks etc etc) to a more normalized html or jsx structure?

**Comment by phoebeschmidt** [comment]
Hey @austinthetaco,

excellent question! We do have a series of tools that help with rendering contentful rich text entries: https://github.com/contentful/rich-text

Probably the react-renderer is the one you're looking for. Hope this helps!

**Comment by austinthetaco** [comment]
@phoebeschmidt unfortunately that renderer won’t work for react native, as react native doesn’t support a lot of normal html elements. Is there some way that I can get the rich text as just one string of html that I can run through my own custom renderer?

**Comment by phoebeschmidt** [comment]
@austinthetaco for the react renderer (and the html renderer) you can pass custom renderers as functions for different types of rich text nodes (Blocks, Nodes, or Embedded Elements.) You can read more about the different types here: https://www.npmjs.com/package/@contentful/rich-text-types. There's an example of how to do this in both the react renderer and the html renderer packages in the repo I linked above.

Or you can check out the html or plain text renderer, maybe those will give you output you prefer for your custom renderer. Does this help?
