### ISSUE TITLE
Response config can be undefined

### ISSUE THREAD

**Issue by JackCA** [contentful/contentful.js#357]
## Expected Behavior

The client should not always [expect a request to be attached to an error](https://github.com/contentful/contentful.js/blob/17b19a34ebb743cde08ea4bdd66aae45ddfe8f94/lib/contentful.js#L101).

## Actual Behavior

When the browser enters an offline state, the code linked above will trigger a `Cannot read property 'config' of undefined` error because when the browser is offline, you won't have access to a response object.

## Possible Solution

add `error.response !== unedefined && error.response.config.headers.Authorization`

## Steps to Reproduce

1. Turn on offline mode in chrome 
2. Trigger a conentful request
3. You

## Context

I'm seeing this error in my error tracker. Users will clearly have other issues if their browser enters offline mode after a request is made, but it'd be nice to 

## Environment

-   **Browser Version**: 
-   **Package Version**: contentful@7.11.0
-   **Which API are you using?**: Delivery

**Comment by MickL** [comment]
I get `Cannot read property 'config' of undefined` even it is an error with axios which does not work within a Cloudflare Worker

**Comment by JackCA** [comment]
Awesome 👏
