### ISSUE TITLE
The package at "node_modules\contentful\dist\contentful.node.js" attempted to import the Node standard library module "assert".

### ISSUE THREAD

**Issue by mtalhadev** [contentful/contentful.js#361]
I have been using contentful for the reactjs, it was working completely fine, but i just tried to use it on react-native app and having issues with it. It shows me this error 

> The package at "node_modules\contentful\dist\contentful.node.js" attempted to import the Node standard library module "assert". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

I have searched everywhere for the solution but nothing seems to work for me. 
My dependencies are following:
`"dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "contentful": "^7.11.3",
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-image-overlay": "^0.1.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  }`

**Comment by mtalhadev** [comment]
```
var contentful = require('contentful');
const client = contentful.createClient({
    space: SPACE_ID,
    accessToken: ACCESS_TOKEN
})
```
I am simply importing it like this

**Comment by ryanhefner** [comment]
@mtalhadev If you change it to the following, it should fix your issue:

```js
const contentful = require('contentful/dist/contentful.browser.min.js');
```

Let me know if that does the trick or not.

**Comment by myhendry** [comment]
@ryanhefner i followed your import method. My expo app was able to build fine. However, when i go to the screen which is supposed to display my contentful assets, i get the following error

[Unhandled promise rejection: Error: You attempted to set the key `authorization` with the value `"Bearer...80PFc"` on an object that is meant to be immutable and has been frozen.]

```
  useEffect(() => {
    const client = contentful.createClient({
      space: "gadfgfgsfg",
      accessToken: "1gsfgfsgfsdgfsg"
    });

    client.getEntries({ content_type: "Listing" }).then(res => {
      console.log("res", res);
    });
  }, []);
```

**Comment by ryanhefner** [comment]
@myhendry Yeah, I ended up doing some more testing with the solution that I found/posted, but I ran into that same issue, too. Have been. trying to get my [`react-contentful`](https://github.com/ryanhefner/react-contentful) package to work nice in React Native/Expo, but so far I haven’t found the magic solution to get it to play well in RN. Please let me know if you end up finding a combination that works.

There is the UPDATED solution provided in this answer on SO, https://stackoverflow.com/questions/39961577/import-contentful-in-to-react-native/39966439#39966439, maybe the custom `adapter` will work for you. I tried it, and ran into an issue with `assert`.

**Comment by myhendry** [comment]
@ryanhefner Thanks for your sharing. So far, I haven't found a way. If we happen to come across any solution, shall post it here. Thanks :)

**Comment by nnabinh** [comment]
Hmm, I ended up creating my own simple http request. Take a look at my draft request implementation. In order to improve this, you can consider to create your own client. Reading the source code in this repo would help to do that.

```javascript
  axios
    .get(
      `https://cdn.contentful.com:443/spaces/${SPACE_ID}/entries?sys.id=${ENTRY_ID}`,
      {
        headers: {
          'Content-Type': 'application/vnd.contentful.delivery.v1+json',
          'X-Contentful-User-Agent':
            'contentful.js/0.0.0-determined-by-semantic-release',
          'Accept-Encoding': 'gzip',
          'user-agent': 'node.js/12',
          Authorization: `Bearer ${ACCESS_TOKEN}`,
        },
      }
    )
    .then((res: Object) => {
      console.log('result: ', res.data);
    })
```

Reach the code further here: 
https://github.com/contentful/contentful.js/blob/master/lib/contentful.js
https://github.com/contentful/contentful.js/blob/master/lib/create-contentful-api.js

**Comment by marcolink** [comment]
Hi @mtalhadev,

We have removed all native node dependencies. If this error occurs again, feel free to re-open this issue or open a new one.
