### ISSUE TITLE
Validations for single references are missing

### ISSUE THREAD

**Issue by nmain100** [contentful/contentful.js#369]
##  Expected Behavior

When querying for a content type, or all content types, I want to be able to see the validations, but they're missing for a references one field (references many are working).  For instance, when I use Chrome devtools to see what Contentful's own UI gets back from the Contentful API, I see this:

`https://api.contentful.com/spaces/<redacted>/content_types/testThingWillBeDeleted`

```
{
  "sys": {<redacted>},
  "displayField": null,
  "name": "TestThingWillBeDeleted",
  "description": "Do not use this!  It's going away.",
  "fields": [
    {
      "id": "oneRef",
      "name": "OneRef",
      "type": "Link",
      "localized": false,
      "required": true,
      "validations": [
        {
          "linkContentType": [
            "block"
          ]
        }
      ],
      "disabled": false,
      "omitted": false,
      "linkType": "Entry"
    },
    {
      "id": "manyRef",
      "name": "ManyRef",
      "type": "Array",
      "localized": false,
      "required": true,
      "validations": [],
      "disabled": false,
      "omitted": false,
      "items": {
        "type": "Link",
        "validations": [
          {
            "linkContentType": [
              "block"
            ]
          }
        ],
        "linkType": "Entry"
      }
    }
  ]
}
```

## Actual Behavior

But when I use the contentful SDK to make the same query, the validations on the references one field are missing:

`await contentfulClient.getContentType("testThingWillBeDeleted")`

```
{
	"sys": {<redacted>},
	"displayField": null,
	"name": "TestThingWillBeDeleted",
	"description": "Do not use this!  It's going away.",
	"fields": [{
		"id": "oneRef",
		"name": "OneRef",
		"type": "Link",
		"localized": false,
		"required": true,
		"disabled": false,
		"omitted": false,
		"linkType": "Entry"
	}, {
		"id": "manyRef",
		"name": "ManyRef",
		"type": "Array",
		"localized": false,
		"required": true,
		"disabled": false,
		"omitted": false,
		"items": {
			"type": "Link",
			"validations": [{
				"linkContentType": ["block"]
			}],
			"linkType": "Entry"
		}
	}]
}
```

## Steps to Reproduce

1. Create a content type with a references one field.  Give that field a validation of allowed content types.
2. Try to retrieve the content type through the SDK.
3. See that the validation is not present

## Context

I'm generating typescript types that describe the shape of my content, but I can't put the right type on references one fields.

## Environment

-   **Language Version**: 13.2.0
-   **Package Manager Version**: 6.13.1
-   **Operating System**: Darwin US-IT01070.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
-   **Package Version**: 7.13.1
-   **Which API are you using?**: Delivery

**Comment by phoebeschmidt** [comment]
Hi @nmain100,

The web app uses our management API, which has differently shaped responses compared to our delivery API. I agree it's strange that the delivery api only returns validations on one-to-many reference fields... but the responses I'm getting from querying the delivery API directly are consistent with the responses you included above. 

You might consider using the management API if these responses don't fit your needs.

**Comment by nmain100** [comment]
I see.  It's not an SDK bug then, so I'll close this ticket and follow up with support on the API bug.
