### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by Ancinek** [contentful/contentful.js#370]
## Expected Behavior
No CORS-related errors
## Actual Behavior
Today I've noticed that my blog (created with the use of Contentful) is empty. Console showed me those:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://cdn.contentful.com/spaces/my_space_id_here/environments/master/entries?locale=pl&content_type=post’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’)
```

Not sure why it happens. I have another app using Contentful and it works pretty well out there. The only difference is that I'm not using `https` there yet.

## Environment

-   **Language Version**:  11.14.0
-   **Package Manager Version**: 6.13.1
-   **Browser Version**: Firefox 72.0.2 (64-bit). Same thing happens on Chrome and Safari
-   **Operating System**: macOS Catalina 10.15.2 
-   **Package Version**: 7.13.1

**Comment by Ancinek** [comment]
Leaving this post here for other people who might encounter the same issue as I did.

This library was written with the use of `axios` for making the requests. The arguments of `createClient` method are passed down when creating `axios` client. Passing `withCredentials: false` solved the issue for me:

```
const client = createClient({
  ...myConfigHere,
  withCredentials: false,
});
```

**Comment by Ancinek** [comment]
I'm reopening this issue – I'm using contentful on 2 websites with the same configuration.
The first website is `https://onpills.co/pl/blog` – I'm getting `304` from the API and the blog posts are showing correctly.
The second website is `https://wallery.io/blog` – I was getting `304` until I tried to publish a new post today. The app is making an `OPTIONS` request and getting `204 No Content` along with this error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://cdn.contentful.com/spaces/w8o3nz1i5dvw/environments/master/entries?locale=pl&content_type=post’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.contentful.com/spaces/w8o3nz1i5dvw/environments/master/entries?locale=pl&content_type=post. (Reason: CORS request did not succeed).
```

This is the request info:
![Screenshot 2020-03-13 at 17 52 38](https://user-images.githubusercontent.com/16444141/76642483-91247d00-6553-11ea-9dd1-5e686980173b.png)

Any idea why is this happening?

**Comment by Sebasarciga** [comment]
> Leaving this post here for other people who might encounter the same issue as I did.
> 
> This library was written with the use of `axios` for making the requests. The arguments of `createClient` method are passed down when creating `axios` client. Passing `withCredentials: false` solved the issue for me:
> 
> ```js
> const client = createClient({
>   ...myConfigHere,
>   withCredentials: false,
> });
> ```

This Solved it for me, adding "withCredentials: false" to my axios request
