### ISSUE TITLE
contentful.legacy.min.js not working on IE 11

### ISSUE THREAD

**Issue by kingeric027** [contentful/contentful.js#371]
## Expected Behavior
I am using the legacy contentful library described here https://contentful.github.io/contentful.js/contentful/6.1.0/

my script tag in my index html is 
`<script src='https://cdn.jsdelivr.net/npm/contentful@latest/dist/contentful.legacy.min.js'></script>`

I would expect this to work on IE 11:
"To support legacy browsers in your application, use contentful.legacy.min.js instead of contentful.browser.min.js"

## Actual Behavior

The app does not load on IE 11. I get this console error: 
SCRIPTING1006: Expected ')'
contentful.legacy.min.js (1,43092)

## Possible Solution
The piece of code that this is pointing at in the contentful.legacy.min.js is ...  function(e=null,t="")
I believe the problem is that IE 11 does not understand default function arguments 
more info: https://stackoverflow.com/questions/44732066/script1006-expected

## Environment

-   **Language Version**: v6.1.0
-   **Package Manager Version**: 3.8.6
-   **Browser Version**: IE 11.914
-   **Operating System**: 64 bit windows

**Comment by marcolink** [comment]
Thanks @kingeric027,

can you please try to pin the version to `7.12.1`:
`<script src='https://cdn.jsdelivr.net/npm/contentful@7.12.1/dist/contentful.legacy.min.js'></script>`

Please let me know if this solves the issue.
