### ISSUE TITLE
Confusing documentation.

### ISSUE THREAD

**Issue by codeviking** [contentful/contentful.js#376]
[This documentation](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/synchronization/pagination-and-subsequent-syncs) states:

> Note: The include parameter resolves links between entries and assets within a space. **Links between content types within a space are not included in the response.**

This is confusing, as it made us think we couldn't link from one content type to another.  That said links *are* resolved across content types in practice -- so these docs are likely wrong.

In our case we have three content types, `A` and `B` and `C`.  `A` has a reference to many instances of `B`, and each `B` references a `C`.  

When querying `A` we have to add the parameter `include: 2` in order to resolve the `C` reference for each `B`.  This ended up working out just fine.

The line referenced in the docs, however, made us think this wasn't even possible -- which was confusing.

Sorry, as I know this is about general documentation and not the Contentful JS API specifically -- that said I figured this was the most expedient way to route this to someone who could fix things.

**Comment by marcolink** [comment]
Hey @codeviking,
I just checked and it seems the doc have been updated!
Closing this for now.
