### ISSUE TITLE
Enable use of list-style-type in rich-text

### ISSUE THREAD

**Issue by cazroam** [contentful/contentful.js#385]
I want to be able to use multiple list styles in one component when using rich-text.
I also want to be able to have sub-lists/nested-lists.

## Expected Behavior
- Select the OL button and have a dropdown which allows me to select a `list-style-type`
- To be able to create a nested list

## Actual Behavior
- only numeric Ordered Lists are available
- I cannot create a nested-list

## Possible Solution
- Add a dropdown from the OL selection button which allows the user to apply a `list-style-type` to the list they are creating
- Add an button to create a nested list

## Steps to Reproduce
1. create a rich-text content type
2. add an OL `ordered-list`
3. try and make that list anything other than the default 1. 2. 3. format
4. not possible within Conetntful

## Context
This has caused me to apply the CSS of `list-style: none` to all of my `ol` (done in my IDE). I then have to manually write the list numbering/lettering that I want in the Contentful rich-text.
- example: 1. a). <text here>
My content looks messy and unformatted because of it.

## Environment

-   **Language Version**: v10.16.0
-   **Package Manager Version**: 6.9.0
-   **Browser Version**: Version 80.0.3987.149
-   **Operating System**: Darwin Kernel Version 18.7.0
-   **Package Version**: not sure
-   **Which API are you using?**: not sure

**Comment by phoebeschmidt** [comment]
Hi @cazroam! Your me-moji looks weirdly like my me-moji! :) hope that's not creepy hah. 

This is more of a feature request, not a bug or question about the JS delivery SDK. Do you mind emailing product-feedback@contentful.com or submitting a ticket here https://www.contentful.com/support/ ?

Thanks!
