### ISSUE TITLE
Querying field value with locale is causing strange results

### ISSUE THREAD

**Issue by mxmtsk** [contentful/contentful.js#386]
I don't think it is specifically an issue with the library but more with the API itself. Please let me know if I should raise this issue elsewhere.

## Expected Behavior

If you have two locales where one returns the other as default fallback(eg. `de-CH` returns `de` as default) value and you use `getEntries` to receive entries and filter by some fields I expect that the query is applied to the fallback values since no translation is present.

## Actual Behavior

For example: You have an entry with a boolean field `show_on_homepage`. The entry is not translated but the field is set to `true` in `de`.

Then you request the other locale like this:

```javascript
  const entries = await contentfulClient.getEntries({
    content_type: 'productPages',
    'fields.show_on_homepage': true,
    include: 10,
    locale: 'de-CH',
  });
```

The entry won't be in the response. If you remove the line `'fields.show_on_homepage': true,` it will be in the response and the field `show_on_homepage` is present in the response with the value `true`.

In my opinion this is wrong and I would expect a different result in the original query.

## Environment

-   **Language Version**: 12.13.1
-   **Package Manager Version**: 6.12.1
-   **Package Version**: 7.10.0
-   **Which API are you using?**: Delivery

**Comment by maxlew** [comment]
I just ran into this today, It looks like this is a limitation on the actual Contentful API not an issue with the javascript SDK. I haven't seen it mentioned in any documentation, but it seems like all field queries don't handle fallback locales at all.

**Comment by apopiidoru** [comment]
Any update on this?

**Comment by mayakarabula** [comment]
closing the issue, if you still need help with this please reach out to Contentful support
