### ISSUE TITLE
contentful.createClient() not working in 1.1.3 but is working in 1.1.1

### ISSUE THREAD

**Issue by mike-stumpf** [contentful/contentful.js#39]
Hello,

Using the same config and the same createClient function as is on the ReadMe, I get a valid access token when using 1.1.1 and an invalid access token in 1.1.3.  

Let me know if you need any more information.

Cheers,

Mike

**Comment by eschaefer** [comment]
+1

**Comment by trodrigues** [comment]
This issue appears to have never been properly addressed, and doesn't seem to still happen. I'm closing this for now but feel free to reopen if there are still issues.
