### ISSUE TITLE
Is there any way to fetch multiple entries in one request?

### ISSUE THREAD

**Issue by just4fun** [contentful/contentful.js#392]
Hi there,

Currently I'm fetching content by following code

```javascript
const entries = await client.getEntries({
  content_type: 'myProductName',
  locale: 'en-US'
});
```

Due to the limitation of 50 fields for content type, I created 2nd content type, and now I called above code two times with passing different content_type.

Is there any way to pass content_type as array? or am I using getEntries API in wrong way?

Thanks in advance.

**Comment by phoebeschmidt** [comment]
Hey @just4fun,

You'd have to use a query over the entries like this:

```
client.getEntries({
  'sys.contentType.sys.id[in]':'person,blogPost' //these are your two content types
})
.then(entries => console.log(entries.items))
```

Here's some docs for reference: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/inclusion/query-entries/console/js

Hope this helps :)

**Comment by just4fun** [comment]
@phoebeschmidt - That's what I need, thanks a lot. TBO, before I created this issue for the question, I checked that document, but didn't find it.
