### ISSUE TITLE
Provide more specific type for the fields of the Asset interface

### ISSUE THREAD

**Issue by wil93** [contentful/contentful.js#399]
Hello, I noticed that the `Asset` interface is defined as:

```
export interface Asset {
    sys: Sys;
    fields: {
        title: string;
        description: string;
        file: {
            url: string;
            details: {
                size: number;
                image?: {
                    width: number;
                    height: number;
                };
            };
            fileName: string;
            contentType: string;
        };
    };
    toPlainObject(): object;
}
```

My question is: would it be possible to also have a version of the Asset type that only specifies the content of `fields: {...}` ? (that is, title, description and so on).

Something like `AssetData`. If we had that, then the `Asset` type could be defined like:

```
type Asset = Entry<AssetData>;
```

The reason I'm asking for this is that I'm trying to write a generic function that wraps my type `T` with `Entry<T>`, but I can't use it with the `Asset` type because it already has the fields that would otherwise be added by `Entry<T>`

**Comment by marcolink** [comment]
Hi @wil93 

we have rewritten the whole project from scratch in typescript for better type support. 

You can check it out on [npm](https://www.npmjs.com/package/contentful) under the beta-v10 tag (go to the "Versions" tab to find it). The [migration guide](https://github.com/contentful/contentful.js/blob/beta-v10/MIGRATION.md#migration-to-contentfuljs-10x) and updated v10 [README](https://github.com/contentful/contentful.js/blob/beta-v10/README.md) and can be found on the [beta-v10 branch](https://github.com/contentful/contentful.js/tree/beta-v10). All details on the new Typescript features can be found [here](https://github.com/contentful/contentful.js/blob/beta-v10/TYPESCRIPT.md).
