### ISSUE TITLE
Nested References Query Failed to excecute

### ISSUE THREAD

**Issue by amaan-nadeem** [contentful/contentful.js#403]
## Description of issue
I have a content type of Coupon cards having a reference field of store and all the stores content type having the reference field of category. Don't know how to execute nested query to get all the coupon card related to specific category. 
flow of application is 
Coupon cards > its store > its category .

Here is the code snippet i used but it failed to excecute

`
const response = await client.getEntries({
        limit: 1,
        skip: skip,
        content_type: "couponCard",
        "fields.storeReference.sys.contentType.sys.id": "footlocker",
        "fields.storeReference.fields.categoryReference.sys.contentType.sys.id": "category",  
        "fields.storeReference.fields.categoryReference.fields.category[match]": categoryName,
        "fields.storeReference.fields.storeName[match]": stores[i],
      })
`

## Error
You can not search through nested reference fields

## Environment
Using Content delivery API

**Comment by mayakarabula** [comment]
closing the issue, if you still need help with this please reach out to Contentful support
