### ISSUE TITLE
A bug about Full-text search on a field

### ISSUE THREAD

**Issue by cityvoice** [contentful/contentful.js#405]
-   **Package Version**: 7.14.4
-   **Which API are you using?**: Delivery

Full-text search on a field only matches the fields which value start with query string, examplce code:

```
    client.getEntries(
      {
        'content_type': 'article',
        'fields.title[match]': 'contentful'
      })
```

It only matches the records like:

```
    {
        fields:{
          title:'contentful xxxxxx'
        }
    }
```

not:
```
    {
        fields:{
          title:'xxxxxx contentful xxxxxx'
        }
    }
```

just like match ^content.

**Comment by llwor94** [comment]
bump ^ same issue

**Comment by Cyberlane** [comment]
I had this exact same problem, so I opened a support ticket with the Contentful guys and they told me that it's a bug in their documentation. Their "full text search" is not "full text search".

In their own words it is "anchored search to the beginning of the string", or in more common terms "starts with, search".

**Comment by lmf-git** [comment]
Awful. This is a deal-breaker if you expect decent searching.

**Comment by mayakarabula** [comment]
closing the issue, if you still need help with this please reach out to Contentful support
