### ISSUE TITLE
Full lodash dependency when consumed as a module

### ISSUE THREAD

**Issue by JackCA** [contentful/contentful.js#408]
## Expected Behavior

When consuming this library as a `module`, the entire `lodash` library is included.

## Actual Behavior

The entire library is included because the module build does not get the advantages provided by the webpack/babel plugins in the non-module version.

I don't think you should expect end-users to subsequently use webpack/babel on their downstream package because they might not be using these libraries, and/or they're never going to notice that this dependency is being included.

## Possible Solution

You could:

1. Switch to [lodash-es](https://www.npmjs.com/package/lodash-es) and remove all of the code related to the babel/webpack plugins.
2. or use the [individual packages](https://www.npmjs.com/package/lodash.clonedeep)

## Steps to Reproduce

1. Create an ecmascript project that consumes `contentful`
2. Add webpack (in order to use [webpack bundle analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer))
3. analyze the bundle
4. Notice that `lodash` is included

## Context

Added ~ 24KB lodash library to payload

## Environment

-   **Language Version**: v12.16.1
-   **Package Manager Version**: yarn 1.22.4
-   **Browser Version**: n/a
-   **Operating System**: n/a
-   **Package Version**: 7.14.4
-   **Which API are you using?**: delivery

Application:
- next.js based

**Comment by devdpontes** [comment]
It's only being used for `cloneDeep `.
