### ISSUE TITLE
About the number that can be acquired by client.getEntries ()

### ISSUE THREAD

**Issue by naomei** [contentful/contentful.js#409]
The document states that the number of records that can be obtained with client.getEntries is 100 by default.
However, it seems that my application is currently able to obtain only 20 records.

Has it changed?

> By default you get 100 entries
https://www.contentful.com/developers/docs/javascript/tutorials/using-js-cda-sdk/

**Comment by marcolink** [comment]
Hi @naomei,
the default limit for entries on the delivery API is 100. You can change this behaviour be defining a `limit` parameter. 
On the management API, the default limit can vary based on the entity type. 

I will close this issue for now. Feel free to re-open it again.
