### ISSUE TITLE
Missing underscore/lodash dependency?

### ISSUE THREAD

**Issue by wmadden** [contentful/contentful.js#41]
Hi, I'm getting an error in `index.es5.js:391` because `_.isObject` is used but underscore/lodash is never imported.

I noticed you have a [recent commit](https://github.com/contentful/contentful.js/commit/6dfacee9348278e64132b6ec8cddb559b2ce68a3) called "removed lodash dependency" so it might have something to do with that.

**Comment by grncdr** [comment]
Hi @wmadden can you let me know what version of the library you're using? I made 2 releases that had the bug with lodash being used but not required. The most recent commit should fix that but hasn't been released to `npm` yet. If you could try installing from master for now (`npm install contentful/contentful.js`) that should fix it.

**Comment by wmadden** [comment]
Hey @grncdr, I was using 1.1.3 from NPM. I'll try reinstalling now.

**Comment by wmadden** [comment]
Hey @grncdr, I'm struggling with my webpack configuration at the moment but I'm not sure why:
```
ERROR in ./~/contentful/index.es6.js
Module parse failed: /Users/wmadden/Projects/klara/web-clients/node_modules/contentful/index.es6.js Line 3: Unexpected reserved word
You may need an appropriate loader to handle this file type.
| 'use strict';
|
| import axios from 'axios';
| import resolveResponse from 'contentful-resolve-response';
| import querystring from 'querystring';
 @ ./~/contentful/index.js 7:19-44
```

It's also worth noting that this line will never work: https://github.com/contentful/contentful.js/blob/master/index.js#L4

**Comment by wmadden** [comment]
I'm not sure why you're using `bable/register` but this page discourages it for libraries: https://babeljs.io/docs/usage/require/

**Comment by grncdr** [comment]
Hey Will,

The distributed `npm` packages will contain `index.es5.js` so the first require normally works; the `catch` block is intended only for local development use.

In any case, we've now released `v1.1.5` which has updated versions of all the compiled files and should work correctly. Can you give it a try?

**Comment by wmadden** [comment]
Hey @grncdr, importing and building works again, which is great.

Unfortunately, the Contentful ES6 module has no default export any more so `import contentful from 'contentful'` doesn't work, I need to change it to `import * as contentful from 'contentful'`.

**Comment by grncdr** [comment]
Ah yep, that would have been changed in the transition from ES5 to ES6. If you're using babel yourself it does some special things for making requires behave like the ES6 module spec. I've opened a new issue for that at #42
