### ISSUE TITLE
X-Contentful-User-Agent header broken

### ISSUE THREAD

**Issue by axe312ger** [contentful/contentful.js#412]
Just found this in an error message I got to debug for a CTF customer:

`"X-Contentful-User-Agent": "sdk contentful.js/0.0.0-determined-by-semantic-release; platform node.js/v12.16.0; os macOS/19.4.0;",`

Can you check if the user agent is sent correctly to the API? Probably version number is not overwritten by semantic release anymore.

Greets,
Benedikt

**Comment by marcolink** [comment]
Hi @axe312ger, 

Thanks for your sharp eye 🦅  and reporting this - We already double-checked with our latest version and it seems provided again. 🙌
