### ISSUE TITLE
Contentful Preview API wrongly includes `sys.locale` on response

### ISSUE THREAD

**Issue by eddyw** [contentful/contentful.js#413]
## Expected Behavior

**Contentful Preview API** should be consistent with **Contentful Delivery API** in that when making a query such as:
```javascript
    const response = await contentful.getEntries({
      content_type: 'navigation',
      locale: '*',
      include: 10,
      limit: 1,
    })
```
The entries shouldn't include `sys.locale`. This field shouldn't exist when query is all locales. This has been working fine all the time and we've noticed that preview breaks for us today because we rely on `sys.locale` to figure out the type of response (if fields are localized)

## Actual Behavior

The **Contentful Preview API** is including the `sys.locale` field when making a request with `locale: '*'`.
This is an example response's entry from **Contentful Preview API** with the above ☝️ query:
```javascript
{
  sys: {
    space: { sys: [Object] },
    type: 'Entry',
    id: '********',
    contentType: { sys: [Object] },
    revision: 26,
    createdAt: '2020-05-18T11:47:03.837Z',
    updatedAt: '2020-06-05T15:23:52.346Z',
    locale: 'en', // <<<<<<<<<< This shouldn't have been included (Delivery API doesn't include it)
    environment: { sys: [Object] }
  },
  fields: {
    title: { en: '*******' },
    navigation: { de: [Object], en: [Object], fr: [Object], nl: [Object] },
    footer: { de: [Object], en: [Object], fr: [Object], nl: [Object] }
  }
}
```

## Possible Solution

Remove the `sys.locale` from entries when request query includes all locales `locale: '*'` as it has been before .. today 🙈 (not sure exactly when this was introduced but it worked before today). Luckily, **Contentful Delivery API** wasn't broken so our site is still alive.

## Steps to Reproduce

1. Create a Contentful Model
2. Create a few fields and mark them as localized
3. Create an entry
4. Use Contentful Preview API to make a request (use the query provided above ☝️)
5. Check response's entries' `sys.locale`

## Context

Our site allows to switch to a preview mode which basically just uses **Contentful Preview API**. After today, we no longer can access the preview version because we rely on `sys.locale` on entries to figure out if the response has localized fields (For example, if query was with `locale: '*'` or `locale: 'en'`)

## Environment

-   **Language Version**: Node v12.16.2
-   **Package Manager Version**: Yarn 1.22.4
-   **Operating System**: MacOS, Linux (deployed to Vercel, not sure what Linux OS runs under)
-   **Package Version**: contentful@7.14.4
-   **Which API are you using?**: Delivery (works as expected) / Preview (fails as explained above)

**Comment by gburgett** [comment]
My team ran into this same issue today, and we do not use contentful.js, we use our own Ruby client.  So, this is most likely an issue with a recent change to the Contentful Preview API.

**Comment by eddyw** [comment]
@gburgett I opened a ticket with Contentful support yesterday and today they let me know that this was fixed. I'm testing before sending a reply but so far it seems that all is working again for us. It'd be great if you could verify with your team.

**Comment by gburgett** [comment]
@eddyw this is fixed for me as well.  I've asked that they post an incident report on their status page.

**Comment by gburgett** [comment]
Here is the response I received from my support ticket:

> Hi Gordon,
> 
> Thanks for reaching out again, I checked with our engineering team about this issue:
> 
> There was a change we shipped yesterday afternoon (Europe time), which caused the API quirk, this morning the team shipped a fix reversing the changes and the problem was solved.
> 
> We didn't deliberately change anything in our APIs, the CPA should continue to work as documented going forward. We will be working to make our systems more resilient against such regressions in the future.
> 
> About the incident report in our status page updates, I think it is missing this time because CPA is functional and the problem was identified and resolved at the same time. However, I agree with you and I will send the feedback to my manager so to improve the process.

I hope they will create an incident report, but it looks like this was a one-time error.

**Comment by marcolink** [comment]
As this seems fixed, I will close it for now. 
Feel free to open it again.
