### ISSUE TITLE
Retry doesn't work

### ISSUE THREAD

**Issue by pugbyte** [contentful/contentful.js#415]
##  Expected Behavior

When the SDK receives a response code 429 (rate limit), it retries that request.

## Actual Behavior

The SDK does not retry requests that fail on response code 429.

## Steps to Reproduce

I don't have any sample code for this, but I encounter 429 rate limits in my application occasionally (when I'm using the SDK in preview mode), and I noticed that they're not being retried, even though the documentation says they should be. 

## Environment

-   **Package Manager Version**: yarn 1.15.2
-   **Browser Version**: Chrome 83.0.4103.106, also encountered in Firefox 77.0.1 and Safari 13.1.1. Browser is likely not an issue.
-   **Operating System**: MacOS 10.14.6 (Mojave)
-   **Package Version**:  7.14.4
-   **Which API are you using?**: Preview

I found this other issue https://github.com/contentful/contentful.js/issues/277 with the same problem I'm experiencing. I tried downgrading to 7.0.3 and retries work, but I still think this should be fixed.

Thank you!

**Comment by marcolink** [comment]
Hi @pugbyte 👋 

This should be fixed in the latest version
