### ISSUE TITLE
allEntries is missing inside of the type CreateClientParams

### ISSUE THREAD

**Issue by dancespiele** [contentful/contentful.js#416]
## Expected Behavior

I should get all the entries and use the allEntries options in typescript
## Actual Behavior

I have the same issue that here https://www.contentfulcommunity.com/t/published-content-items-randomly-dissapear-from-fetched-yaml/1254/5 but I cannot include the option allEntries because is missing inside of the types of CreateClientParam

## Environment

-   **Language Version**:  ts-node v8.4.1
-   **Package Manager Version**: 
-   **Browser Version**: 
-   **Operating System**:  Solus
-   **Package Version**:  7.12.0
-   **Which API are you using?**:

**Comment by TimBeyer** [comment]
Hi @dancespiele,
this option does not exist in the JS SDK and is specifically for the `jekyll` importer.  
Could you explain what you're trying to do?  
The SDK has pagination options which should allow you to fetch all the data by paginating through it.  
There's also https://github.com/contentful/contentful-export and https://github.com/contentful/contentful-import specifically for import and export use cases. Do any of those work for you?

**Comment by marcolink** [comment]
Closing for now as there hasn't been a response for a while now. Please feel free to re-open it ✌️
