### ISSUE TITLE
typings are very vague

### ISSUE THREAD

**Issue by pixelass** [contentful/contentful.js#417]
## Expected Behavior

I expect usable typings for methods

## Actual Behavior

`any` is used for parts where a typing would be extremely helpful (e.g. `query`).

There is no way to know what options can be used here (e.g. `getEntries<T>(query?: any): Promise<EntryCollection<T>>`)

```ts
export interface ContentfulClientApi {
    getAsset(id: string, query?: any): Promise<Asset>;
    getAssets(query?: any): Promise<AssetCollection>;
    getContentType(id: string): Promise<ContentType>;
    getContentTypes(query?: any): Promise<ContentTypeCollection>;
    getEntries<T>(query?: any): Promise<EntryCollection<T>>;
    getEntry<T>(id: string, query?: any): Promise<Entry<T>>;
    getSpace(): Promise<Space>;
    getLocales(): Promise<LocaleCollection>;
    parseEntries<T>(raw: any): Promise<EntryCollection<T>>;
    sync(query: any): Promise<SyncCollection>;
}
```
## Steps to Reproduce

n/a

## Context

I want to fetch all entries with a query but I don't know the expected shape of the query object.

## Environment

n/a

**Comment by marcolink** [comment]
@pixelass 
Thanks for reporting this. 
I agree that type definitions for queries are not optimal right now. 
There is an ongoing initiative to migrate this project fully to typescript.

I just opened a [PR](#563) for better query types. Feel free to comment!

**Comment by pixelass** [comment]
Seems like the link to the PR was wrong . 
Correct link: #563

**Comment by marcolink** [comment]
@pixelass Ah sorry, you're right. 
And thanks for posting the correct link 👍

**Comment by marcolink** [comment]
Closing this issue for now.
