### ISSUE TITLE
GraphQL. DRAFT references cause errors on nullable fields

### ISSUE THREAD

**Issue by pixelass** [contentful/contentful.js#418]
## Expected Behavior

`DRAFT` as `Reference` should be ignored by graphQL on nullable fields.

## Actual Behavior

Adding a `DRAFT` as `Reference` causes an error and prevents loading data.

Using: `useQuery` via `@apollo/client` or graphiql via `https://graphql.contentful.com/content/v1/spaces/{SPACE}`

```
"errors": [
    {
      "message": "Query execution error. Link to entry '{ENTRY_ID}' on field '{FIELD_NAME}' within type '{CONTENT_TYPE}' cannot be resolved",
      "extensions": {
        "contentful": {
          "code": "UNRESOLVABLE_LINK",
          "requestId": "{REQUEST_ID}",
          "details": {
            "type": "{CONTENT_TYPE}",
            "field": "{FIELD_NAME}",
            "linkType": "Entry",
            "linkId": "{ENTRY_ID}"
          }
        }
      },
      "locations": [
        {
          "line": 156,
          "column": 9
        }
      ],
      "path": [
        "{COLLECTION_NAME}",
        "items",
        0,
        "{FIELD_NAME}"
      ]
    }
  ]
```

Partial data exists on graphiql via `https://graphql.contentful.com/content/v1/spaces/{SPACE}` but it won't be returned by `@apollo/client`.

<img width="601" alt="contentful_error_graphql" src="https://user-images.githubusercontent.com/1148334/87536272-2453f780-c699-11ea-8f3a-3e90cf6e780a.png">

## Possible Solution

Removing the `DRAFT` works but is (probably) not the intended behavior

## Steps to Reproduce

1. Add a `DRAFT` as `Reference`
2. Query the contentType via `https://graphql.contentful.com/content/v1/spaces/{SPACE}`
3. See error

## Context

When changing a published entry to `DRAFT` the page cannot be loaded. This can cause unexpected behavior and should be considered a showstopper.

Partial data exists on graphiql via `https://graphql.contentful.com/content/v1/spaces/{SPACE}` but it won't be returned by `@apollo/client`. 

**If this is considered an `@apollo/client` issue please mention it in a comment so I can create an issue and link it.
Maybe `@apollo/client` does not return data when an error is present. The error is unnecessary and IMHO a bug.**

## Environment

-   **Language Version**: v12.15.0
-   **Package Manager Version**: 6.13.4
-   **Operating System**: 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
-   **Package Version**: n.a.
-   **Which API are you using?**: GraphQL

**Comment by Spring3** [comment]
Hi, @pixelass.

Thanks for reporting this ticket. Indeed, Contentful Delivery API returns references to draft content along with an error, which is by design. A decision was made to have sdks handle this by providing an option to filter them out of the response.

For JS sdk, there is an option called `removeUnresolved`, that is responsible for such functionality. Have you tried adding it to your contentful.Client config?

You can see all the settings for the client [on this page](https://contentful.github.io/contentful.js/contentful/7.14.5/contentful.html#.createClient)

**Comment by pixelass** [comment]
@Spring3 thx for the comment but AFAIK there is no way to configure the graphQL API since it's hosted/provided by contentful and not part of our own source-code

**Comment by julianbenegas** [comment]
No news on this? So, with graphql, we can't reference a draft entry... That's unfortunate

**Comment by mvanduijker** [comment]
You can get drafts back with the preview option. By default Apollo client will handle any error as a network error. You can change that behaviour so you can work with the results you get back. To configure apollo client read this:   https://www.apollographql.com/docs/react/data/error-handling/#error-policies.

**Comment by pixelass** [comment]
@mvanduijker thank you for the link. 
It seems like we have to set it on every query request though.
Maybe I overlooked the global option for this.

**Comment by pixelass** [comment]
I found this: https://www.apollographql.com/docs/react/api/core/ApolloClient/#example-constructor-call

So it seems it can be globally added.

Closing since this should resolve the issue.

**Comment by hugomn** [comment]
Hey, this issue is causing us some troubles, using GraphQL Api. I know we can filter or ignore the errors, but what about the `null` entries? For example when we have an entry with linked entries, and some of then are still in draft mode, we get something like this:

```
[
  { sys: { id: <id> } },
  { sys: { id: <id> } },
  null,
  { sys: { id: <id> } }
]
```

Which is very annoying and error-prone when we use indexing of the items to track order, for example. And as far as I understood, the option `removeUnresolved` is not available in the GraphQL Api. Any other way of fixing this?

**Comment by wunt** [comment]
Is there any update on this issue? I am also affected by this issue which is really inconvenient.
I'd expect that Drafts/Unpublished Contents are complete ignored and not returned, if the "preview: false" parameter is set (=default), also for recursive content...

**Comment by lucashfreitas** [comment]
I am having the same issue - it's strange - why the graphql api returns NULL fields in draft items instead of just not returning them? Since we have preview tokens for that purposes it seems like a bug? @pixelass 

As @hugomn mentioned a lot of my queries are also returning this data structure:

```
[
  { sys: { id: <id> } },
  { sys: { id: <id> } },
  null,
  { sys: { id: <id> } }
]

```

So I am having to do a lot of `data.filter(x=>x)` as a workaround for this issue.

@hugomn did you find any solution for that?

Thanks.

**Comment by pepijnverburg** [comment]
We are also hitting this issue, would be great if somehow it is possible to pass `removeUnresolved` via a custom header to apply for all queries? Or add it as a query arguments like the `preview` flag?

Filtering out errors and then also the null references is a temporary solution, but for sure not a pretty one. Let us know if there are any other options!

**Comment by sometimescasey** [comment]
Just adding a quick note to myself and others in future that if you are following the Contentful tutorial for basic setup with React, and you're using the prepopulated Contentful example blog, the 3 example blog posts are connected to Hero images which are set to DRAFT and will therefore result in this error.

![image](https://user-images.githubusercontent.com/16248601/142059071-9c0ed4e6-1fdb-45e8-acc1-607816fa1dc3.png)


Not a bug per se but could throw beginners off. Thanks for opening the issue!

**Comment by harleyharl** [comment]
I'm also having this exact problem. I'm not using Apollo as my GraphQL client so I don't have the option to `removeUnresolved`. I'm using [graphql-request](https://github.com/prisma-labs/graphql-request#error-handling). Filtering out draft content in the front end doesn't work!

**Comment by pepijnverburg** [comment]
@harleyharl The nice thing is that you receive a quite extensive GraphQL error from Contentful where it specifies all the JSON paths where there is unresolved content. You can loop through those errors one-by-one and remove them from the data JSON. After you removed them you can also remove the error from the GraphQL response (you sort of 'fixed' the error). Yes, I know this is **not good practise** at all, but this was causing a lot of issues for us when different clients were consuming Contentful data. Downside of such a third-party GraphQL API without all the options in the original SDK.  

An example of a utility function that you can put in either your front-end or back-end middleware (BTW: if you are no fan of Lodash, then see this as a reference for you..):
```typescript
import { filter, get, isArray, isEmpty, isNumber, map, pull, set, slice, unset, cloneDeep } from 'lodash';
import { GraphQLError } from 'graphql';

interface GraphQLResponse {
  errors: GraphQLError[];
  data: any; // type this if needed
}

// this is a piece of the error message to match on that you get back as a Contentful unresolved error.
// adapt this matcher to your own setup depending on how strict it should be (e.g. when you might have other API's with similar errors).
const CONTENT_UNRESOLVED_MATCHER = 'cannot be resolved';

/**
 * Based on GraphQL errors from contentful we can automatically filter out unresolved links
 * across the response and resolve the errors in our own middleware so the client is not dealing with it.
 */
export function filterUnresolved(response: GraphQLResponse) {
  const { errors, data } = cloneDeep(response);
  const regex = new RegExp(CONTENT_UNRESOLVED_MATCHER);
  const unresolvedErrors = filter(errors, (error) => {
    const { message } = error;
    return regex.test(message);
  });
  const potentialUnresolvedPaths: (string|number)[][] = [];

  // guard: skip filtering when there are no unresolved errors
  if (isEmpty(unresolvedErrors)) {
    return response;
  }

  map(unresolvedErrors, (error) => {
    // cast to non-read only
    const path = (error.path) as (string|number)[];

    // guard: skip invalid paths
    if (!path) {
      return;
    }

    // by default we remove the unresolved content from the path completely
    unset(data, path);

    // add the path to be removed entirely later on
    potentialUnresolvedPaths.push(path);

    // register the parent path when it is an array to remove null entries later
    if (isNumber(path?.[path?.length - 1])) {
      potentialUnresolvedPaths.push(slice(path, 0, path.length - 1));
    }

    // if all is good we will delete the error as well
    pull(errors, error);
  });

  // strip out all the potential nulls that exist while filtering.
  // this is done afterwards, because some paths contain indexes and if you
  // mutate directly all the indexes will shift, causing the wrong data to be removed.
  map(potentialUnresolvedPaths, (path) => {
    const entry = get(data, path);

    if (isArray(entry)) {
      const filteredList = filter(entry, (entryPiece) => {

        // filter out nulls and undefined from a list
        // NOTE: if you expect nullable objects this will mess some things up!
        return entryPiece ?? false;
      });

      set(data, path, filteredList);
      return;
    }
  });

  return response;
}
```

I haven't tested the code in complete isolation, so let me know if something is still wrong. Hope this helps!

**Comment by SergeiZag** [comment]
The [solution ](https://www.apollographql.com/docs/react/data/error-handling/)for Apollo client can be to use `errorPolicy: "all"`  and looks working for my case like:
`const {
    loading,
    error,
    data
  } = useQuery(GET_BY_ID, {
    variables: {
      id: params.id,
    },
    errorPolicy: "all" 
  });`

**Comment by MickL** [comment]
I dont exactly understand:

Using the preview access token I should be able to query for drafts but when one of the entries of a referenced field is a draft Apollo throws an error. If I ignore the error (thanks @SergeiZag) the item is null. 

- Shouldnt drafts be resolved with the preview access token?
- Also setting `myCollection(preview: false)` should show no drafts, but the error is thrown anyway

**Comment by BirgitPohl** [comment]
I'm running into the issue also. I find @MickL comment very good. We shall think about logic as well, when creating APIs.

**Comment by rahimimo** [comment]
Not all errors are related to the unresolvable links, @MickL maybe what you are getting is related to a deleted entry or other errors like query complexity. Please post your error. I do not have the unresolvable error with the preview token. (Make sure the preview boolean is also set to true)

@harleyharl  The `graphql-request` library also have a errorPolicy as well https://github.com/jasonkuhrt/graphql-request?tab=readme-ov-file#errorpolicy

**Comment by sorenhoyer** [comment]
When calling a Delivery API we expect only to get published content. If it was a Management or Preview API my expectations would have been differently.

In my opinion the problem is how required fields are enforced in the Management System. When setting a required field e.g. a requried reference field, I'd expect that reference to be published as well - unfortunately contentful allows a required reference field to contain a reference to an unpublished entry.

Meaning that we need to sprinkle `where: id_exists: true` all over the place to causing the required field to return null, instead of getting an "Query execution error. Link from entry ... to entry ... on field 'foo' within type 'Bar' cannot be resolved". This workaround is a terrible work-around for something that should not have been possible to begin with, from the Contentful Management System side as I see it.

This issue should be reopened.

**Comment by marlonschlosshauer** [comment]
> Meaning that we need to sprinkle where: id_exists: true all over the place to causing the required field only to get null in return - but still better than breaking things with an "Query execution error. Link from entry ... to entry ... on field 'foo' within type 'Bar' cannot be resolved". This workaround is a terrible work-around for something that should not have been possible to begin with, from the Contentful Management System side as I see it.

To add to this wonderful answer, if `id_exists` doesn't show up for you, make sure to query the `sys` field, like: `(where: { sys: { id_exists: true } })`.

**Comment by mdomanski93** [comment]
it resolved my problem 

> > Meaning that we need to sprinkle where: id_exists: true all over the place to causing the required field only to get null in return - but still better than breaking things with an "Query execution error. Link from entry ... to entry ... on field 'foo' within type 'Bar' cannot be resolved". This workaround is a terrible work-around for something that should not have been possible to begin with, from the Contentful Management System side as I see it.
> 
> To add to this wonderful answer, if `id_exists` doesn't show up for you, make sure to query the `sys` field, like: `(where: { sys: { id_exists: true } })`.

**Comment by tth-nine** [comment]
This is still an issue. 
`where: { sys: { id_exists: true } }` does not work with a reference field that has many content-types.

We have the follow query, where body collection can contain 4 different content types

```js
query getSomething() {
  __typename
  articleCollection(
    preview: false
    locale: 'en'
    where: { slug: 'my-slug' }
  ) {
    __typename
    items {
      __typename
      slug
      bodyCollection(preview: false, where: {sys: { id_exists: true }}) {
      items {
          __typename
        }
      }
    }
  }
}
```
which just give an empty bodyCollection array and without the `where: { sys: { id_exists: true } }` throws and UNRESOLVABLE_LINK error

And `where: { sys: { id_exists: true } }` looks more like and hack then a final solution but it is now part of the official docs on [contentful graphql errors] 🤷 
(https://www.contentful.com/developers/docs/references/graphql/#/reference/graphql-errors/graphql-errors-explained)
![Image](https://github.com/user-attachments/assets/4d70d60a-9f0d-4e7b-adf0-daa865b36e67)
