### ISSUE TITLE
Gray bottom line on the images after a crop

### ISSUE THREAD

**Issue by hellopath** [contentful/contentful.js#419]
## Expected Behavior

I would like to crop my image with contentful's asset editor without a gray line at the bottom of the page.
The ratio I use is 2:3 for mobile use.

## Actual Behavior

After I apply a crop, a gray line at the bottom of the image appears which is not the case before the crop.

<img width="758" alt="Screenshot 2020-07-18 at 23 09 40" src="https://user-images.githubusercontent.com/550356/87862063-3f01c700-c94c-11ea-818d-0faef76ed7b4.png">
<img width="696" alt="Screenshot 2020-07-18 at 23 09 49" src="https://user-images.githubusercontent.com/550356/87862065-43c67b00-c94c-11ea-890e-2587169f5455.png">

## Steps to Reproduce

1. Download that [image](https://www.dropbox.com/s/gv8lmuvzrosbtmi/minitore_vue01.jpg?dl=0) I also use.
2. On the content model add a content type.
3. In the content type add a field.
4. Choose a media.
5. Create a new content of that content type and click "Create new asset and link" so to create a new media.
6. Drag and Drop the file to upload.
7. Select crop 
8. Apply custom crop 2:3

Thank you guys

**Comment by Spring3** [comment]
Hello @hellopath .

Since it looks, like the issue is not on the sdk side, but rather on the way image processing services work, I would like to kindly ask you to open a ticket for customer support on the web app via intercom or contacting the support directly.

**Comment by hellopath** [comment]
Hey @Spring3,
Thank you for your answer, I opened a ticket on the customer support.
