### ISSUE TITLE
obscureAuthTokenInResponse - Uses a deprecated property since Node v12

### ISSUE THREAD

**Issue by lfamorim** [contentful/contentful.js#421]
This PR is non-sense. As programmers, we need to make all code understandable and avoid secret shortcuts, like the function obscureAuthTokenInResponse. This pull-request inserts a deprecated property from NodeJS since the 12 version and does not guarantee that there is no other secret leaking from the error, resuming, still insecure, and breaks production environments.

https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames

A logical suggestion to fix is to stop trying to modify the headers from the error to make safe. Simply creating a new error and using safe methods and properties, those who not begin with an underscore and exists in the documentation will do better in turning this library safe in error throwing.

```
lfamorim@lfamorim-bipbop:~/projects/bipbop-components/packages/screen-generator$ node --trace-deprecation dist/contentful-client.js
(node:18129) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at /home/lfamorim/projects/bipbop-components/packages/screen-generator/node_modules/contentful/dist/contentful.node.js:7610:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async retrieveLabel (/home/lfamorim/projects/bipbop-components/packages/screen-generator/dist/contentful-client.js:34:18)
(node:18129) UnhandledPromiseRejectionWarning: #<Object>
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:18129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```
```

_Originally posted by @lfamorim in https://github.com/contentful/contentful.js/pull/355#issuecomment-663904454_

**Comment by Morialkar** [comment]
No fix yet? I just started using the SDK and it clearly says that it supports Node.js LTS (which node 12 is) and it blocks because of this. I don't want to move my whole backend back to node 10 just because you want to keep using undocumented  properties of node...

**Comment by mayakarabula** [comment]
closing the issue, if you still need help with this please reach out to Contentful support
