### ISSUE TITLE
Typings suggest that Field.validations is always defined, but it is not.

### ISSUE THREAD

**Issue by hanna-greaves** [contentful/contentful.js#427]
This is an issue that came up when I was working with @marcolink on a [change](https://github.com/contentful-labs/cf-content-types-generator/pull/22) to the content types generator.

## Expected Behavior

Typings for the `Field` type suggest that `validations` will always be set.

## Actual Behavior

It is possible that `validations` can be undefined when querying the `content_types` endpoint from the Content Delivery API

## Possible Solution

Make `validations` in [`Field`](https://github.com/contentful/contentful.js/blob/master/index.d.ts#L172) an optional type that the user needs to use a null check guard with, or make the Content Delivery API always return an empty array for validations.

## Steps to Reproduce

1. Go to Contentful and create a new content type called ValidationsDemo
2. Add one boolean field called test
3. Save/publish the content type
4. Call the Content Delivery API and retrieve the content type you just created, you will see that the validations field does not exist.

Example response : 
```
{
            "sys": {
                "space": {
                    ...
                },
                "id": "validationMissing",
                "type": "ContentType",
                "environment": {
                    ...
                },
            },
            ...
            "fields": [
                {
                    "id": "test",
                    "name": "test",
                    "type": "Boolean",
                    "localized": false,
                    "required": false,
                    "disabled": false,
                    "omitted": false
                }
            ]
        },
```

## Context

This caused some issues with the content type generator as it was expected that validations would never be null, which caused the tool to fail when trying to generate typescript definitions for our Content Model.

N.b. I'm happy to provide a PR to change the typescript definition if that is the solution :)

**Comment by marcolink** [comment]
Hi @hanna-greaves 👋 
We expected this to be solved with the latest [major](https://github.com/contentful/contentful.js/compare/v9.3.5...v10.0.0)  release (which was a complete re-write).
Please feel free to re-open again if the error still occurs.
