### ISSUE TITLE
Performance issue with cloneDeep

### ISSUE THREAD

**Issue by asselin** [contentful/contentful.js#428]
## Actual Behavior

While doing some performance testing, I noticed that there is a significant amount of time being spent in cloneDeep (in my case, app startup spent ~100ms in cloneDeep).  A getEntry call winds up calling cloneDeep 3 times on the response.  It looks like cloneDeep was added several years ago, but there wasn't any detail on why it was added-- is there a reason the data from the API needs to be cloned before being processed?  Can those cloneDeeps be removed to fix the performance issue?  If there's a reason to clone the data, can the multiple clones be pared down to just 1?

**Comment by marcolink** [comment]
Hi @asselin, 

With version 8, we have removed most of the `cloneDeep` calls including those invoked in our own dependencies. 
Thanks again for pointing it out!

I'll close this issue for now. Feel free to open it again.
