### ISSUE TITLE
Avoid using snake_case in javascript

### ISSUE THREAD

**Issue by jkatsnelson** [contentful/contentful.js#43]
Hey, I noticed your "content_type" key uses snake case. I think it would be more idiomatic JS to stick with camel case. Feel free to close this without comment, I just wanted to point it out.

**Comment by slang800** [comment]
:+1:

**Comment by trodrigues** [comment]
This is due to that being the way our API takes its parameters, which are sent via HTTP URL parameters, and that's a more common pattern there.

**Comment by jkatsnelson** [comment]
Ah that makes sense, sorry! Silly me
