### ISSUE TITLE
Posts with Related Posts of the same content type produce very deep object

### ISSUE THREAD

**Issue by AlexandraKlein** [contentful/contentful.js#439]
## Expected Behavior
When fetching post data with `include: 3`, response should not return data deeper than 3 levels.

## Actual Behavior

```javascript
export async function getPosts(slug, preview) {
  const entries = await contentfulClient(preview).getEntries({
    content_type: 'post',
    'fields.slug[in]': slug,
    include: 3
  });

  return entries;
}
```

The following returns:

```javascript
 items: {
    0: {
      fields: {
        title: 'article 1',
        relatedPosts: {
          0: {
            fields: {
              title: 'article 2',
              relatedPosts: {
                0: {
                  fields: {
                    title: 'article 3',
                    relatedPosts: {
                      0: {
                        fields: {
                          title: 'article 4',
                          relatedPosts: [...goes on very deep...]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
```

-   **Node Version**:  14.13.1
-   **Yarn Version**: 1.22.10
-   **Operating System**: OSX Chrome
-   **Package Version**: 7.14.8
-   **Which API are you using?**: Delivery

**Comment by TimBeyer** [comment]
Hi @AlexandraKlein 
could it be that the `relatedPosts` contain circular references?  
While `include: 3` only fetches three levels deep, if entries reference each other, they are linked together so a circular reference might look like infinite depths when logged.

**Comment by AlexandraKlein** [comment]
@TimBeyer, yes, that is exactly what is happening. Certainly related posts will be linked to each other at some point. Still unclear how to stop relatedPosts data after 3 levels deep. I only require Related Posts of the fetched post.

**Comment by AlexandraKlein** [comment]
Current solution is separating and implementing additional requests.
re: https://github.com/vercel/next.js/discussions/10992#discussioncomment-109197

**Comment by TimBeyer** [comment]
From the thread it sounds like we can close the issue, correct?  
Sadly there isn't really a way to stop circular dependencies after a certain level.  
The entry objects that link to each other are always the same instances, so there is no way to break the cycle at some point.  

Take for example a list of objects linking like this `A -> B -> C -> A -> B ...`.  
The instance of `A` that links to `B` is the same as the one `C` links to.  
If I were to remove the reference from `A` to `B` to break the cycle at the point where it repeats, I would break the original chain too.  

If you want to work with a fully flattened version of the model, you would have to use the raw response and manually resolve the `includes` from the returned entries where you can keep track of cycles yourself.

**Comment by AlexandraKlein** [comment]
I'm ok with closing this issue.
