### ISSUE TITLE
Upgrade axios to 0.6.0

### ISSUE THREAD

**Issue by trodrigues** [contentful/contentful.js#44]
Will require us to provide the promise implementation.

**Comment by skevy** [comment]
It would be awesome actually if you updated when this PR was merged (hopefully would be soon)? https://github.com/mzabriskie/axios/pull/98 and disable xhrf (which is not needed here).

This allows for uses on platforms like React Native.

**Comment by trodrigues** [comment]
Ah, thanks for the feedback. Will keep an eye on it and let you know.

**Comment by mzabriskie** [comment]
axios@0.6.0 has been release...

**Comment by trodrigues** [comment]
@mzabriskie ah, thanks for the notice, we'll update this soon as we also need to change our builds a bit to reflect this.

Also, kind of unrelated side note, maybe it would've been a good idea to up the major version of axios as this is a major breaking change :)

**Comment by mzabriskie** [comment]
@trodrigues ideally this would be a major version bump. The lib isn't at 1.0 yet. Until it is, minor versions should be treated as breaking changes.

**Comment by trodrigues** [comment]
@mzabriskie fair enough. I also wasn't aware there had been some changes to semver to treat minors below 1.0 as breaking (a coworker made me aware of it).

**Comment by jakubholynet** [comment]
There is now Axios 0.7.0. One of the nice changes is that it now [supports passing in an agent](https://github.com/mzabriskie/axios/commit/11c0b0aa10dd5f9580e31cda7637f869e7d1ef77) and thus makes it possible to use it over a http(s) proxy, which is necessary in every typical enterprise setting. It would be nice to get that available :)

**Comment by trodrigues** [comment]
Fixed on 2.1.0
