### ISSUE TITLE
RichTextEditor

### ISSUE THREAD

**Issue by David05500** [contentful/contentful.js#440]
Why are you making it so difficult to print out RichTextEditor data, why there isn't a simpler way of doing it instead of defining options, configs and so on .... having options and config optional would make the whole experience so much more developer friendly.

**Comment by marcolink** [comment]
Hi @David05500,

I'm sorry to hear you facing these issues. 

Is this about typescript types, or a general issue you're facing with the structure of the data?

Have you already tried to use our [richtext-renderer](https://www.contentful.com/developers/docs/javascript/tutorials/rendering-contentful-rich-text-with-javascript/).

**Comment by mayakarabula** [comment]
closing the issue, if you still need help with this please reach out to Contentful support
