### ISSUE TITLE
Definition of `Asset` type is wrong - failing content validation

### ISSUE THREAD

**Issue by alonre** [contentful/contentful.js#442]
## Expected Behavior
[Type definition of `Asset`](https://github.com/contentful/contentful.js/blob/master/index.d.ts#L50) should match the actual content that is returned from the API.

## Actual Behavior

 1. `sys`: Asset uses the general definition of `sys`, which requires a `contentType` entry. However, `Asset` does not include it. **This is the main blocker for us (at Intercom).**
 1. `title` is declared as `required` - but it is not required by Contentful's App/UI
 1. `description` is declared as `required` - but it is not required by Contentful's App/UI

## Possible Solution

 1. Fork the definition of `sys` so `Asset` could have it's own `sys` definition which does not include `contentType`
 1. Change definition of `title` and `description` to be optional

## Steps to Reproduce

1. Create an Asset on Contentful (see that you can leave the `title` and `description` empty)
2. Export the asset's JSON (either by API or by reloading the Contentful page and inspecting the network request in the browser)
3. See that the returned response does not contain a `contentType` node

## Context

This blocks us from validating our content when deploying to production.
Here at Intercom we "export" all the content (as JSON) through the Content Delivery API upon deployment - and validate everything with JSONSchema.

Up until now we were using "weak" validation that only verified the "fields" of each entry - but that allowed too many bad deployments (specifically - deployments with references to deleted entries).
To generate the JSON schema we use [`typescript-json-schema`](https://github.com/YousefED/typescript-json-schema#typescript-json-schema).
Most of the TypeScript types used for the schema are generated by our code - except for `Entry` and `Asset` that are coming from this lib.

Having this fixed would allow us to spot content issues during deployment, thus have much greater confidence in our deployments and less incidents in production.

## Environment

Since this is tied directly to the code definitions I don't believe my environment is relevant here.
Omitting this to reduce noise.

## Related Issues and PRs
https://github.com/contentful/contentful.js/issues/208
https://github.com/contentful/contentful.js/pull/258
https://github.com/contentful/contentful.js/pull/206

**Comment by alextiley** [comment]
Looks like this was raised a while back but came across this issue whilst searching for a problem that I am also encountering. 

In our case we have editors who link assets to content and then later unpublish those assets. This results in the content API returning a payload structure where the asset's `fields` property is `undefined`, and not required as per the typings:

Example response from content API:
```json
{
  "metadata": {
    ...
  },
  "sys": {
    ...
  },
  "fields": {
    "foo": "Foo",
    "bar": "Bar",
    "someAsset": {
      "sys": {
        "type": "Link",
        "linkType": "Asset",
        "id": "1hOckwQBvtE7JM4yRxqLl2"
      }
    }
  }
}
```

Current typings for type `Asset`:
```typescript
export interface Asset {
    sys: Sys;
    fields: {
        title: string;
        description: string;
        file: {
            url: string;
            details: {
                size: number;
                image?: {
                    width: number;
                    height: number;
                };
            };
            fileName: string;
            contentType: string;
        };
    };
    metadata: Metadata;
    toPlainObject(): object;
}
```
The TypeScript type for type `Asset` declares that `fields` is required. However in the scenario above, `entry.fields.someAsset.fields` is `undefined`.

I could probably create a PR for this specific use case if this is something that the maintainers are happy to accept?

**Comment by magnattic** [comment]
We have a similar issue. When you have two languages with no language fallback and only upload the Asset in one language, `fields.file` can be `undefined`. But TS doesn't warn us because the types don't reflect this.

**Comment by magnattic** [comment]
If I read this correctly this still leaves the problem mentioned above: The typings don't always reflecting what's going on during runtime:
- If there is no language fallback defined, `asset.file` can be `undefined` if the image was only uploaded in one language. But in the typings it's not optional:

```
export interface AssetFields {
  title?: string
  description?: string
  file: AssetFile
}
```

**Comment by magnattic** [comment]
Yes, I'll open one as soon as possible.

While I have your attention: Under all of this is actually one of the biggest problems our company has with Contentful (which we love).
The fact that the language fallback is "all or nothing" is really making things hard on our end.

- We want automatic language fallback for all images/assets, since most of our images are not language specific.
- We don't want automatic language fallback for most content types, since we don't want to accidentally show mixed language content anywhere. Also we need to support pages that are only available in one language and non-existant in other languages (which is hard when you have language fallback enabled).

This means we need to disable language fallback everywhere (since it's not more atomic) and have to solve all the resulting problems by hand:
- We need to gather the fallback images manually with a complex solution for all languages that are not the default.
- If we have other content types that need a fallback, we have to provide duplicated content there. Example: URLs to external pages that are not language specific.

It would be great if Contentful would support more fine grained control over what has a language fallback and what doesn't.

**Comment by marcolink** [comment]
@magnattic Thanks for your feedback, 
I will forward it to our product team! 

May I also suggest our [community slack](https://www.contentful.com/slack/) for such requests? Questions that are more intended for product teams are more visible to them.

Best
Marco

**Comment by marcolink** [comment]
@magnattic 

created a PR to also address this issue: https://github.com/contentful/contentful.js/pull/1240
