### ISSUE TITLE
The removeUnresolved flag unexpected behaviour

### ISSUE THREAD

**Issue by aelmeniawy** [contentful/contentful.js#444]
Our application consumes Contentful with linked draft entries. We went for using the flag provided by the SDK `removeUnresolved` to filter out the problematic draft entries but it seemed to filter out more than what we wanted.

Sometimes we fetch entries using a certain depth in order just to fetch the sys property of the entry and not include the fields.

## Expected Behavior

When the flag `removeUnresolved` is set to true it would remove only draft entries from the response object..

## Actual Behavior

Entries that don't contain the `.fields` property get filtered out even though they're not in draft mode.

## Possible Solution

What would be nice to have is to only filter out entries that are actually in draft mode and not filter out the entries that are fetched with shallow depth (i.e., not including the .fields property).

## Steps to Reproduce

1. Write a query that fetches only the sys property of entries linked within an entry
2. Set the `removeUnresolved` flag to `true`

Entries within the entry fetched would all be filtered out as they don't contain the `.fields` property.

## Context

I was trying to filter out draft entries.

## Environment

-   **Language Version**:`12.x`
-   **Package Version**:  v7.14.8 
-   **Which API are you using?**:  Delivery

**Comment by TimBeyer** [comment]
Hi @aelmeniawy, I'm wondering if you encountered this bug when you did a `select: 'sys'` or if you actually selected a specific set of `sys` properties. In theory the filter should really only remove entities it cannot find and the `fields` property is not looked at. There's a different bug however that sometimes makes the SDK not resolve links correctly in case a subset of `sys` fields was used. I'm wondering if this might be another instance of that bug or if I need to dig a bit deeper here.

**Comment by TimBeyer** [comment]
@aelmeniawy could you check if the latest release also fixed your problem?

**Comment by nenad-percic** [comment]
@TimBeyer @aelmeniawy is colleague of mine on the same project - version 7.15.1 is currently not testable for us due to #503 that we reported today. I will followup this as soon as it becomes actionable.

Thank you!

**Comment by TimBeyer** [comment]
Your use case should now work in https://github.com/contentful/contentful.js/releases/tag/v8.1.0

**Comment by nenad-percic** [comment]
@TimBeyer That was unexpectedly quick release. :)

I wrote two [tests](https://prnt.sc/vxgzlx) that would cover our use-case and both of them are green! :) 
Thank you very much!
