### ISSUE TITLE
Still getting circular reference 

### ISSUE THREAD

**Issue by kbowerma** [contentful/contentful.js#46]
@trodrigues I updated the npm to 1.2.0 and added the option ```resolveLinks: false``` in my client declaration.  and I still get the circular reference error.

[Here is my app on Heroku](https://contentful-request-dev-pr-16.herokuapp.com/)  and here is [my code on github](https://github.com/kbowerma/contentful-request/tree/bug/nativeContentful)   branch bug/nativeContentful.   Do you mind telling me if I am doing something wrong.

**Comment by kbowerma** [comment]
I created a pull request and added an pure node example that should show the circular reference issue,  You will need to create a new space and use the blog sample.  Then you should be able to start it with ```node app.js``` and fire your browser to localhost:3000

**Comment by trodrigues** [comment]
This is not a problem anymore with the 3.x series (see the migration guide for more details https://github.com/contentful/contentful.js/blob/master/migration_from_2_x.md)
