### ISSUE TITLE
Contentful selling email addresses to spam operators

### ISSUE THREAD

**Issue by kevindoveton** [contentful/contentful.js#489]
## Context
I create a unique email address for each website I sign up for, since the 7th of October, 2020, I have received multiple emails from spam operators to the email address I used for Contentful. Is Contentful selling data to third parties, or has there been a data breach?

Example of spam emails

<img width="1236" alt="Screen Shot 2020-11-26 at 6 52 48 pm" src="https://user-images.githubusercontent.com/11331381/100325897-2780cc00-3019-11eb-92ee-eff44b581f23.png">

Example of legit email from Contentful
<img width="2032" alt="Screen Shot 2020-11-27 at 8 00 45 am" src="https://user-images.githubusercontent.com/11331381/100392583-f2ab5e00-3086-11eb-914b-d7a042ec67c3.png">

## Expected Behavior
Contentful does not sell my data to third party spam operators.

## Actual Behavior
Contentful does sell sell my data to third party spam operators.

**Comment by stefanjudis** [comment]
Contentful does not sell email addresses to spam operators. Privacy and security are top priorities at Contentful. For more information on our security practices, including our ISO 27001 compliance certificate, please visit our website: [www.contentful.com/security/](https://www.contentful.com/security/).  You can also find more information on Contentful's privacy practices on our website: [www.contentful.com/legal/privacy/](https://www.contentful.com/legal/privacy/).  

If you have any additional questions, please contact us at [privacy@contentful.com](mailto:privacy@contentful.com). Thank you.
