### ISSUE TITLE
Links are not resolving (querying entries by content_type)

### ISSUE THREAD

**Issue by jarodtaylor** [contentful/contentful.js#50]
If I have a collection of entries (e.g. corporate leaders) and it includes an attached photo, the links are not resolving, no matter how many I put in the `include` parameter. I tried 1-10.

```
var contentful = require('contentful');

var client = contentful.createClient({
  space: 'xxxxx',
  accessToken: 'xxxxxx',
  resolveLinks: true
});

client.entries({'content_type':'xxxxx', include:1}).then(function(leaders) {
  return leaders.map(function(leader){
      console.log(leader.fields);
  });
})
```

This returns :

```
{ order: 1,
  name: 'Bob Barker',
  title: 'President',
  bio: 'Biography goes here',
  photo: { sys: { type: 'Link', linkType: 'Asset', id: 'xxxxx' } } }
{ order: 2,
  title: 'VP, Product',
  name: 'John Wayne',
  bio: 'Biography goes here',
  photo: { sys: { type: 'Link', linkType: 'Asset', id: 'xxxxx' } } }
```

However, in another entry (it's really a single entry but I have to use `entries` so that I can query), it works perfectly fine:

```
client.entries({'sys.id':'xxxxxxx', include:1}).then(function(pages) {
  console.log(pages[0].fields);
});
```

returns this:

```
{ pageTitle: 'Page Title',
  pageSummary: 'This is where the page summary goes.',
  section4Image:
   Asset {
     sys:
      Sys {
        id: 'xxxxx',
        revision: 3,
        type: 'Asset',
        locale: 'en-US',
        space: [Object],
        contentType: undefined,
        createdAt: Tue Nov 10 2015 14:50:55 GMT-0600 (CST),
        updatedAt: Tue Nov 10 2015 15:40:04 GMT-0600 (CST) },
     fields: { file: [Object], title: 'Team Happy Hour in Manhattan' } },
  section2Image:
   Asset {
     sys:
      Sys {
        id: 'xxxxxx',
        revision: 2,
        type: 'Asset',
        locale: 'en-US',
        space: [Object],
        contentType: undefined,
        createdAt: Tue Nov 10 2015 14:51:11 GMT-0600 (CST),
        updatedAt: Tue Nov 10 2015 15:37:03 GMT-0600 (CST) },
     fields: { file: [Object], title: 'Photobooth at SXSW 2013' } } }
```

Both of these were attached the same exact way inside of the Contentful Admin UI, but you'll see in this example I actually have access to the Assets attached. In fact, if I remove that `include:1`, I still can get it to work.

**Comment by jarodtaylor** [comment]
This was my fault. I'm closing the issue. 

I had uploaded all the photos in the Media tab of Contentful but I had not "Published" them.

Brainfart on my part.

**Comment by trodrigues** [comment]
Hi there,

no worries. This is definitely a workflow that could probably use some improvement in the user interface and something that we discussed before.

I've mentioned this to the user interface product manager so they can take it into consideration in future improvements in the UI
