### ISSUE TITLE
contentful.min.js isn't updated

### ISSUE THREAD

**Issue by nettaru** [contentful/contentful.js#51]
The index.es6.js version considers also headers as a part of the client creation:
https://github.com/contentful/contentful.js/blob/master/index.es6.js#L12
https://github.com/contentful/contentful.js/blob/master/index.es6.js#L30

This code is missing from the minified version.
Could you please update the minified version?

**Comment by trodrigues** [comment]
Hi there,

apologies for this. It should be updated now.
