### ISSUE TITLE
Sync: I can get the initial sync, but when I set the 'nextSyncToken' option, I get no response.

### ISSUE THREAD

**Issue by jakecarr** [contentful/contentful.js#52]
Here is my code:

```javascript
            var syncToken = window.localStorage.getItem('syncToken');
            var entriesString = window.localStorage.getItem('entries');
            var entries = JSON.parse(entriesString);
            client.sync(syncToken ? {nextSyncToken: syncToken} : {initial: true})
                .then(function(response){
                
                    response.items.forEach(function (entity) {
                        if(entity.sys.type === 'Entry'){
                            entries[entity.sys.id] = entity
                        }
                        if(entity.sys.type === 'DeletedEntry'){
                            delete entries[entity.sys.id]
                        }
                    })
                    window.localStorage.setItem('entries', JSON.stringify(entries));
                    window.localStorage.setItem('syncToken', response.nextSyncToken);
            });
```

It gets the content fine when 'initial' is set to true, but if I set the 'nextSyncToken' to the 'nextSyncToken' that I got from the previous response, the function passed into the then() method is never called.

Hopefully you can help.

Thank you.

Jake

**Comment by trodrigues** [comment]
Hi Jake,

when you call the sync endpoint with a `nextSyncToken`, the then method is only called if any new content was published, any existing entries/assets updated and published or if any content was deleted since the last time you synced.

Is this the case? Have you changed any content since the last time the content was synced?

**Comment by jakecarr** [comment]
@trodrigues Hi Trodrigues,

Thank you for the reply!

Yeah I have updated an entry and published it. It only gets downloaded when I set the syncToken back to null so initial is set to true and so it downloads every entry again.

**Comment by jakecarr** [comment]
@trodrigues Just in case it helps - Just tried adding and publishing a new entry, instead of just editing an existing one and I still get no response.

**Comment by trodrigues** [comment]
Ok, thanks. I'll investigate and try and figure out what's going on.

By the way, another thing to note: the content delivery API is distributed by a CDN, so when you publish an entry it can take up to 60 seconds for it to show up on any requests to the API.q

**Comment by jakecarr** [comment]
@trodrigues Thank you.

Yeah I noticed this, it seemed to take around 25 seconds to be able to download new/updated content after it's published when 'initial' is set to true. However, even after waiting a few minutes, I still get no response when the 'nextSyncToken' is set.

**Comment by jakecarr** [comment]
@trodrigues When I add the following code:

```javascript
                client.sync({nextSyncToken: response.nextSyncToken})
                    .then(function(response){
                    console.log("Im inside the nested sync method")
                }, function(error){
                    console.log("Im inside the nested sync method but there was an error")
                    console.log("Error: " + JSON.stringify(error));
                });
```

after this line:

```javascript
                    window.localStorage.setItem('syncToken', response.nextSyncToken);
````

I get this error:

```JSON
{"sys":{"type":"Error","id":"BadRequest"},"message":"Please specify either the \"initial\" parameter as \"true\" or a valid starting date or the \"sync_token\" parameter with a valid sync token.","requestId":"90a-2083715328"}
```

Even though I set the 'nextSyncToken' option of the sync method to the 'nextSyncToken' that was just returned to me from the response.

The value of 'response.nextSyncToken' is:

```
w5ZGw6JFwqZmVcKsE8Kow4grw45QdybClzoHYsOUfsKswr13F35jR8OOUsOkwr4TXMKFw48GVWwnw5LCoglEIcKlw4dxSTnCsVUMBXbCpznDgFrDkcObBMO3w7VSwo_Dh8OmwqZywrcjbkoHJMK4wqjDlA
```

Does this look like a normal token? 

I know when I added a nested sync method like this, it doesn't give me the chance to update and publish the content, but I've got a feeling that I shouldn't get a 'BadRequest' error when no content has changed.

Hope this helps you :smiley:

**Comment by trodrigues** [comment]
Oh, I just noticed what your problem is. Here:
```
client.sync({nextSyncToken: response.nextSyncToken})
```

You should be doing
```
client.sync({syncToken: response.nextSyncToken})
```

While nextSyncToken is the name of the parameter actually sent in the url, and received in the response, the method takes a simpler name. In retrospect, having this name disparity probably wasn't a good idea.

I'll add a separate issue to fix this issue and make the library handle this situation better.

**Comment by trodrigues** [comment]
Disregard my previous comment (I deleted it).

**Comment by jakecarr** [comment]
@trodrigues Hi Trodrigues,

Have you made any progress on this issue?

Thank you.

Jake

**Comment by trodrigues** [comment]
Hi Jake,

apologies for the lack of replies but I was travelling.

So to go back to the beginning of the ticket, the documentation was indeed wrong. The name of the parameter that should be passed down to the `sync` method is `nextSyncToken`.

From what I saw on your last code example, you are using that now, so that should work.

So my next question would be, is that the full example? Are you by any chance extending an object where you might already have the `initial` parameter as well?

You should always send either one or the other.

Unfortunately it seems that even initial=false registers as that parameter being true on our backend, because the existence of the parameter is enough. I've reported this as a bug and will also add some code to prevent that from ever being sent by the SDK.

Other than that I don't see any obvious possible cause for this to fail.

**Comment by trodrigues** [comment]
Oh, and I've also just released a new version which omits sending the sync param to the server if nextSyncToken is defined.

**Comment by jakecarr** [comment]
Hi trodrigues,

Thank you for the reply and investigating this issue!

Here is the code for the 'sync' method of a service I'm using (minus a few console log statements). I'm not great at Angular JS so sorry if there are any stupid mistakes. 

```JavaScript
        sync: function () {
            var client = contentful.createClient({
                accessToken: '87b8b3a7d2709c9a6f5dbcf9eaf7531a5986cdc8757b99f7b208306891ae8924',
                space: 'ecatui8b23wy'
            });
            
            var syncToken = window.localStorage.getItem('syncToken');
            var entriesString = window.localStorage.getItem('entries');
            var entries = JSON.parse(entriesString);
            var options = {}
            if (syncToken === null) {
                options = {initial: true};
            } else {
                options = {nextSyncToken: syncToken}
            }
            client.sync(options)
                .then(function(response){
                
                    response.items.forEach(function (entity) {
                        if(entity.sys.type === 'Entry'){
                            entries[entity.sys.id] = entity
                        }
                        if(entity.sys.type === 'DeletedEntry'){
                            delete entries[entity.sys.id]
                        }
                    })
                    window.localStorage.setItem('entries', JSON.stringify(entries));
                    window.localStorage.setItem('syncToken', response.nextSyncToken);
            }, function(error) {
                console.log("Promise rejected");
                console.log("Error: " + JSON.stringify(error));
            });
        },
```

The object being passed into the sync method is this:

``` JSON
{"nextSyncToken":"w5ZGw6JFwqZmVcKsE8Kow4grw45QdybCmsO3bQZSwrzCiAvDqHTChF7CgcOIFVPDnwlzW8Kww6vDuAnDmj8Qw7YhMkJsLMOHKcKjbTAGwp7DjDDDmMOfasOMwpbDvi_DnMOOGMKawqwKM8KKwp3DgFnCnDJlYQ"}
```

As you can see, there is no initial property in the object I am passing in.

And this is the error I get:

``` JSON
{"sys":{"type":"Error","id":"BadRequest"},"message":"Please specify either the \"initial\" parameter as \"true\" or a valid starting date or the \"sync_token\" parameter with a valid sync token.","requestId":"90a-2086630166"}
```

I tried it after updating contenful.js using bower and it still has the same problem.

Can you see what I'm doing wrong? Let me know if you want me to try anything.

Thank you.

Jake

**Comment by trodrigues** [comment]
Hi Jake,

right, on first sight there is nothing wrong.

Can you give it another try to reinstalling the package with bower? Due to my mistake, the file that is pulled by bower wasn't rebuilt and updated on the new version. It should be fine now.

**Comment by jakecarr** [comment]
Hi trodrigues,

I used 'bower uninstall contentful' and 'bower install contentful' to reinstall the package and unfortunately it still doesn't work. It is now version 1.2.1. For some reason, when I use 'bower list', it lists the Contentful package as 'extraneous', could this have something to do with the issue I'm having?

The options param is set to this:

```JSON
{"nextSyncToken":"w5ZGw6JFwqZmVcKsE8Kow4grw45QdyYTwpVOw6Y1DsOGZA8xwodUEynDosKxG8OqZcK1R2XDjG0reBfDvcOgBMK2IMKVNsKCbsORRcORZRh-w501wq51w4hgXsKrVHTCsVXDgmbDq8KfcXDCt8OKwoDCtA"}
```
and the error I get is this:

```JSON
{"sys":{"type":"Error","id":"BadRequest"},"message":"Please specify either the \"initial\" parameter as \"true\" or a valid starting date or the \"sync_token\" parameter with a valid sync token.","requestId":"405-1389270914"}
```

Thank you.

Jake

**Comment by trodrigues** [comment]
Hi Jake,

I've tried it also with the built version of the file, in the same way that you are using it, and it works fine for me. I really can't understand what the problem might be here.

Can you maybe have a look at the network tab of your browser and check the request that is being sent?

Here's an example of what it should look like: https://dl.dropboxusercontent.com/s/gkym3ghaizll6t5/2015-12-02%20at%2016.59%202x.png?dl=0
