### ISSUE TITLE
Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by stayradiated** [contentful/contentful.js#56]
Hi there,
We are using contentful.js in the browser (via npm and webpack).

On every request to Contentful, we get this warning:
```
Refused to set unsafe header "User-Agent"
```

It looks like contentful.js is trying to overwrite the User-Agent header, which most web browsers do not allow.

**Comment by trodrigues** [comment]
Oh damn, this was definitely an oversight. We'll look at setting a different header or sending it only when being used in node.

**Comment by trodrigues** [comment]
Ok, I've just published v2.1.2 which fixes this issue by sending a custom header.

**Comment by stayradiated** [comment]
Awesome, thanks for the quick response!
