### ISSUE TITLE
Package cannot be installed with npm install

### ISSUE THREAD

**Issue by jakbob** [contentful/contentful.js#57]
When installing version 3.0.2 of contentful in another project using npm install, the process fails with error:

```
> rimraf vendor-node && mkdirp vendor-node && babel node_modules/axios/lib/ --out-dir vendor-node/

'babel' is not recognized as an internal or external command,
operable program or batch file.
```

It seems the postinstall script depends on both axios and babel-cli but as these two are only listed in devDependencies they are not included when running npm install.

**Comment by RuLeZzz1987** [comment]
rimraf vendor-node && mkdirp vendor-node && babel node_modules/axios/lib/ --out-dir vendor-node/

node_modules/axios/lib/ doesn't exist

I've got this error on "npm i contentful"

**Comment by trodrigues** [comment]
Hi there,

sorry for the issues, I'm looking into this.

**Comment by trodrigues** [comment]
Just removed those commands from the postinstall task and pushed a new version. Should be up soon as 3.0.3. Apologies for the issue.

**Comment by trodrigues** [comment]
3.0.3 has been published and fixes the stated issue. Let me know if any other issues occur.

There's still some problems for webpack users but I'll open a separate issue to track that.
