### ISSUE TITLE
Contentful server side calls in angular universal are no longer awaited since version (8.0.1)

### ISSUE THREAD

**Issue by VirMaker** [contentful/contentful.js#642]
Opening separate issue for server side rendering issue originally described [here](https://github.com/contentful/contentful.js/issues/545). On migration from contentful 7.15.2 to 8.1.8. server side (Angular universal) contentful calls no longer complete (awaited?). The call is being executed but the page does not have those results. Looks like this issue was introduced in 8.0.1, works fine with 8.0.0;

Current environment:
Node 15.7
Angular 11.1.1
Contentful 8.1.8

We are trying to move away from 7.15.2 because of axios vulnerabilities:
contentful 1.0.0 - 2.1.2 || 4.0.0 - 5.0.3 || 7.1.0-beta0 - 7.1.0-beta1 || 7.5.0 - 8.0.2 Depends on vulnerable versions of axios

**Comment by fbaba-nibtravel** [comment]
I'm experiencing a similar problem. I haven't read the code to check what's the cause but what we can see is that prior the upgrade (in our case, v8.2.1) the server-side calls are not completed before returning to the browser. This causes api calls on the client-side, thus defeating the purpose of the SSR. 

Just FYI, as recommended by https://github.com/contentful/contentful.js/blob/master/ADVANCED.md#angular-universal, we created our custom adapter to perform what the `ngx-axios-adapter` would do (this lib is not being actively maintained) and this was working prior to the upgrade to latest version.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
