### ISSUE TITLE
OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by rrostt** [contentful/contentful.js#647]
Contentful is using deprecated node apis when dealing with errors.

https://github.com/contentful/contentful.js/blob/38b2f8a73d7518d539b689bfac0732ed3e706232/lib/contentful.js#L106

https://nodejs.org/api/deprecations.html#DEP0066

Also, headers are already sent and can not be changed using setHeader without exception. Possible solution to strip the request object.

**Comment by ngnathan** [comment]
Anyone know if there's a way around this?  Trying to pull contentful data on the server side (with NextJS) using getStaticProps but this seems to be blocking for me on node 12.

**Comment by mferryRV** [comment]
Same issue on Node 16

**Comment by makinwab** [comment]
Fixed by #648
