### ISSUE TITLE
Auto-generated slug not caught by unique validation

### ISSUE THREAD

**Issue by jackherizsmith** [contentful/contentful.js#659]
## Expected Behavior

Validation should prevent auto-generated slugs in a content model from being duplicated when this field is required to be unique.

## Actual Behavior

Duplicate, auto-generated slugs are allowed if left untouched by the user, which effectively ensures bugs using the API.

## Possible Solution

Use the existing validation when there is user input, on auto-generation. Alternatively append random digits e.g. /example-slug-4724

## Steps to Reproduce

1. Create a content model with short text entry title field, and slug field with unique field validation
1. Create content document with title and slug
1. Create a second document with the same title, save second document with duplicate slug
1. A query using slug field of one value will return both results.

## Context

This is necessary to prevent multiple duplicate documents being returned when using the 'unique' slug field to collect documents.

**Comment by marcolink** [comment]
Hi @jackherizsmith,
Thanks for reporting this. It would be great if you could re-post this issue on the [community slack](contentful-community.slack.com
) for visibility. This repo is mainly focused on the content delivery API.
