### ISSUE TITLE
what are 'errors' and 'includes' properties in the getEntries() response object?

### ISSUE THREAD

**Issue by chriswu14** [contentful/contentful.js#69]
this is what my client code look like, everything works fine I get my content but when I am learning based on the API documentation I cannot find any info about these two objects.

`var client = contentful.createClient({
      accessToken: '****',
      space: '****'
    });
    client.getEntries().then(entries => {
      console.log(entries)
    })`

the response is
![image](https://cloud.githubusercontent.com/assets/5129085/14133552/f1b03e1e-f69b-11e5-84dc-c5196bdcbb5c.png)

**Comment by trodrigues** [comment]
Hi @chriswu14,

these are properties returned by the Contentful REST API.

The `includes` property doesn't really need to be there, as it includes entries or assets that might be linked from the ones included in the `items` array. Those links are resolved automatically, so the includes array doesn't need to be exposed. I'll look into removing it.

As for the `errors` property, it might include errors which occurred in retrieving some of the entries. I will add this to the documentation.

**Comment by chriswu14** [comment]
Thanks for the reply, I figured later on that I started my account with a prefilled sample one and deleted some of the author content may be there was some linking between them.

**Comment by HauntedSmores** [comment]
@trodrigues Hey, I know this is an old issue but theres still some inconsistencies, at least from my understanding, with the `includes` array and its still being sent in the response from the SDK.

Its described [here](https://www.contentful.com/developers/docs/concepts/links/) as the place where linked asset/entry data is resolved (i.e. urls). The language is very vague, for instance:

> linked items are placed in the includes array, when not already fetched in the items array.

And from [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items)

>If the standard items array has not already retrieved the linked entries, they will be in the includes.Entry array. Linked assets are inside the includes.Asset array.

What the hell is "when not already fetched in the items array" or "if the standard items array has not already...."?.

If Im writing an app, I need to know exactly where in the response Im getting my data. Is it gonna be in `includes[]` or in the actual items array object? It looks like both for me. But my app is currently looking for nested linked stuff in the objects inside the items array. This is what made the most sense to me - each item in `items[]` has a linked asset/entry so I should be looking in `items[x].fields.my_linked_field[x].fields` for my linked data.

**Comment by Khaledgarbaya** [comment]
Hi @HauntedSmores,
If the entry is already in the items array it does not make sense to include in the `includes` array this will lead to duplication of content and a bigger payload.
When resolving the links you need to look into both `items` and `includes`.
That's what we do in the SDK already since we resolve the links for you.
You can check the code [here](https://github.com/contentful/contentful.js/blob/0833986174bf64e16793ccba543bfce86762a6c9/lib/entities/entry.js#L108).

Best,
Khaled

**Comment by HauntedSmores** [comment]
@Khaledgarbaya Thanks a lot for the clarification. I also had the same explanation from contentful support, who are always on the ball. Great work on the SDK and the platform in general. My team let me run with Contentful for my current project and I think I may have successfully killed WordPress around here. Thanks for that!
