### ISSUE TITLE
Add function list/documention

### ISSUE THREAD

**Issue by piotrowski** [contentful/contentful.js#7]
The current Contentful Content Delivery API documentation is nice to learn about the concepts behind Contentful and how to use the js library to achieve specific tasks. But it's not very helpful if you want to find out what the js library does or does not support. 

A short list or documentation of the functions that are or are not supported, linking the particular paragraph in the Content Delivery API documentation would be a great start for new users to find out, what we can or can't do with the current js implementation.

(Probably enough to just add it to the readme for now)

**Comment by trodrigues** [comment]
Fixed by documentation of new 3.x series.
