### ISSUE TITLE
The node xhr adapter throws 'window is not defined'

### ISSUE THREAD

**Issue by StuartHarris** [contentful/contentful.js#70]
This line throws an exception `window is not defined` when called server-side (e.g. when using `client.sync()` in node.js v5.10.1):
https://github.com/contentful/contentful.js/blob/2b84d596c5f425c4b354e4844a7d843a2268ed57/vendor-node/adapters/xhr.js#L8

putting this before line 8 fixes the issue
``` js
var window = global || window;
```
Would you like me to submit a PR?

**Comment by trodrigues** [comment]
Hello Stuart,

no, that shouldn't be necessary, because the XHR adapter on Axios (the library we use for HTTP requests) should never be loaded on a server environment (you can see the code that defines that [here](https://github.com/contentful/contentful.js/blob/master/vendor-node/core/dispatchRequest.js#L25))

Is your environment possibly trying to emulate the same environment as a browser, where `XMLHttpRequest` would be defined as a global but other expect browser variables such as window wouldn't be defined?

**Comment by StuartHarris** [comment]
Hey Tiago,

Thanks for your quick response. Yes, I'm using PouchDB and it appears that it does emulate XMLHttpRequest :-(
The same thing happens with the management api `contentful.js`.

Can you think of a safer way to determine whether you're server-side or client-side?

Thanks,
Stu

**Comment by trodrigues** [comment]
Hi Stuart,

I had a look through their code and it doesn't seem like that is exactly the case. They seem to also have a different request adapter whether you're on the browser or or on Node (which they seem to inject on the build).

But even if you were using their browser build it doesn't exactly seem like that's something that they are doing.

I ran a quick test with the following node script and didn't run into this issue:
```
var contentful = require('contentful')
var PouchDB = require('pouchdb')
var db = new PouchDB('stuff')
var client = contentful.createClient({
  // This is the space ID. A space is like a project folder in Contentful terms
  space: 'developer_bookshelf',
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: '0b7f6x59a0'
})
// This API call will request an entry with the specified ID from the space defined at the top, using a space-specific access token.
client.getEntry('5PeGS2SoZGSa4GuiQsigQu')
.then(function (entry) {
  console.log('got entry', entry)
  var eo = entry.toPlainObject()
  eo._id = entry.sys.id
  db.put(eo)
  db.get(entry.sys.id)
  .then(function (indb) {
    console.log('got entry in db', indb)
  });
})
```

The above script works perfectly, entirely on node using both contentful.js and PouchDB, without the error you described.

Can you give me some more information about your environemnt and how you're trying to run your code?

**Comment by StuartHarris** [comment]
Hey Tiago,

Thanks for investigating this :-). I should have mentioned that we were also using `express-pouchdb` and it appears that was the issue. I ripped it out now and am using CouchDB on the server instead, and the problem has now gone away (we were also having problems syncing a client PouchDB when using Express-pouchdb).

Thanks for your help - much appreciated.
Stu
