### ISSUE TITLE
Subtitles not being pulled by the contentful js 

### ISSUE THREAD

**Issue by ir2pid** [contentful/contentful.js#710]
## Expected Behavior

We have titles and subtitles in our contentful form. 
The form subtitles don't get pulled when we run the contentful js file.
Title and other form fields are getting pulled.

## Actual Behavior

Expect subtitles to appear.

![image](https://user-images.githubusercontent.com/907075/115256101-3898b980-a12f-11eb-95b9-d12432df5c70.png)

## Environment

-   **Language Version**: v12.22.1
-   **Package Manager Version**: 6.14.12
-   **Operating System**: Mac osx 10.15.7
-   **Package Version**: 8.3
-   **Which API are you using?**: Delivery

**Comment by marcolink** [comment]
Hi @ir2pid 👋 

Sorry for the late response, would you be able to provide some code for your exact request? Also, have you tried to trigger a direct API call to compare responses?

**Comment by marcolink** [comment]
Closing this for now due to inactivity.
Please feel free to re-open it again.
