### ISSUE TITLE
add Metadata property in Entry interface

### ISSUE THREAD

**Issue by 37108** [contentful/contentful.js#711]
## Expected Behavior
i try to get Contentful tag via metadata.  
`getEntry` returns generic Entry interface and there is a metadata property.

```typescript
const greeting = await client.getEntry('xxx');

// no error to get metadata
const meta =  greeting.metadata;
```

## Actual Behavior
i got a "property does not exist" error.

```typescript
const greeting = await client.getEntry('xxx');

const meta =  greeting.metadata;
// Property 'metadata' does not exist on type 'Entry<unknown>'.ts(2339)
```

## Possible Solution
add the new Metadata optional Property into Entry interface.

https://github.com/contentful/contentful.js/blob/38b2f8a73d7518d539b689bfac0732ed3e706232/index.d.ts#L81-L86

## Steps to Reproduce

1. write code like below

```typescript
const greeting = await client.getEntry('xxx');

const meta =  greeting.metadata;
// Property 'metadata' does not exist on type 'Entry<unknown>'.ts(2339)
```

same thing do with `getEntries`

```typescript
const res = await client.getEntries({
  content_type: 'greeting',
});

const meta = res.items[0].metadata;
// Property 'metadata' does not exist on type 'Entry<unknown>'.ts(2339)
```

## Context
i want to avoid using any type. ignoring ts2339 error, i need to write code like `const res: any = await getEntry()` and this turns res type to any.

## Environment

-   **Language Version**: v15.4.0
-   **Package Manager Version**: yarn 1.22.10
-   **Browser Version**: Google Chrome Version 89.0.4389.128
-   **Operating System**: Darwin Kernel Version 19.6.0 x_86_64
-   **Package Version**: contentful sdk 8.3.0
-   **Which API are you using?**: Delivery

**Comment by TheJotob** [comment]
Hi. I'm running into the same issue. Is there any plan when this will be addressed, since we would really like to work with the new Tags-Feature but because of this issue it is currently not possible

**Comment by ruderngespra** [comment]
Hey @37108 @TheJotob, thanks for reporting this! We added type support for metadata on entries and assets and hope that should fix the issue for you (https://github.com/contentful/contentful.js/commit/ddb4711f6e113b1e16ffc1961912e8b1c09c469c). Let me know if you still run into problems!
