### ISSUE TITLE
Pulling in data in grunt

### ISSUE THREAD

**Issue by DusanMilko** [contentful/contentful.js#72]
I'm trying to pull in the data in grunt, I end up getting the below: I do currently have entries that are article type.

```
{"_c":[],"_s":0,"_d":false,"_h":0,"_n":false}
```

Code used:
```
grunt.registerTask('getData', 'A sample', function(arg1, arg2) {
    var contentful = require('contentful');

    content = contentful.createClient({
      space : '#######',
      accessToken : '##################'
    }); 

    var value = content.getEntries({
      content_type : 'article'
    })
    .then(function(entries) {
      grunt.log.writeln('testing then');
      grunt.file.write('./articles.json', JSON.stringify(entries) );
    });
    grunt.log.writeln( JSON.stringify(value) );
});
```

The code in the *then* never gets triggered

**Comment by trodrigues** [comment]
Hi there,

where are you getting that output? Is it on the logging at the end of this code snippet?

The `getEntries` method returns only a promise, so trying to log that wouldn't really be useful for any purpose.

Regarding the `then` method, if the function you are passing to it never gets called, it could mean that there was an error fetching your content from the server. In that case you should try handling the error case, such as:

```js
content.getEntries({
  content_type : 'article'
})
.then(function(entries) {
  grunt.log.writeln('testing then');
  grunt.file.write('./articles.json', JSON.stringify(entries) );
}, function(error) {
  grunt.log.writeln(error)
});
```

Keep in mind that using `JSON.stringify` on collections of entries is not always a good idea if you have entries that link to each other. You can use the [stringifySafe](https://contentful.github.io/contentful.js/contentful/3.3.5/Entities.html#.EntryCollection) method present in the returned object to avoid any circular dependencies problems.

**Comment by DusanMilko** [comment]
Thanks for the quick reply.
I tried using the error handling and no error gets logged. Also the then doesn't log out 'testing then'. Neither is working.

**Comment by seripap** [comment]
You need to specify in grunt that the promise is asynchronous.

```js
var done = this.async();

content.getEntries({
 content_type : 'article'
}).then(function(entries) {
  grunt.log.writeln('testing then');
  grunt.file.write('./articles.json', JSON.stringify(entries) );
  done();
}, function(error) {
  grunt.log.writeln(error);
  console.log(error);
  done(false);
});
```

**Comment by DusanMilko** [comment]
Thank you, that worked.
