### ISSUE TITLE
"The access token you sent could not be found or is invalid" for Preview Api Key

### ISSUE THREAD

**Issue by RezaRahmati** [contentful/contentful.js#721]
## Expected Behavior
The client retrieve contents with no error

## Actual Behavior
The client return this error
```
Uncaught (in promise): Object: {"sys":{"type":"Error","id":"AccessTokenInvalid"},"message":"The access token you sent could not be found or is invalid.","requestId":"cdc52913-f514-4350-96e2-d184f76bd93a"}
```

## Steps to Reproduce
- Create a new space (I am using free tier)
- Create a sample content type and content
- Read contents by Delivery Api Key
- Confirm you are able to read content (empty array if content is in draft mode, and filled array when content is pubslished)
- Make sure content is in Draft
- Update api key to preview
- See the error

## Environment

-   **Language Version**:  14.15
-   **Package Manager Version**:  6.14
-   **Browser Version**: 
-   **Operating System**: 
-   **Package Version**:  8.3.1
-   **Which API are you using?**:  Preview

**Comment by dkast** [comment]
I had the same issue, it seems that you have to define the host on your client connection

```js
const client = createClient({
    space: process.env.NEXT_PUBLIC_SPACE_ID,
    accessToken: preview
      ? process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN
      : process.env.CONTENTFUL_PUBLIC_ACCESS_TOKEN,
    host: preview ? "preview.contentful.com" : "cdn.contentful.com"
  });
```

**Comment by itsjavi** [comment]
I think the client should have a `preview: boolean` flag instead of the developers having to define the host, 
which is very inconvenient and it's not even referenced in the docs.

**Comment by marcolink** [comment]
Thanks @itsjavi - that's a valid idea!
I will add it as a feature request! If you feel like- you can also always create a PR for it :)
