### ISSUE TITLE
Delivery API JSON parser fails when two entries reference each other

### ISSUE THREAD

**Issue by smadan** [contentful/contentful.js#739]
## Expected Behavior

Create entry A and entry B. Add a link to B in A and vice versa. Use the Contentful Javascript delivery API and call getEntries(). Observe JSON parsing error.

In particular, if you print out the response, you'll see entry A looks something like this:

{"content": [{"data": [Object], "marks": [Array], "nodeType": "text", "value": "Link to test post B"}], "data": {"target": {"fields": [Object], "metadata": [Object], "sys": [Object]}}, "nodeType": "entry-hyperlink"}

If you then inspect data.target, you'll see that it tries to embed post B entirely in there, which then itself tries to embed all of post A inside its data.target field.

## Actual Behavior

Should not throw an error.

## Possible Solution

Don't embed entire posts. Embed some kind of reference or ID.

## Steps to Reproduce

Create entry A and entry B. Add a link to B in A and vice versa. Use the Contentful Javascript delivery API and call getEntries(). Observe JSON parsing error. "Unhandled error RangeError: Maximum call stack size exceeded"

## Context

Can't link posts to each other.

## Environment

Node version 12. Also doesn't work on 15.
NPM 7.5.2.
Contentful v8.2.1.
Language: Typescript
Environment: Using a Google Cloud Function running locally on my MacOS machine.

**Comment by smadan** [comment]
Looks like this has come up multiple times before. Like some of the other folks that ran into this, I ended up using safe-json-stringify to get around the problem. Not a great solution because it adds an extra JSON parse step. Would love a better solution here.

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.
