### ISSUE TITLE
Cannot install as a dependency of itself

### ISSUE THREAD

**Issue by vuk** [contentful/contentful.js#75]
I've tried installing contentful for nodejs and when i do 

`npm install contentful --save` 

it tells me 

`npm ERR! Refusing to install contentful as a dependency of itself`

I've tried multiple versions and they all give same error down to 3.2.0. 

Any idea why?

Additional info:

`npm ERR! node v4.4.5 
 npm ERR! npm  v3.9.3`

**Comment by trodrigues** [comment]
The only reason why you'd get such an error is if you'd clone this repository and tried to run that command inside of it.

Can you give me some more information about the directory you are running this on?

Also, can you try running it in a fresh, clean directory?

**Comment by vuk** [comment]
I've just created new Express app from new project menu in PhpStorm 

Here is package.json 

`{
  "name": "contentful",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "request": "^2.72.0",
    "serve-favicon": "~2.3.0"
  },
  "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-ts": "^5.5.1",
    "grunt-typedoc": "^0.2.3"
  }
}
`

**Comment by trodrigues** [comment]
Ah, I see your problem and it's somehow obvious. You've created a package with the name `contentful` and you're trying to install our SDK, which is also called `contentful` as a dependency of it, so the error message you get makes perfect sense.

If you just change the name of your project it should work fine.

**Comment by vuk** [comment]
Sorry about that. Yes, obviously
