### ISSUE TITLE
Clarification: Querying on Linked entries

### ISSUE THREAD

**Issue by bringking** [contentful/contentful.js#78]
I am trying to use this library to filter a query by a Linked item. Is this possible? For example -

Given - 
_Post_ can have many _Categories_

```js
contentful.getEntries({ content_type: 'post', include: 1, 'fields.category[0].title': 'Marketing'})
```

I would like to be able to query all Posts that have the Marketing category as their first category.

**Comment by bringking** [comment]
Actually figured this out - You need to make two calls

```js
client.getEntries({content_type: 'category'}).then((resp) => {
      let cat = resp.items
        .filter((item) => item.fields.title === 'Marketing');

      if (cat.length) {
        const matchingCategory = cat[0];
        return client.getEntries({
            content_type: type, 
            include: 1, 
            'fields.category.sys.id': matchingCategory.sys.id
        });
      }
});
```

**Comment by stickyhands** [comment]
@bringking is that still the only way to do so ?

**Comment by Khaledgarbaya** [comment]
@stickyhands if you have something with multiple categories, you can have a field in your entry called categories or type slug. and with one request like this

```js
client.getEntries({
            content_type: 'post', 
            'fields.category[in]': 'marketing,anotherCategory'
        });
```
