### ISSUE TITLE
Is there any way to get content type's data  (dropdown data)?

### ISSUE THREAD

**Issue by sankar9659** [contentful/contentful.js#782]
Hi, I'm working on contentful to create blog posts.
I have created a field named with category with dropdown data, like the below image.
I have created more blogs for each categories (Ex: game has 5 blogs, Tour has 10 blogs and etc).
I want to show the list of all categories with content counts,
Is there any possible to get all of the categories with content count? ( I can get it by getting all blogs using this query
`const res = ContentfulService.getEntries({ content_type: 'blog'})`

 then I grouped with category, but to get the category only, I dont want to get all of the blogs.)

And tried this method but I cant get exact response,
`const res = await ContentfulService.getEntries({
      content_type: 'blog',
      select: 'fields.category',
    }).then(response => {
      console.log('response...........', response)
    })`

![image](https://user-images.githubusercontent.com/58698022/120515032-83bf1100-c3eb-11eb-8b93-164eee041ef9.png)

Please let me know if there is a solution.
Thanks

**Comment by marcolink** [comment]
Hi @sankar9659 👋 
I think you found the best solution on the REST API already. I can imagine that you can achieve such queries with our [GraphQL API](https://www.contentful.com/developers/docs/references/graphql/). closing this for now, but please feel free to re-open it again, or post the question in the [community slack](contentful-community.slack.com
) for visibility.
