### ISSUE TITLE
[Need help] images show download prompt when browser not supporting webp

### ISSUE THREAD

**Issue by Stupidism** [contentful/contentful.js#809]
## Expected Behavior

Fallback to the default format if the client browser doesn't support `webp` like [what nextjs does](https://nextjs.org/docs/basic-features/image-optimization).

## Actual Behavior

Because [safari browsers doesn't support](https://caniuse.com/webp)

![image](https://user-images.githubusercontent.com/5801015/122501216-d40eb380-d026-11eb-94ad-8a0d51c3ad9d.png)

It shows a download prompt instead.

## Possible Solution

1. images CDN support this fallback by default
2. add an option to support fallback like `<image-url>?fm=webp&fallback_fm=png`
3. no matter what fm specified, add an option to use webp first: `<image-url>?fm=png&prefer_fm=webp`

## Steps to Reproduce

Just access this URL with a non `macOS Big Sur` safari browser.

https://images.ctfassets.net/7n7vfqlomamo/5ctRst5nKQq4o8a6eBm1Wx/63d90bb3ed6fc8a3dedc06bfcd086534/Avatar_for_Bow_Capital?w=64&h=64&fm=webp

If you don't have such a browser. You can use the online feature [`caniuse`](https://caniuse.com/webp) provides:

![image](https://user-images.githubusercontent.com/5801015/122501404-35cf1d80-d027-11eb-8af8-4b86cd39318b.png)

## Context

Enough I think

## Environment

Safari browser (except macOS Big Sur)
or IE broswer

**Comment by marcolink** [comment]
Hi @Stupidism,
You can achieve a fallback behaviour by using a [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element and define multiple sources.
