### ISSUE TITLE
Does the contentful.js Javascript API support Link Resolution?

### ISSUE THREAD

**Issue by maxkwallace** [contentful/contentful.js#82]
You link to it in the README (https://www.contentful.com/developers/docs/concepts/links/), but does this Javascript library support the `include` parameter, as documented at https://www.contentful.com/developers/docs/concepts/links/#linked-entries ?

I can't find anything about this in the documentation for this library.

**Comment by Khaledgarbaya** [comment]
Hi @maxkwallace 

Yes contentful.js support link resolution and it is set to true by default. Also it will append all the data automatically to the resolved object.
the link resolution can go up to 10 level deep. you can set in the query param using the include key.
e.g `{include:6}` when getting entries etc. 

for more info you can check : https://contentful.github.io/contentful.js

Best,
Khaled

**Comment by maxkwallace** [comment]
@Khaledgarbaya If that's the case, I'd recommend updating your documentation. On https://contentful.github.io/contentful.js/contentful/3.4.3/ContentfulClientAPI.html I see "Object with search parameters. In this method it's only useful for `locale`."

Could you provide an example of what an API call with `included: ... ` would look like through this API? To the best of my understanding, I did everything you suggested this morning, and I still wasn't able to get it to work.

My code looks like:

`Contentful.createClient(config.APP.contentful).getEntry(config.APP.platformContentEntryId, { include: 10 })`

**Comment by Khaledgarbaya** [comment]
Hi @maxkwallace ,
The documentation is is correct.
The link resolution is done client side and it is done when you request collection of entries and not a single entry. 
example : https://contentful.github.io/contentful.js/contentful/3.4.3/ContentfulClientAPI.html#.getEntries

**Comment by maxkwallace** [comment]
@Khaledgarbaya thanks! That's helpful. Now I'm able to do what I wanted. Obviously it's up to you whether to update the documentation, but as a point of feedback-- I found it unclear, and it didn't answer my question (which is why I opened an issue in the first place).

**Comment by Khaledgarbaya** [comment]
Happy to help.
And yeah I am planing to make the documentation more clear especially about link resolution and how it is done client side

**Comment by cwhitten** [comment]
Trying to follow this but it doesn't look like `getEntities` is a valid interface. Has it been removed?

**Comment by stephenhmarsh** [comment]
you would think nearly 2 years after this issue was opened, `getEntry` would have parity with `getEntries` especially in something as useful as link resolution.  why not????????

instead you have to do this, which is rather annoying:

```
client.getEntries({'sys.id': '<some specific content id>', include: 10})
  .then(function (entries) {
    var entry = entries.items[0]
 
...
```

**Comment by axe312ger** [comment]
@stephenhmarsh  no worries, we have it in our backlog. Stay tuned :)

**Comment by AndrewEckart** [comment]
Just started using Contentful, immediately ran into this issue and wasted quite a while trying to understand why I could only resolve links with `getEntries` and not `getEntry`. Having to query for a single entry id rather than retrieving the desired entry directly is very unintuitive. Hopefully this is resolved soon.

**Comment by sarneeh** [comment]
Yup. Ran into this issue too. Hope this will be implemented 😄

**Comment by axe312ger** [comment]
We will implement it soon :) Stay tuned 🙈

**Comment by sarneeh** [comment]
Woohoo! Thank you! 🎉

**Comment by phoebeschmidt** [comment]
@sarneeh just a heads up that this is a breaking change and due to some small hiccups it's not quite released yet. But it will be soon, stay tuned!

**Comment by sarneeh** [comment]
@phoebeschmidt Sure, no problem. Just wanted to share my gratitude that this thing is getting fixed 😄

**Comment by phoebeschmidt** [comment]
This is included in the 7.0.0 release 🎉

**Comment by markmssd** [comment]
Thanks @phoebeschmidt ! Heads-up: It seems like https://github.com/contentful/contentful.js/blob/master/ADVANCED.md#link-resolution isn't updated yet.

**Comment by Khaledgarbaya** [comment]
We removed the outdated section

**Comment by rafaelrinaldi** [comment]
Thanks for adding this in.
