### ISSUE TITLE
Transpile into ECMAScript Module

### ISSUE THREAD

**Issue by gromovich** [contentful/contentful.js#833]
## Expected Behavior

Transpile contentful.js into ECMAScript module.

## Actual Behavior

contentful.js is transpiled into CommonJS module.

## Context

I'm using your library in an [Angular](https://github.com/angular/angular) project and it outputs warning when I try to build it:

```
Warning: contentful.ts depends on 'contentful'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

You can find more information here:

[Configuring CommonJS dependencies](https://angular.io/guide/build#configuring-commonjs-dependencies)

```
It is recommended that you avoid depending on CommonJS modules in your Angular applications. Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use ECMAScript modules in your entire application.
```

[How CommonJS is making your bundles larger](https://web.dev/commonjs-larger-bundles/)

## Environment

-   **Package Version**: 8.4.2

**Comment by Fedeorlandau** [comment]
Same thing to get this working with svelte kit https://github.com/sveltejs/kit/issues/928
