### ISSUE TITLE
Dereferencing objects from different pages

### ISSUE THREAD

**Issue by Munhoziii** [contentful/contentful.js#88]
There is a limitation when an object in a page references another object in another page. Imagine you have (1000 + x) entries connected to each other, even if you add the `include` parameter in your call the response length limit won’t allow all the objects to be returned – so the resulting graph will be missing the + x entries, making the references to it break.

There is also the case of needing a single instance of each object in the resulting graphs from requests: If you get a dereferenced graph from each page and objects from multiple pages reference a single object Y then your library will return one instance of Y for each dereferenced graph, meaning in the end we will have more than one Y in the final graph (comprised of all the Contentful entries that were results to the request).

**Comment by Khaledgarbaya** [comment]
Hi @Munhoziii ,
I am preparing a meeting with the team to tackle this use case and I will get back to you asap, by tomorrow. 
Hopefully will come up with a solution that suites your needs.
Best,
Khaled

**Comment by Khaledgarbaya** [comment]
Hi There,

We now have a method `parseEntiries` that accepts a raw json data and parse it into entries object with link resolution. Your part now is to get all the data and make sure always to concat both `data.items` and `data.include` for each page and then pass it to the client using `client.parseEntites(data)` and you will get a parsed data set with all the link resolution done for you.

Best,
Khaled
