### ISSUE TITLE
Contentful.js doesn't work with ESM bundlers

### ISSUE THREAD

**Issue by angelmeraz** [contentful/contentful.js#917]
## Expected Behavior
Contentful.js SDK works with ESM bundlers.

## Actual Behavior
Getting `undefined` when importing `contentful` package.

`import contentful from 'contentful';`

## Steps to Reproduce
1. Start new SvelteKit project https://kit.svelte.dev
2. Add contentful: `npm i -D contentful`
3. Import it somewhere in your app: `import contentful from 'contentful';`

## Environment

-   **Language Version**:  Node v14.15.4
-   **Package Manager Version**: NPM 6.14.10
-   **Operating System**: macOS Big Sur v11.5.2
- `Darwin **** 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64`
-   **Package Version**:  `"contentful": "^9.0.0",`
-   **Which API are you using?**: Trying to use Contentful JavaScript Content Delivery Library

**Comment by filsuck** [comment]
If you look at dist folder there is es-modules, try changing import contentful from 'contentful' to this one.


```
import { createClient } from 'contentful'

const contenful = createClient({
  space: '',
  accessToken: '',
})
```

**Comment by angelmeraz** [comment]
`import * as contentful from 'contentful';`
and
`import { createClient } from 'contentful';`

... seem to work!

**Comment by einarpersson** [comment]
For me 

````typescript
// Works on dev, but breaks when running npm run build
import { createClient } from 'contentful' 
````

````typescript
 // Works both when running dev and build
import contentful from 'contentful'
const { createClient } = contentful
````

**Comment by ajeffrey** [comment]
for anybody else facing this problem, I found a solution:

```typescript
import contentful from 'contentful';
import * as contentful2 from 'contentful';

const createClient = contentful ? contentful.createClient : contentful2.createClient
```

this snippet works on both frontend and backend.
