### ISSUE TITLE
Add more information/examples on Preview API

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful.js#93]
As a User I would like to have more examples on how to use the preview API.

**Comment by axe312ger** [comment]
Afaik the only thing that needs to be done here is to change the host config option to `preview.contentful.com`

Anything else @Khaledgarbaya?

**Comment by Khaledgarbaya** [comment]
@axe312ger maybe check for drafts etc

**Comment by shahzadhassan10** [comment]
Is there any way to POST content to a content_type using the javascript SDK? I want to create records with couple of fields from client side. I can only see get functions no post function in the documentation.

**Comment by axe312ger** [comment]
@shahzadhassan10 I assume u are fresh to github. Next time feel free to open a new issue for your question. I'll answer anyways: 

This SDK can't POST data, you are looking for this: https://github.com/contentful/contentful-management.js

**Comment by phoebeschmidt** [comment]
@axe312ger did you mean to comment on https://github.com/contentful/contentful.js/issues/331 ? :)

**Comment by axe312ger** [comment]
@phoebeschmidt nope, he just removed his comment here after I replied 🙈
