### ISSUE TITLE
p-throttle export error preventing usage

### ISSUE THREAD

**Issue by gregorvand** [contentful/contentful.js#938]
I am using prescribed ES6 usage with the latest build, so:

```
import { createClient } from 'contentful'


function hello() {
  let client = createClient({
    space: 'developer_bookshelf',
    accessToken: '[token]'
  })

  client.then(result => {
    console.log(result)
  })
};
```

However getting this webpack error:

```
ERROR in ./node_modules/contentful-sdk-core/dist/index.es-modules.js 335:9-18
"export 'default' (imported as 'pThrottle') was not found in 'p-throttle'
```

Is this known / any workarounds?

**Comment by gregorvand** [comment]
likely local build issue

**Comment by mattbatman** [comment]
@gregorvand I think we're hitting the exact same issue you did. We're trying to build with React on Rails, which I think uses webpack. Did you have an advice? Do you remember what you did to get around this?
