### ISSUE TITLE
Make Contentful.js configurable on how it construct Promises

### ISSUE THREAD

**Issue by Khaledgarbaya** [contentful/contentful.js#94]
As a user I would like to have a way to configure contentful.js to use a custom promise library

As an example, this is how it would work:

``` js
var BPromise = require('bluebird');

var client = contentful.createClient({
  // ...
  Promise: BPromise
});

// Now client.getEntry('...') would return a Bluebird promise
```

**Comment by marcolink** [comment]
With Microsoft dropping support for **Windows 7/IE11** on **7. of Feb 2020**, 
using `contentful.legacy.min.js` for projects who still need to support it should be sufficient.


Will close this issue for now.
