### ISSUE TITLE
Can't import contentful in to react native project

### ISSUE THREAD

**Issue by DanielApt** [contentful/contentful.js#96]
Hi there,

I am extremely excited about using contentful for my project, but I can't get the JS library to work in a react-native project.

I get the following error:
<img width="375" alt="screen shot 2016-10-10 at 16 10 44" src="https://cloud.githubusercontent.com/assets/52545/19240905/5caf27c4-8f04-11e6-8dd6-dbf5e08a6c05.png">

I have tried the following approaches:

``` js
import contentful from 'contentful'; 
// or
var contentful = require('contentful');
```

You can reproduce the bug by going to [this repo](https://github.com/DanielApt/ContentfulReact/) and following the steps I have provided.

Help would be greatly appreciated.

**Comment by Khaledgarbaya** [comment]
Hi @DanielApt ,
I already answered your question in StackOverFlow http://stackoverflow.com/questions/39961577/import-contentful-in-to-react-native/39966439#39966439

Does that help ?

Best,
Khale

**Comment by DanielApt** [comment]
Thank you for help! It all works now :D

I would suggest it might be worth adding that to the documentation somewhere, or have I missed this somewhere?

**Comment by Khaledgarbaya** [comment]
Like I mentioned before I think there was something wrong with your setup, I invite to check other example using contentful.js like this [one](https://github.com/contentful/gallery-app-react)

**Comment by jariwalabhavesh** [comment]
@Khaledgarbaya : Latest version is not working with react-native. It has some dependency issue which doesn't allow react-native app to run.

**Comment by Khaledgarbaya** [comment]
H @jariwalabhavesh, can you share a small project with the issue?

**Comment by jariwalabhavesh** [comment]
@Khaledgarbaya : Sure  i will do

**Comment by jariwalabhavesh** [comment]
@Khaledgarbaya : here is a small project which you ask for https://github.com/jariwalabhavesh/contentul-issue-rn
just clone and npm install

Project has two branch/
1. master
which has latest(v7.6.0) version of contentful and not working in react-native project

2. working 
which has v3.6.4 contentful and working in react-native project

Please let me know if you need anything else. I had also written information on project readme.md. I am also attaching error screenshots for other dev as well how it looks in react-native.
![Simulator Screen Shot - iPhone X - 2019-06-06 at 11 26 58](https://user-images.githubusercontent.com/10993666/59011069-135b7480-8851-11e9-8b27-9d03e9dfe3f9.png)
![Simulator Screen Shot - iPhone X - 2019-06-06 at 11 25 32](https://user-images.githubusercontent.com/10993666/59011078-19515580-8851-11e9-83f9-baaaf8dbd8f9.png)


Actually, i am using v3.6.4 in my project but now I need support with the environment in contentful which not supported in v3.6.4 so I have to upgrade to the latest version of contentful but the latest version is not working in react-native. 

can you provide and working solution for v3.6.4 or you guys can fix lastest version issue with react-native.?

**Comment by jariwalabhavesh** [comment]
@Khaledgarbaya : any update on an issue?

**Comment by Khaledgarbaya** [comment]
Hey @jariwalabhavesh still looking into it. I will post an update soon

**Comment by Khaledgarbaya** [comment]
Hey Folks,
@jariwalabhavesh, Thanks a lot for your sample project.
I made a PR that fixes the issuehttps://github.com/jariwalabhavesh/contentul-issue-rn/pull/1.

React Native somehow is loading the node bundle. This change makes sure that RN picks the right bundle

**Comment by Khaledgarbaya** [comment]
For reference, we have this workaround in the `troubleshooting section` https://github.com/contentful/contentful.js#troubleshooting

**Comment by jariwalabhavesh** [comment]
@Khaledgarbaya : Thanks a lot.

**Comment by andreipfeiffer** [comment]
@Khaledgarbaya do you know how can we add TS typings/intellisense when importing from `contentful/dist/contentful.browser.min.js`?

**Comment by thomashagstrom** [comment]
@andreipfeiffer @Khaledgarbaya The workaround might include this in the TypeScript section:

```typescript
import {EntryCollection, ContentfulClientApi} from 'contentful';
// @ts-ignore
import {createClient} from 'contentful/dist/contentful.browser.min.js';

const client: ContentfulClientApi = createClient({
    space: Env.CONTENTFUL_SPACEID,
    accessToken: Env.CONTENTFUL_TOKEN,
  });
```

**Comment by thomashagstrom** [comment]
I still didn't get this to work properly and opted for REST calls and TypeScript types from `contentful` SDK @andreipfeiffer @Khaledgarbaya 

```typescript
import axios from 'axios';
import {EntryCollection} from 'contentful';

import Env from '../Env';

const contentfulApi = 'https://cdn.contentful.com';

/**
 * Default locale used in contentful calls
 *
 * @see {@link getContentfulEntries}
 * @constant
 */
export const ContentfulLocale = 'sv';

/**
 * @typedef ContentfulProps
 * @param locale optional locale to use. Default is {@link ContentfulLocale}
 * @param entryType content type in contentful model
 */
type ContentfulProps = {
  entryType: string;
  locale?: string;
};
/**
 * Get entries from Contentful content API
 * @param props See {@link ContentfulProps}
 */
export const getContentfulEntries = async <T>(
  props: ContentfulProps,
): Promise<EntryCollection<T>> => {
  const client = axios.create({
    baseURL: `${contentfulApi}/spaces/${Env.CONTENTFUL_SPACEID}/environments/master/entries?`,
    timeout: 1000,
    headers: {Authorization: `Bearer ${Env.CONTENTFUL_TOKEN}`},
  });

  const result = await client.get<EntryCollection<T>>(
    '&content_type=' + props.entryType,
  );

  return result.data;
};

export default getContentfulEntries;

```
