### ISSUE TITLE
The "Sys" type doesn't show the `updatedBy` or `publishedBy` fields

### ISSUE THREAD

**Issue by benwinding** [contentful/contentful.js#982]
## Context

- Using latest npm package: `contentful` version `9.1.4`
- API docs reference: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entry/get-a-single-entry/console
- ![image](https://user-images.githubusercontent.com/11782590/140713192-33081301-e38b-4f1e-9899-586abbde08ee.png)

## Expected Behavior

According to the API docs,  shouldn't the `Sys` type have the fields `updatedBy` and `publishedBy`? 

I would have thought it would be on this type:

https://github.com/contentful/contentful.js/blob/1eecf7a7fdc63794f6e69af40df0b4948de1ca3f/index.d.ts#L152-L168

## Possible Solution

Add fields to the `Sys` type

**Comment by harleyharl** [comment]
I'm also wondering why some properties are missing. I want to access the "version" property, but these are the only properties I can access: 

![Screen Shot 2021-11-19 at 11 03 57 AM](https://user-images.githubusercontent.com/33185785/142504593-ac42da0e-c1cc-4053-8bb7-b0842c3cdbb1.png)

**Comment by marcolink** [comment]
Hi @benwinding, @harleyharl 

the fields you're referencing, are only available on the contentful management API. This library is only consuming data from the contentful delivery API, and therefore exposing a subset of the data.
