### ISSUE TITLE
How to sort posts in reverse chronology?

### ISSUE THREAD

**Issue by imujjwal96** [contentful/contentful.js#99]

**Comment by Khaledgarbaya** [comment]
Hi there,
It would be nice if you provide some context of your usage in the description.
But based on your title you can achieve that like this : 

```js
client.getEntries({content_type:'contentTypeID', 'order':'-sys.createdAt'})
```

**Comment by imujjwal96** [comment]
Oh! Thanks a lot for the soultion.
